### ISSUE TITLE
Can we remove `"min-versions"` if no supported hhvm version does not support a feature?

### ISSUE THREAD

**Issue by lexidor** [hhvm/user-documentation#1005]
Pages like https://docs.hhvm.com/hack/asynchronous-operations/concurrent warn you that this feature is not available if you are not at least on version 4.6. The oldest supported version is 4.56, which is a full year older than 4.6. Do we want to keep these legacy notices around?

**Comment by jjergus** [comment]
Agreed, feel free to remove any such references you find, I'll probably do the same when I run into any.
