### ISSUE TITLE
"De-sugers" typo

### ISSUE THREAD

**Issue by dunnbobcat** [hhvm/user-documentation#1006]
Please complete the information below:

# Where is the problem?

https://docs.hhvm.com/hack/asynchronous-operations/await-as-an-expression-spec
Pipe BinaryExpression 

# What is the problem?

"De-sugers" should be "de-sugars"

--------------------------------

Pipe BinaryExpression

--------------------------------

 - Build ID: HHVM=HHVM-4.98.0:HSL=v4.93.1:2021-03-04T00:33:54+0000:1fa47f258c6b68f8ec01899aa82fd6ffa0957109
 - Page requested: /hack/asynchronous-operations/await-as-an-expression-spec
 - Page requested at: Thu, 04 Mar 2021 16:40:14 +0000
 - Controller: GuidePageController

**Comment by AndrewDiMola** [comment]
Fixed in https://github.com/hhvm/user-documentation/commit/e4b9f92d163c85ea8ec7884191aaed1f832976ba.
