### ISSUE TITLE
Description is not clear enough.

### ISSUE THREAD

**Issue by reazuddindotcom** [hhvm/user-documentation#1021]
Please complete the information below:

# Where is the problem?

Description is not clear enough.

# What is the problem?

Replace this line - 
"Given a KeyedTraversable with nullable values, returns a new dict with those entries removed"

With - 
"Given a KeyedTraversable with nullable values, returns a new dict with null entries removed"

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.102.0:HSL=v4.94.0:2021-04-09T18:33:31+0000:1fa47f258c6b68f8ec01899aa82fd6ffa0957109
 - Page requested: /hsl/reference/function/HH.Lib.Dict.filter_nulls/
 - Page requested at: Tue, 13 Apr 2021 00:48:47 +0000
 - Controller: APIClassPageController

**Comment by lexidor** [comment]
The current text is indeed a bit misleading. I like your suggestion. The text came from [this comment](https://github.com/hhvm/hsl/blob/b60b845787b69c498ab5e062b7563afb696744f8/src/dict/select.php#L146) in the hsl repository. If you'd like to be credited for your description, you can edit the comment in github. When the next release happens, the page will get updated automatically.

**Comment by reazuddindotcom** [comment]
Thanks. I will update the comment.

**Comment by AndrewDiMola** [comment]
@reazuddindotcom let me know if you still want to work on this change, otherwise I can update the line!
