### ISSUE TITLE
"Its'" is not a word.

### ISSUE THREAD

**Issue by griznet** [hhvm/user-documentation#1023]
Please complete the information below:

# Where is the problem?
https://docs.hhvm.com/hack/contexts-and-capabilities/introduction

On first line where it states:

Contexts and capabilities provide a way to specify a set of capabilities for a function's implementation and a permission system for **its'** callers.

# What is the problem?

It's is a contraction, meaning a shorter or "contracted" form of "it is" or "it has." (Example: It's going to rain.)

Its is a possessive pronoun meaning, "belonging to it," or a "quality of it" (Example: The carrier lost its license) or (Example: Its color is red.)

**And there's absolutely, positively no such word as its'.**

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.102.0:HSL=v4.94.0:2021-04-09T18:33:31+0000:1fa47f258c6b68f8ec01899aa82fd6ffa0957109
 - Page requested: /hack/contexts-and-capabilities/introduction
 - Page requested at: Wed, 14 Apr 2021 16:16:19 +0000
 - Controller: GuidePageController

**Comment by Wilfred** [comment]
Thanks.
