### ISSUE TITLE
Not able to curl an existing hhconfig from hhast from github

### ISSUE THREAD

**Issue by funfun0737** [hhvm/user-documentation#1031]
Please complete the information below:

# Where is the problem?

https://docs.hhvm.com/hack/getting-started/starting-a-real-project
the first command listed in "An Example" Section
```
curl https://raw.githubusercontent.com/hhvm/hhast/master/.hhconfig > .hhconfig
```
# What is the problem?

```
➜  first curl https://raw.githubusercontent.com/hhvm/hhast/master/.hhconfig > .hhconfig

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL: no alternative certificate subject name matches target host name 'raw.githubusercontent.com'
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```
--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.110.0:HSL=v4.108.1:2021-05-18T22:29:20+0000:1fa47f258c6b68f8ec01899aa82fd6ffa0957109
 - Page requested: /hack/getting-started/starting-a-real-project
 - Page requested at: Mon, 24 May 2021 23:37:07 +0000
 - Controller: GuidePageController

**Comment by fredemmott** [comment]
The error message indicates a problem with your ISP or network connection, for example, a wifi login page.
- check you don't need to login for wifi
- you might find it useful to open https://raw.githubusercontent.com/hhvm/hhast/master/.hhconfig in a browser and see what happens
- as the message suggests, try https://curl.haxx.se/docs/sslcerts.html
