### ISSUE TITLE
one of the IO\request_input() should be IO\request_output()

### ISSUE THREAD

**Issue by funfun0737** [hhvm/user-documentation#1035]
Please complete the information below:

# Where is the problem?

https://docs.hhvm.com/hsl/reference/interface/HH.Lib.IO.Handle/
```
IO\request_input(), IO\request_input(), or IO\request_error(); these used for all kinds of requests, including both HTTP and CLI requests.
```
# What is the problem?
one of the `IO\request_input()` should be `IO\request_output()`

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.110.0:HSL=v4.108.1:2021-05-26T15:49:52+0000:1fa47f258c6b68f8ec01899aa82fd6ffa0957109
 - Page requested: /hsl/reference/interface/HH.Lib.IO.Handle/
 - Page requested at: Thu, 27 May 2021 04:13:11 +0000
 - Controller: APIClassPageController

**Comment by AndrewDiMola** [comment]
Thanks @funfun0737! Update should be in soon!

**Comment by fredemmott** [comment]
FYI, as this documentation is generated for doccomments in HHVM itself, the fix will not be visible until docs.hhvm.com as a whole is updated to a version of HHVM that is released after that commit :)
