### ISSUE TITLE
[Bug][Quick Fix] Link to Generics is broken

### ISSUE THREAD

**Issue by shirleypatterson** [hhvm/user-documentation#1036]
Please complete the information below:

# Where is the problem?

The paragraph copy directly under the Reified Generics headline.

# What is the problem?

The link to "Generics" is broken. It points to localhost:8080 instead of docs.hhvm.com.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.110.0:HSL=v4.108.1:2021-05-27T19:05:46+0000:1fa47f258c6b68f8ec01899aa82fd6ffa0957109
 - Page requested: /hack/reified-generics/reified-generics
 - Page requested at: Fri, 28 May 2021 15:39:49 +0000
 - Controller: GuidePageController

**Comment by lexidor** [comment]
It could very well have been me. Thanks for your issue. I have removed the host from the link.

_It works on my machine_ strikes again 😃.
