### ISSUE TITLE
Deprecated Support is out of date by several years

### ISSUE THREAD

**Issue by lexidor** [hhvm/user-documentation#1055]
# Where is the problem?

Deprecated support for hhvm 3.18 and Ubuntu 14.04.

# What is the problem?

This hhvm version is not supported.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.117.0:HSL=v4.108.1:2021-07-07T22:16:22+0000:1fa47f258c6b68f8ec01899aa82fd6ffa0957109
 - Page requested: /hhvm/installation/release-schedule
 - Page requested at: Fri, 16 Jul 2021 00:19:46 +0000
 - Controller: GuidePageController

**Comment by AndrewDiMola** [comment]
Thanks! I updated support here: https://docs.hhvm.com/hhvm/installation/deprecated-support
