### ISSUE TITLE
Update Repo / About description with Slack space, instead of Twitter profile

### ISSUE THREAD

**Issue by AndrewDiMola** [hhvm/user-documentation#1063]
![image](https://user-images.githubusercontent.com/5179225/128061066-c673de78-92ed-463e-aa83-f25099c826a7.png)

https://twitter.com/HHVMDocCommits

I can log-in and make a post on the above twitter to redirect people there too. This format doesn't seem useful anymore. And is inactive / misleading.

**Comment by Wilfred** [comment]
Ouch, looks like https://twitter.com/HHVMDocCommits stopped tweeting in 2019.

I'm not sure there's any super useful URL beyond the main site itself. I've removed that link from the description.
