### ISSUE TITLE
Redirect URLs without trailing slash to URL with trailing slash

### ISSUE THREAD

**Issue by daviddoran** [hhvm/user-documentation#108]
For example, this returns a 404 error:

http://beta.docs.hhvm.com/hack/reference/class/Set/map

But with a trailing slash this works fine:

http://beta.docs.hhvm.com/hack/reference/class/Set/map/

**Comment by JoelMarcey** [comment]
@fredemmott If we hit a `\FastRoute\Dispatcher::NOT_FOUND`, can't we just check the the last character of the `path` and if there is a `/`, remove it or if there is not a `/`, add it to the end, and then route the request again? 

Something like that?

**Comment by fredemmott** [comment]
This should really be built into HHVMDocumentationSite instead of the router, though I'm not entirely sure about the cleanest way to do that.
