### ISSUE TITLE
[ Imcorrect information ] Await as an expression spec allows await on the RHS of a `|>` operator, but this is a typechecker error.

### ISSUE THREAD

**Issue by lexidor** [hhvm/user-documentation#1080]
# Where is the problem?

The literal text:
```
Allowed: $x |> (await $$) de-sugars into (await $x)
```

# What is the problem?

This is a typechecker error.
```HACK
$x = async {
  return 5;
};
$x |> (await $$);
```

```
Parsing[1002] await cannot be used as an expression right of a pipe operator.
```

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.121.0:HSL=v4.108.1:2021-08-27T21:48:30+0000:1fa47f258c6b68f8ec01899aa82fd6ffa0957109
 - Page requested: /hack/asynchronous-operations/await-as-an-expression-spec
 - Page requested at: Sun, 05 Sep 2021 17:39:50 +0000
 - Controller: GuidePageController

**Comment by Wilfred** [comment]
@AndrewDiMola this is an interesting case. It looks like the implemented version of `await` expressions does not exactly match the spec you removed in #1079.

Given that we've removed the spec page in the docs, I think this can be closed. @lexidor do you think there's anything else we should do?

**Comment by AndrewDiMola** [comment]
Removing that spec page has already provided utility! Will close soon unless @lexidor has any other thoughts to add.

**Comment by lexidor** [comment]
Nothing important. The spec mentions the `and` and `or` operators which got killed years ago.
