### ISSUE TITLE
I can not able to run this in winows11

### ISSUE THREAD

**Issue by jayedsikder** [hhvm/user-documentation#1086]
Please complete the information below:

# Where is the problem?

- e.g. "The section describing how widgets work"

# What is the problem?

- e.g. "It doesn't explain that widgets are singletons"

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.121.0:HSL=v4.108.1:2021-09-14T01:50:02+0000:1fa47f258c6b68f8ec01899aa82fd6ffa0957109
 - Page requested: /hack/expressions-and-operators/new
 - Page requested at: Thu, 16 Sep 2021 05:15:09 +0000
 - Controller: GuidePageController

**Comment by fredemmott** [comment]
Sorry, Windows is not currently a supported platform. You might want to try WSL2+Ubuntu or Docker
