### ISSUE TITLE
Update to latest HHVM

### ISSUE THREAD

**Issue by fredemmott** [hhvm/user-documentation#1087]
- we have new HSL functions that should be documented
- soft-blocked by https://github.com/facebook/hhvm/issues/8898

**Comment by AndrewDiMola** [comment]
reference: https://hhvm.com/blog/2021/09/16/hhvm-4.127.html

**Comment by fredemmott** [comment]
I updated us to 4.130 since this issue, and am currently working on 4.134

**Comment by AndrewDiMola** [comment]
ah, thought you were calling out something specifically to document from that specific release
