### ISSUE TITLE
Remove style="foo" from IncludeExamplesFilter, add a CSS class instead

### ISSUE THREAD

**Issue by fredemmott** [hhvm/user-documentation#109]

**Comment by JoelMarcey** [comment]
![screenshot 2015-11-18 17 44 40](https://cloud.githubusercontent.com/assets/3757713/11260051/49dd8472-8e1c-11e5-9b10-ac492255d21f.png)
![screenshot 2015-11-18 17 43 31](https://cloud.githubusercontent.com/assets/3757713/11260050/49dd388c-8e1c-11e5-874b-172995c0daa9.png)

**Comment by JoelMarcey** [comment]
I changed the CSS to blue, and it worked too. So I wasn't see a cached red or anything.

Changed it back to red though
