### ISSUE TITLE
Please update documentation on this function, thank you

### ISSUE THREAD

**Issue by Aaron1Alicia** [hhvm/user-documentation#1105]
Please complete the information below:

# Where is the problem?

- the whole page

# What is the problem?

- There is basically no description on the function besides function signature

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.130.0:HSL=v4.108.1:2021-11-02T21:15:45+0000:1fa47f258c6b68f8ec01899aa82fd6ffa0957109
 - Page requested: /hack/reference/function/HH.is_late_init_prop_init/
 - Page requested at: Thu, 04 Nov 2021 04:32:41 +0000
 - Controller: APIClassPageController

**Comment by AndrewDiMola** [comment]
Looking into this!

**Comment by AndrewDiMola** [comment]
It's related to the `__LateInit` attribute -- not recommended, generally, in production code.

More details here: https://docs.hhvm.com/hack/attributes/predefined-attributes#__lateinit
