### ISSUE TITLE
gmail

### ISSUE THREAD

**Issue by yoyfunkid** [hhvm/user-documentation#1113]
Please complete the information below:

# Where is the problem?

- e.g. "The section describing how widgets work"

# What is the problem?

- e.g. "It doesn't explain that widgets are singletons"

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.134.0:HSL=v4.108.1:2021-11-12T20:20:45+0000:1fa47f258c6b68f8ec01899aa82fd6ffa0957109
 - Page requested: /search
 - Page requested at: Sun, 14 Nov 2021 23:53:28 +0000
 - Controller: SearchController

**Comment by lexidor** [comment]
It appears this issue was created accidentally, it is empty.
