### ISSUE TITLE
What do the asterisks in the Arrays Cheat Sheet mean?

### ISSUE THREAD

**Issue by robertquitt** [hhvm/user-documentation#1115]
Please complete the information below:

# Where is the problem?

https://docs.hhvm.com/hack/arrays-and-collections/introduction#arrays-cheat-sheet

# What is the problem?

There are two asterisks with no accompaniment

![image](https://user-images.githubusercontent.com/6463052/141966354-6c410396-6ad4-429c-8403-55a2963a7cdd.png)

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.134.0:HSL=v4.108.1:2021-11-15T21:25:05+0000:1fa47f258c6b68f8ec01899aa82fd6ffa0957109
 - Page requested: /hack/arrays-and-collections/introduction
 - Page requested at: Tue, 16 Nov 2021 10:10:44 +0000
 - Controller: GuidePageController

**Comment by AndrewDiMola** [comment]
Good catch. This was the asterisk note that is no longer there.

> $container can be a Hack Array, Hack Collection, or PHP array.

I can add it back in but perhaps just as:

> $container can be a Hack Array or Hack Collection
