### ISSUE TITLE
Showing me a type without the [inherited] methods defined on it is pretty useless

### ISSUE THREAD

**Issue by samuel-messing** [hhvm/user-documentation#1125]
Trying to use Hacklang for Advent of code.

A documentation file like this: https://docs.hhvm.com/hsl/reference/interface/HH.Lib.File.CloseableReadHandle/

Is basically useless? Maybe I'm not sure how to use this website correctly... but I want to see the methods defined on a type. I'm trying to read in a text file, and every thing just links to interfaces like this with no methods defined. Even if they're not *defined* on this type, and come from a class that this type extended or an interface it implemented, I think this documentation would only be useful if I could see those methods here.

**Comment by fredemmott** [comment]
At a minimum, it should link to the the interfaces, but inlining the methods (with a '// Inherited from Foo') would definitely be good too.

**Comment by samuel-messing** [comment]
Thank you for improving the title!

Yeah, just to build on this. I'm new to Hack, and I was trying to do Advent of Code and looking up how to read lines from a file. It felt clicking through all the documentation like things were really sparse and made it much slower to get going. I think this would have a huge impact on improving the usability of the documentation, especially for newbies like myself.

Are the docs autogenerated? Is there a tool that does it? If it's relatively simple I'd be willing to give it a try.

**Comment by fredemmott** [comment]
They're generated, primarily with https://github.com/hhvm/hh-apidoc , but this codebase extends them a bit.

There's also support for hand-written examples, but IMO it's probably a better use of time to fix the auto-generated stuff first, then add examples, rather than to hand-write examples that try to make up for the bad reference docs.

**Comment by samuel-messing** [comment]
Woohoo! Thank you @fredemmott for writing that PR! I noticed https://docs.hhvm.com/hsl/reference/interface/HH.Lib.IO.ReadFDHandle/ doesn't yet have your updated change. I'm not finding anything about the release cycle for docs.hhvm.com in this repo... just wanted to check that its expected not to be out yet?

**Comment by fredemmott** [comment]
Several third-party changes have broken the deployment recently, been a bit of whackamole. All should be resolved as of yesterday, should be able to pick this up soon.

**Comment by samuel-messing** [comment]
<3 <3 <3 Thank you!

**Comment by fredemmott** [comment]
A corresponding release of hh-apidoc is needed; as it's a backwards-incompatible change, I'm not going to do that on a friday.

**Comment by fredemmott** [comment]
That's not enough: docs.hhvm.com generates its' own index, but does it at a later stage. This needs to be moved earlier for the generation to be aware of the inherited methods
