### ISSUE TITLE
HHVM compilation fails on aarch64

### ISSUE THREAD

**Issue by hlitz** [hhvm/user-documentation#1130]
Please complete the information below:

# Where is the problem?

HHVM compilation fails for aarch64 (ARM)

# What is the problem?

third-party/rustc tries to execute an x86 binary which fails on aarch64
  /hhvm/hphp/hack/scripts/build_rust_to_ocaml.sh: line 65: /hhvm/build/third-party/rustc/bundled_rust-prefix/bin/cargo: cannot execute binary file: Exec format error

In the process of compiling rustc, the make file downloads the tarball:
module='https://static.rust-lang.org/dist/2021-10-21/rust-nightly-x86_64-unknown-linux-gnu.tar.gz'
within
/third-party/rustc/bundled_rust-prefix/src/bundled_rust-stamp/bundled_rust-urlinfo.txt

How can  we propagate the aarch64 to the rustc compile step?

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.136.0:HSL=v4.108.1:2021-12-02T18:46:15+0000:1fa47f258c6b68f8ec01899aa82fd6ffa0957109
 - Page requested: /hhvm/installation/building-from-source
 - Page requested at: Sat, 04 Dec 2021 00:19:47 +0000
 - Controller: GuidePageController

**Comment by fredemmott** [comment]
Sorry, HHVM currently only supports x86_64; this is something we hope to change, but is not currently considered a bug.

That said:

- please file any similar issues or pull requests against the facebook/hhvm repository
- if you wanted to give this a try, you'd want to start at https://github.com/facebook/hhvm/blob/master/third-party/rustc/CMakeLists.txt and https://github.com/facebook/hhvm/blob/0e43a8e3e5fc92e191217f9e7d4cf85849bbaa13/CMake/HPHPFunctions.cmake#L513
