### ISSUE TITLE
Typo about ?? operator's type

### ISSUE THREAD

**Issue by davidpichardie** [hhvm/user-documentation#1131]
Please complete the information below:

# Where is the problem?

- section "Usages"
 
# What is the problem?

- It is written that (T & nothing) is just T. This is very confusing I think. I'm unsure where & is formally defined but this looks like an intersection of types. nothing is the empty type, so T&nothing is not equivalent to T (except if T is nothing). The type of the ?? operator is a "union". And indeed "T union nothing" is equivalent to T.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.136.0:HSL=v4.108.1:2021-12-02T18:46:15+0000:1fa47f258c6b68f8ec01899aa82fd6ffa0957109
 - Page requested: /hack/built-in-types/nothing
 - Page requested at: Mon, 06 Dec 2021 07:46:41 +0000
 - Controller: GuidePageController

**Comment by lexidor** [comment]
Ah, I believe that is an error of mine. I always mix up the notation for union `(a | b)` and intersection `(a & b)`. You are correct here. No value can be an intersection of T and nothing. An intersection with nothing is always nothing, whereas a union with nothing is always T.
