### ISSUE TITLE
ct

### ISSUE THREAD

**Issue by sscloud88** [hhvm/user-documentation#1133]
Please complete the information below:

# Where is the problem?

- e.g. "The section describing how widgets work"

# What is the problem?

- e.g. "It doesn't explain that widgets are singletons"

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.136.0:HSL=v4.108.1:2021-12-07T01:40:35+0000:1fa47f258c6b68f8ec01899aa82fd6ffa0957109
 - Page requested: /hack/XHP/extending
 - Page requested at: Tue, 07 Dec 2021 10:01:02 +0000
 - Controller: GuidePageController

**Comment by lexidor** [comment]
This issue is empty. If you need help filling out the template, feel free to leave a comment below.
