### ISSUE TITLE
Incorrect parentheses

### ISSUE THREAD

**Issue by its-your-favorite** [hhvm/user-documentation#1142]
Please complete the information below:

# Where is the problem?

Contexts & Capabalities > Local Operators

# What is the problem?

Incorrect parentheses in the english, also confusing.

I see the wording "In the world where all these contexts (and matching capabilities exist), some or all may be included within the defaults context." In english grammar, remarks in parentheses should be removable without changing the meaning of the sentence. Perhaps "exist" should be outside of the parentheses here.

But while we're at it, I'm still pretty confused at what "In the world where" means in this documentation. Am I to understand these contexts/capabilities don't already exist built in to HHVM? I thought all contexts/capabilities are defined in the "typechecker and runtime" so wouldn't that imply the set of contexts/capabilities that exist is hardcoded? 

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.136.0:HSL=v4.108.1:2022-01-03T04:48:47+0000:1fa47f258c6b68f8ec01899aa82fd6ffa0957109
 - Page requested: /hack/contexts-and-capabilities/local-operations
 - Page requested at: Tue, 04 Jan 2022 16:37:51 +0000
 - Controller: GuidePageController

**Comment by AndrewDiMola** [comment]
Agree it's a very confusing, theoretical sentence. Going to remove it entirely.

**Comment by AndrewDiMola** [comment]
Need to update the public docs, but, yes, the source of truth would be here: https://github.com/facebook/hhvm/tree/master/hphp/hack/hhi/coeffect
