### ISSUE TITLE
jlt

### ISSUE THREAD

**Issue by j3lli21** [hhvm/user-documentation#1143]
Please complete the information below:

# Where is the problem?

- e.g. "The section describing how widgets work"

# What is the problem?

- e.g. "It doesn't explain that widgets are singletons"

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.136.0:HSL=v4.108.1:2022-01-03T04:48:47+0000:1fa47f258c6b68f8ec01899aa82fd6ffa0957109
 - Page requested: /hhvm/basic-usage/introduction
 - Page requested at: Wed, 05 Jan 2022 01:39:34 +0000
 - Controller: GuidePageController

**Comment by lexidor** [comment]
This issue is empty. Please create a new issue and edit the template to provide information about the shortcoming you have found.
