### ISSUE TITLE
string encoding docs should mention `Regex\`

### ISSUE THREAD

**Issue by fredemmott** [hhvm/user-documentation#1154]
This page talks a lot about how `Str\` works with bytes vs characters; it should also mention that `Regex\` is primarily byte-based, unless the `/u` modifier is present in the pattern.

The `Regex\` docs should probably also mention this and link back to the string page.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.140.1:HSL=v4.108.1:2022-01-14T20:09:46+0000:1fa47f258c6b68f8ec01899aa82fd6ffa0957109
 - Page requested: /hack/built-in-types/string
 - Page requested at: Fri, 28 Jan 2022 17:35:19 +0000
 - Controller: GuidePageController

**Comment by AndrewDiMola** [comment]
Adding a line in my soon-to-submitted PR. On the reference side, I'm working on adding @guide references to the Str\ and Regex\ namespaces, and will also add a note there.
