### ISSUE TITLE
Hack API reference docs don't indicate which parameters and return types are nullable

### ISSUE THREAD

**Issue by daviddoran** [hhvm/user-documentation#116]
For example, these methods all have a nullable return type:

- http://staging.docs.hhvm.com/hack/reference/class/Vector/firstValue/
- http://staging.docs.hhvm.com/hack/reference/class/Vector/get/

This method takes a single nullable argument:

- http://staging.docs.hhvm.com/hack/reference/class/Vector/setAll/

But they're displaying as non-nullable.

**Comment by JoelMarcey** [comment]
Good find. :+1: 

Not sure how far down the tree this goes. We get the information from hhi/hni files. Then create a YAML tree. Then render. Etc.

cc @fredemmott

**Comment by sorawee** [comment]
Can we reopen this issue? Although http://staging.docs.hhvm.com/hack/reference/class/Vector/firstValue/ shows 

> Tv - The first value in the current Vector, or null if the Vector is empty.

But the signature of the function is still 

```
public function firstValue(): Tv
```

This should actually be

```
public function firstValue(): ?Tv
```

**Comment by JoelMarcey** [comment]
It is on the actual live site too:

https://docs.hhvm.com/hack/reference/class/HH.Vector/firstValue/

I noticed in the `.hhi` file, that it does show `?Tv` .. https://github.com/facebook/hhvm/blob/3d171f73f2becfe4976a2920581f53b7dd0350e6/hphp/hack/hhi/collections/Vector.hhi#L362

@fredemmott --- This worked before though, I think, right?

**Comment by fredemmott** [comment]
We still have the param one (https://staging.docs.hhvm.com/hack/reference/class/HH.Vector/setAll/) btu not the return types.

As usual for regressions, please open a new issue.
