### ISSUE TITLE
Map::set is perhaps not semantically equivalent to []

### ISSUE THREAD

**Issue by smeenai** [hhvm/user-documentation#121]
The [documentation for `Map::set`](http://beta.docs.hhvm.com/hack/reference/class/Map/set/) states:

> `$map->set($k,$v)` is semantically equivalent to `$map[$k] = $v` (except that `set()` returns the current `Map`).

However, if `$k` isn't currently present in the map, `set` will throw an exception, whereas the `[]` form will insert a new key. I'm not completely sure how "semantic equivalence" is defined in this context, but I think this is a fairly significant behavior difference.

**Comment by fredemmott** [comment]
This looks like a duplicate of #117  ? cc @JoelMarcey

**Comment by smeenai** [comment]
Not quite. That was referencing the documentation of the [`Map` class](http://beta.docs.hhvm.com/hack/reference/class/Map/) (and there was a followup pertaining to [`Map::add`](http://beta.docs.hhvm.com/hack/reference/class/Map/add/)). This is a different issue.

**Comment by fredemmott** [comment]
Thanks :)

**Comment by JoelMarcey** [comment]
Internal diff: D2704592
