### ISSUE TITLE
Incorrect spelling under Enums page

### ISSUE THREAD

**Issue by KendrickAng** [hhvm/user-documentation#1213]
Please complete the information below:

# Where is the problem?

- The Built-in types -> Enums page

# What is the problem?
Simple spelling error - `contant` should be `constant`
![image](https://user-images.githubusercontent.com/38814428/167902560-581a665a-b7d8-4eef-aab4-29f9c6655d6f.png)

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.154.0:HSL=v4.108.1:2022-05-03T20:54:00+0000:1fa47f258c6b68f8ec01899aa82fd6ffa0957109
 - Page requested: /hack/built-in-types/enum
 - Page requested at: Wed, 11 May 2022 16:18:18 +0000
 - Controller: GuidePageController

**Comment by AndrewDiMola** [comment]
Thanks for finding that typo @KendrickAng!
