### ISSUE TITLE
Re-merge ini wiki into the docs

### ISSUE THREAD

**Issue by JoelMarcey** [hhvm/user-documentation#123]
I heard there were some updates to the [HHVM ini wiki](https://github.com/facebook/hhvm/wiki/INI-Settings) via @jazzdan.

We need to keep that wiki in sync with our table in these docs until we launch the docs and make that the source of truth and redirect the wiki to it.

**Comment by jazzdan** [comment]
Ah apologies, I totally missed [this page](http://beta.docs.hhvm.com/hhvm/configuration/INI-settings) that duplicates that information. I should be able to port those over on Monday if no one else gets to it before then.

**Comment by JoelMarcey** [comment]
No worries @jazzdan -- the wiki is //technically// official right now :)

If I haven't gotten to it by Monday, please, yes feel free to send a pull request for those changes. I will accept immediately :)
