### ISSUE TITLE
Does not show how to instantiate an instance.

### ISSUE THREAD

**Issue by hacklanguser** [hhvm/user-documentation#1277]
https://docs.hhvm.com/hack/built-in-types/shape

This shows you how to declare a shape type but, what good is it if it doesn't show you how to instantiate an instance of one of these declared types?

Specifically I want to know how to instantiate with values.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.164.0:HSL=v4.108.1:2022-07-26T17:24:38+0000:1fa47f258c6b68f8ec01899aa82fd6ffa0957109
 - Page requested: /hack/built-in-types/shape
 - Page requested at: Mon, 01 Aug 2022 00:32:44 +0000

**Comment by lexidor** [comment]
Shapes can be created with the literal syntax shown here:
https://docs.hhvm.com/hack/built-in-types/shape#shape-values

**Comment by hacklanguser** [comment]
I'm asking about how to use shape types, not literals. For example:

```
type SpecialShape('some_prop'=string)

# Okay, how do I make an instance of SpecialShape?
i_want_one = SpecialShape("some_prop"="how_is_this_supposed_to_work") 
```

**Comment by lexidor** [comment]
```HACK
type TColor = shape('r' => int, 'g' => int, 'b' => int);

function abc(int $r, int $g, int $b): TColor {
  return shape('r' => $r, 'g' => $g, 'b' => $b);
}
```

The `type` keyword creates an alias. `TColor` is now a shorthand for `shape('r' => int, 'g' => int, 'b' => int)`. You can use a shape literal to make any shape you'd like. You don't have to mention the name of the type alias you are building. Any shape with integer rgb keys (and no extra keys) is a TColor.

**Comment by hacklanguser** [comment]
Thanks for explaining. Closing this since I see that it does say this in the documentation

> Any shape value that has all of the required fields (and no undefined fields - unless the shape permits them) is considered a value of type Server; the type is not specified when creating the value.
