### ISSUE TITLE
request_time

### ISSUE THREAD

**Issue by akhapre** [hhvm/user-documentation#1303]
Please complete the information below:

# Where is the problem?

- e.g. "The section describing how widgets work"

# What is the problem?

- e.g. "It doesn't explain that widgets are singletons"

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.164.0:HSL=v4.108.1:2022-10-17T19:11:04+0000:1fa47f258c6b68f8ec01899aa82fd6ffa0957109
 - Page requested: /
 - Page requested at: Wed, 19 Oct 2022 04:13:46 +0000
 - Controller: HomePageController

**Comment by lexidor** [comment]
Try `HH\global_get('_SERVER')['REQUEST_TIME_FLOAT']` to get the request start time as a float.
