### ISSUE TITLE
Update documentation on Starting A Real Project to reflect move of hhvm/hsl

### ISSUE THREAD

**Issue by connordoner** [hhvm/user-documentation#1318]
Please complete the information below:

# Where is the problem?

The documentation page on [Starting A Real Project](https://docs.hhvm.com/hack/getting-started/starting-a-real-project), hosted at <docs.hhvm.com>.

# What is the problem?

It asks the user to install [hhvm/hsl](https://github.com/hhvm/hsl), which it appears will be moved into HHVM soon. The documentation should likely be updated to reflect this when complete.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.164.0:HSL=v4.108.1:2022-11-08T19:08:34+0000:1fa47f258c6b68f8ec01899aa82fd6ffa0957109
 - Page requested: /hack/getting-started/starting-a-real-project
 - Page requested at: Mon, 14 Nov 2022 04:12:34 +0000
 - Controller: GuidePageController

**Comment by fredemmott** [comment]
> which it appears will be moved into HHVM soon

This was completed a while ago; the repository still exists separately as it's more convenient to work/test on the HSL there, but it's just a copy of https://github.com/facebook/hhvm/tree/master/hphp/hsl nowadays

**Comment by connordoner** [comment]
Thanks, Fred! Appreciate the clarification.

**Comment by fredemmott** [comment]
Sorry, to clarify, people *should not* need to manually install HSL - the docs are not up to date

Even though it's unneeded, it will work though - hhvm/hsl is now a 'stub' composer package for compatibility.

**Comment by connordoner** [comment]
Sorry, I hope my original comment didn't come across as sarcastic, as I came to the same conclusion as you've since stated.

Would it help if I submit a PR for the docs?
