### ISSUE TITLE
The "Report a problem or make a suggestion" link is not centered

### ISSUE THREAD

**Issue by jamesgpearce** [hhvm/user-documentation#132]
![image](https://cloud.githubusercontent.com/assets/90942/11354981/d32ad1a2-9205-11e5-93b5-47358f1c6e3d.png)

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2015-11-23T22:06:58+0000:d140164987ca743497f6d1295941525daa65a12a:cd53d644d5ba6bd89af5e778425fea90fac2092b
 - Page requested: /hhvm/
 - Page requested at: Tue, 24 Nov 2015 01:14:57 +0000

**Comment by fredemmott** [comment]
It is centered, at least for me - your cropped image doesn't include the full page.
