### ISSUE TITLE
Hack & HHVM in toolbar jump around

### ISSUE THREAD

**Issue by jamesgpearce** [hhvm/user-documentation#133]
The two words are of different length, so they skip around when toggling between them. Either make logo+name the same length for both or have them keep their ordinality regardless of which is highlighted.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2015-11-23T22:06:58+0000:d140164987ca743497f6d1295941525daa65a12a:cd53d644d5ba6bd89af5e778425fea90fac2092b
 - Page requested: /hack/
 - Page requested at: Tue, 24 Nov 2015 01:16:14 +0000

**Comment by matthewjohnston4** [comment]
Fixed by leaving out some imported SCSS rules in a33d80d665755c9e8f13b5f877879f2feb0663fc
