### ISSUE TITLE
404: /manual/en/install.php

### ISSUE THREAD

**Issue by Riism** [hhvm/user-documentation#1335]
Please complete the information below:

# How I got to this page:

- e.g. "I clicked a link on <address of other site>"

# What I expected to find here:

- e.g. "Documentation that tells me how to <do something>"

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.164.0:HSL=v4.108.1:2023-03-17T21:45:14+0000:1fa47f258c6b68f8ec01899aa82fd6ffa0957109
 - Page requested: /manual/en/install.php
 - Page requested at: Sat, 18 Mar 2023 02:12:16 +0000

**Comment by Wilfred** [comment]
I don't see anything wrong here, this page doesn't exist. Was this linked somewhere?
