### ISSUE TITLE
Provide short URL redirects

### ISSUE THREAD

**Issue by simonwelsh** [hhvm/user-documentation#143]
The current docs site provides short URL access to pages based on string matches (e.g. http://docs.hhvm.com/map is a short version for http://docs.hhvm.com/manual/en/class.hack.maptktv.php)

Would be nice if the new docs provided something similar.

It seems that error.php does a string-based match against the docbook filenames and then directly renders what it finds. Redirecting makes more sense and only searching on things that can actually be used in code (e.g. class, method and function names) rather than on every file/folder would make things much nicer.

For methods, the PHP docs use `classname.methodname` for the lookup.

**Comment by fredemmott** [comment]
One option for the same use is to provide a couple of OpenSearch plugins, one for search (using the existing endpoint),and one for jumping to exact matches

**Comment by fredemmott** [comment]
whoops, wrong button

**Comment by fredemmott** [comment]
![screen shot 2015-12-09 at 3 23 23 pm](https://cloud.githubusercontent.com/assets/360927/11702124/e90f847e-9e88-11e5-89e7-5c530fe99646.png) will be working in a bit
