### ISSUE TITLE
Show type signatures in class references

### ISSUE THREAD

**Issue by jabagawee** [hhvm/user-documentation#153]
I think pages like http://beta.docs.hhvm.com/hack/reference/class/Map/ should have a quick synopsis of the type signatures for methods on that class. Either that, or the argument and return types should be included next to the method names in the "Interface Synopsis"

**Comment by fredemmott** [comment]
note to self: `FunctionMarkdownBuilder::getSignature()` should probably be moved to Stringify for htis

**Comment by daviddoran** [comment]
Agreed. @fredemmott I think something like we have internally where we list the type signatures and summaries for all of the methods in a class would be super useful. I often ⌘-f on the page for things like `: ?string` to find a method that returns a nullable string, for example.

**Comment by jabagawee** [comment]
@daviddoran sounds like something like [Hoogle](https://github.com/ndmitchell/hoogle) would be cool, but that would be a way bigger feature request

**Comment by fredemmott** [comment]
Screenshot and explanation of that styling in attached commit.

**Comment by fredemmott** [comment]
Live, http://docs.hhvm.com/hack/reference/class/Vector/ for example
