### ISSUE TITLE
I can't see how that code can produce that output!

### ISSUE THREAD

**Issue by jamesgpearce** [hhvm/user-documentation#156]
--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2015-12-02T22:44:21+0000:259cf8689cb41cf9ca7ec970c171968bffd57b31:36e427972db5e5417a380631a18f74818d594282
 - Page requested: /hack/getting-started/getting-started
 - Page requested at: Thu, 03 Dec 2015 14:38:31 +0000

**Comment by JoelMarcey** [comment]
Um, I can't either. And I don't know why it was changed. Let me look at commit history.

**Comment by JoelMarcey** [comment]
Looks like the `Animal` example was replaced with something seemingly simpler. But some of the output files weren't changed.

I will talk with @jwatzman and @fredemmott this morning about the example change. But in the meantime, I will fix what is there for now.

**Comment by daviddoran** [comment]
PS: It would be very cool if we automatically compared the `.out` files to the `.expectf` patterns during unit testing to catch this.

**Comment by JoelMarcey** [comment]
@daviddoran Ha ha ha!! @jwatzman and I were literally talking about this. And yes, a script that did all the testing and comparing that could be put in our `bin` directory would be useful. I will see if I have time before launch.

**Comment by JoelMarcey** [comment]
Although in this particular case, that script wouldn't have helped...

We have a `.no.auto.output` file for this because we don't have the output directly after the code like most other examples. 

So this output was added manually.

**Comment by JoelMarcey** [comment]
But the script in general is a good idea, I think.

https://github.com/hhvm/user-documentation/issues/157
