### ISSUE TITLE
Create run all test script

### ISSUE THREAD

**Issue by JoelMarcey** [hhvm/user-documentation#157]
Create a script that runs the test runner for HHVM, the typechecker and compares any .example.xxx.out file with .xxx.expectf file.

**Comment by fredemmott** [comment]
This should be PHPUnit.

**Comment by fredemmott** [comment]
Not sure I'll do all of this, but I'll get the basics there.

**Comment by fredemmott** [comment]
Usage is one out of:

```
hhvm vendor/bin/phpunit tests/
bin/test-staging.sh
REMOTE_TEST_HOST=127.0.0.1:8080 hhvm vendor/bin/phpunit --group remote tests/
```
