### ISSUE TITLE
Do we need to expose certain PHP-based APIs specifically in our API docs?

### ISSUE THREAD

**Issue by JoelMarcey** [hhvm/user-documentation#161]
e.g.,

`ReflectionType`
`phpinfo`

cc @fredemmott

**Comment by JoelMarcey** [comment]
The reason for this is that HHVM has either a bit different behavior for some functions (like `phpinfo`) or added functionality like `ReflectionType`.

**Comment by fredemmott** [comment]
I don't know if we care about phpinfo() being different. It outputs a string of HTML that has /some/ info. Do we care about more?

**Comment by JoelMarcey** [comment]
I was just thinking about the various different config options between the two that get output. But the specifics maybe don't matter. So, cool, yeah, we can leave out `phpinfo`.

Is there any other APIs that we need to worry about you think?

**Comment by SiebelsTim** [comment]
A note on zend_sorting for the `sort()` functions would be nice too. 
You see an issue about zend_sorting at github every now and then...

**Comment by fredemmott** [comment]
I think we could just add <<__HipHopSpecific>> to these and it'll work

**Comment by fredemmott** [comment]
Won't be doing this, due to https://hhvm.com/blog/2017/09/18/the-future-of-hhvm.html
