### ISSUE TITLE
Add links to Hack Spec and GitHub Repo from the docs

### ISSUE THREAD

**Issue by JoelMarcey** [hhvm/user-documentation#164]
Maybe at the bottom of the front page? Or in the sidebar? 

Possibly in the footer, but not sure about that.

**Comment by JoelMarcey** [comment]
Assigning myself to think about this a bit more. There was some chat between @fredemmott and I about whether a link to the Hack spec is needed or not? Maybe the spec is just linked from a revamped hacklang.org instead? 

The docs repo on the other hand ... we seemed to agree that might be useful. Maybe a small link in the footer of each page or something?

**Comment by simonwelsh** [comment]
Something I've seen in other github-backed documentation is a link to the markdown file used to generate the page, making it easier to submit small edits.

**Comment by fredemmott** [comment]
I have mixed feelings about that, given that if a change is wanted to an example instead of the text, it rapidly gets much more involved and filing an issue instesad is probably the better option for people who aren't planning many changes.

**Comment by fredemmott** [comment]
Reassigning as Matthew probably has some ideas about where this should go.

**Comment by Wilfred** [comment]
The spec is no longer maintained, but we should link to this repo.
