### ISSUE TITLE
asio curl_exec needs examples

### ISSUE THREAD

**Issue by fredemmott** [hhvm/user-documentation#167]
--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2015-12-04T21:57:38+0000:4c3ea2879ef44c06996d326412a4d498e39a6be4:089fad97483d47b54be4a7684bd33a16c8db0f33
 - Page requested: /hack/reference/function/HH.Asio.curl_exec/
 - Page requested at: Fri, 04 Dec 2015 22:50:47 +0000

**Comment by JoelMarcey** [comment]
First part of fix is D2731115
