### ISSUE TITLE
Headings are hidden under the nav bar when using anchors

### ISSUE THREAD

**Issue by simonwelsh** [hhvm/user-documentation#168]
Please complete the information below:

# What is the problem?

When using an anchor, the heading is hidden under the top bar.

For example, http://docs.hhvm.com/hack/typechecker/modes#decl-mode scrolls you to the "Decl mode" section but the "Decl mode" heading is hidden under the top bar.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2015-12-04T21:57:38+0000:4c3ea2879ef44c06996d326412a4d498e39a6be4:089fad97483d47b54be4a7684bd33a16c8db0f33
 - Page requested: /hack/typechecker/modes
 - Page requested at: Fri, 04 Dec 2015 22:51:33 +0000

**Comment by matthewjohnston4** [comment]
Fixed in 8a7c55aa4812c67abf960a50e17a9e673ba69499
