### ISSUE TITLE
placeholder variable: suppress output

### ISSUE THREAD

**Issue by fredemmott** [hhvm/user-documentation#169]
The typechecker bans it, and the whole point of this page is that using $_ is not allowed; showing it working is confusing.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2015-12-04T23:13:16+0000:09a12875e831327fbf5be42a9c0198c688af2433:bfa816e32c7b1a74e7aaee3d2688af2112439003
 - Page requested: /hack/other-features/placeholder-variable
 - Page requested at: Sat, 05 Dec 2015 05:23:53 +0000

**Comment by JoelMarcey** [comment]
@fredemmott Placeholder variables *are* supported. Did you mean some other page?

**Comment by fredemmott** [comment]
Writing to them is, reading from them isn't.
