### ISSUE TITLE
Internal anchors need to be offset

### ISSUE THREAD

**Issue by demetris** [hhvm/user-documentation#171]
Please complete the information below:

# Where is the problem?

As an example, this link:

<http://docs.hhvm.com/hhvm/installation/linux#debian-8-wheezy>

# What is the problem?

When you click the link, the anchor is hidden below the top bar. It needs to be offset.

Cheers!

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2015-12-04T23:13:16+0000:09a12875e831327fbf5be42a9c0198c688af2433:bfa816e32c7b1a74e7aaee3d2688af2112439003
 - Page requested: /
 - Page requested at: Sat, 05 Dec 2015 18:35:40 +0000

**Comment by fredemmott** [comment]
#178
