### ISSUE TITLE
404: /hack/async/intro - broken link

### ISSUE THREAD

**Issue by shivam-mangla** [hhvm/user-documentation#175]
Please complete the information below:

# How I got to this page:

I clicked on **Async: Intro** on <http://docs.hhvm.com/hack/reference/interface/HH.AsyncIterator/>.

# What I expected to find here:

Documentation for async introduction. I believe that [this](http://docs.hhvm.com/hack/async/introduction) is the correct link for the same. Please fix the broken link.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2015-12-04T23:13:16+0000:09a12875e831327fbf5be42a9c0198c688af2433:bfa816e32c7b1a74e7aaee3d2688af2112439003
 - Page requested: /hack/async/intro
 - Page requested at: Sun, 06 Dec 2015 22:06:09 +0000

**Comment by SiebelsTim** [comment]
It's *every* Link to intro in the reference.

**Comment by JoelMarcey** [comment]
Yep. See comment on #176 . I wil fix this.

I am going to close this as a duplication. 

Thanks
