### ISSUE TITLE
404: /hack/collections/intro

### ISSUE THREAD

**Issue by Daniel15** [hhvm/user-documentation#176]
I clicked the "Collections: Intro" link at http://docs.hhvm.com/hack/reference/class/Set/ which brought me to a 404 :cry: 

--------------------------------

 - Build ID: 2015-12-04T23:13:16+0000:09a12875e831327fbf5be42a9c0198c688af2433:bfa816e32c7b1a74e7aaee3d2688af2112439003
 - Page requested: /hack/collections/intro
 - Page requested at: Mon, 07 Dec 2015 00:09:23 +0000

**Comment by JoelMarcey** [comment]
Ah -- good catch. We renamed "intro" to "introduction" and I need to change the HHVM docs to reflect this. Thanks.

**Comment by JoelMarcey** [comment]
Internal D2730199
