### ISSUE TITLE
Sets don't have values, they have keys

### ISSUE THREAD

**Issue by admdikramr** [hhvm/user-documentation#177]
Please complete the information below:

# Where is the problem?

"Since Sets do not have keys, it returns the first value."

# What is the problem?

Sets do have keys. They do not have values. Although the keys are like values to many people, in that they have value, and in that the value-add constructor loads new keys into the set.

Less flippantly, the right way to note this caveat is to note that for sets the keys and values are the same thing. :)

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2015-12-04T23:13:16+0000:09a12875e831327fbf5be42a9c0198c688af2433:bfa816e32c7b1a74e7aaee3d2688af2112439003
 - Page requested: /hack/reference/class/Set/firstKey/
 - Page requested at: Mon, 07 Dec 2015 05:01:10 +0000

**Comment by simonwelsh** [comment]
For all intents and purposes, Sets do not have keys. That they do in practice is an implementation detail that should not be included in the documentation or relied on in code.

```hack
  $a = Set {'a', 'b'};
  $foo = $a['a'];
  $a['c'] = 'c';
```

Both those accesses are invalid in Hack, with the `$a['c'] = 'c';` being invalid at runtime too.

**Comment by JoelMarcey** [comment]
Hmmm... the definition I have always known (and is corraborated by @oyamauchi's book) is that a `Set` is an "ordered set of unique *values*" with no mentioned of how they are indexed, etc. like is done with `Vector` and `Map`.

I think the more confusing thing is that `firstKey` exists for a `Set` to begin with. I believe it is confusing. Implementation-wise, the `Set` has a key (=== value), but the user shouldn't have to know that, I don't think.

I am going to close this issue for bookkeeping. If we have more information re: this needing to actually be changed to say `Set`s have keys, then we can reopen.
