### ISSUE TITLE
404: /manual/en/ref.array.php

### ISSUE THREAD

**Issue by jek584** [hhvm/user-documentation#178]
Please complete the information below:

# How I got to this page:

I googled "hack arrays"

# What I expected to find here:

Docs on hack array functions

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2015-12-07T21:53:30+0000:a3ef760c946ccd086a95cc421503ba78c88cd59b:6b6620fca32d7de309e9fd72c2d93c15cd77576d
 - Page requested: /manual/en/ref.array.php
 - Page requested at: Mon, 07 Dec 2015 22:10:55 +0000

**Comment by fredemmott** [comment]
This is annoying... we've been giving a 404 for that, and it's in robots.txt, for over a week now :(

**Comment by fredemmott** [comment]
FYI, there is no such thing as Hack array functions, which is why we removed the page. You can still use PHP's ones, so it /should/ redirect to PHP.net. I'll look into why that isn't happening.

You might also want http://docs.hhvm.com/hack/collections/introduction
