### ISSUE TITLE
404: /manual/en/install.hack.conversion.php

### ISSUE THREAD

**Issue by yeonsh** [hhvm/user-documentation#179]
Please complete the information below:

# How I got to this page:

Clicked a link 'conversion tools' on the bottom of http://hacklang.org/

# What I expected to find here:

Web page about conversion tools but "The page you requested can't be found."

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2015-12-08T00:12:16+0000:01340a5dee16c523cdd5ca44617b3a217183b6d2:6b6620fca32d7de309e9fd72c2d93c15cd77576d
 - Page requested: /manual/en/install.hack.conversion.php
 - Page requested at: Tue, 08 Dec 2015 04:24:19 +0000

**Comment by JoelMarcey** [comment]
Thanks for finding this! This will land in our push tomorrow.
