### ISSUE TITLE
Got the debian releases round the wrong way..

### ISSUE THREAD

**Issue by MrSleeps** [hhvm/user-documentation#180]
# Where is the problem?

http://docs.hhvm.com/hhvm/installation/linux#debian-7-jessie

# What is the problem?

Isn't Debian 7 Wheezy and Debian 8 Jessie?

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2015-12-08T00:12:16+0000:01340a5dee16c523cdd5ca44617b3a217183b6d2:6b6620fca32d7de309e9fd72c2d93c15cd77576d
 - Page requested: /hhvm/installation/linux
 - Page requested at: Tue, 08 Dec 2015 04:35:50 +0000

**Comment by JoelMarcey** [comment]
Yes it is. Good catch. Fix coming up. :+1:

**Comment by JoelMarcey** [comment]
It will go live tomorrow. Thanks again.
