### ISSUE TITLE
Make subsection links discoverable

### ISSUE THREAD

**Issue by katherinez** [hhvm/user-documentation#181]
From here:
http://docs.hhvm.com/hack/enums/introduction

I want to be able to link directly to `Implicit Casting`

Something like

http://docs.hhvm.com/hack/enums/introduction/#Implicit_Casting

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2015-12-08T00:12:16+0000:01340a5dee16c523cdd5ca44617b3a217183b6d2:6b6620fca32d7de309e9fd72c2d93c15cd77576d
 - Page requested: /hack/enums/introduction
 - Page requested at: Tue, 08 Dec 2015 17:56:01 +0000

**Comment by fredemmott** [comment]
http://docs.hhvm.com/hack/enums/introduction#casting-to-underlying-type__implicit-casting

**Comment by fredemmott** [comment]
Any suggestions for making this more discoverable?

**Comment by katherinez** [comment]
**amazing** thank you.

But HOW did you get it? I was hovering over "Implicit Casting" expecting it to become a link .. I moved my mouse over seemingly the entire page and didn't find anything.

So maybe some change on hover over "Implicit Casting", or something next to "Implicit Casting" (like a hashtag)?

**Comment by JoelMarcey** [comment]
We have an issue #146 to have second level menu items shown. I think that will help a lot.

**Comment by JoelMarcey** [comment]
cc @matthewjohnston4

**Comment by fredemmott** [comment]
I'll see if I can hack something up more inline until that happens.

**Comment by fredemmott** [comment]
I pulled the ID out of the DOM in developer tools to get that link... :p

**Comment by fredemmott** [comment]
![screen shot 2015-12-08 at 2 17 19 pm](https://cloud.githubusercontent.com/assets/360927/11670428/a8f52204-9db6-11e5-98ca-57b6bec3e70e.png)

^^^ this shows up when the cursor is over a heading
