### ISSUE TITLE
Remove full links to API and php.net

### ISSUE THREAD

**Issue by JoelMarcey** [hhvm/user-documentation#182]
The API linkifiers are in place now...

https://github.com/hhvm/user-documentation/commit/8b82fcd1e14ff6f6c2874ad5c3d31aeb28fdfa02

https://github.com/hhvm/user-documentation/commit/520cbf035c1a35bde85425bf95617411fba046c4

So you can remove the references on both the HHVM docblock side and the documentation side.

**Comment by JoelMarcey** [comment]
Keep the guide links in place though

**Comment by fredemmott** [comment]
meh, close enough, fix up as encountered in future.
