### ISSUE TITLE
404: /hhvm/installation/release-schedule

### ISSUE THREAD

**Issue by danslo** [hhvm/user-documentation#183]
Please complete the information below:

# How I got to this page:

Clicked on link at https://github.com/facebook/hhvm/wiki/Release-Schedule

# What I expected to find here:

Release schedule page, which doesn't seem to exist on http://docs.hhvm.com/.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2015-12-08T21:50:03+0000:ecc5be051ea9bdb20cb3576290684dce9baf0c4d:9640202ab55c5e9ccb7f176d48f2d82465bbb18c
 - Page requested: /hhvm/installation/release-schedule
 - Page requested at: Wed, 09 Dec 2015 02:09:58 +0000

**Comment by JoelMarcey** [comment]
Ugh, my changes have pushed live yet. I will do another push with all these new links.

https://github.com/hhvm/user-documentation/commit/8366eebe6328ef3ef91915d5ea3bae97a6e41be3

**Comment by danslo** [comment]
Fair enough :-)
