### ISSUE TITLE
404: /manual/en/language.oop5.constants.php

### ISSUE THREAD

**Issue by ravigummadi** [hhvm/user-documentation#187]
Please complete the information below:

# How I got to this page:

- - - eg "I clicked a link on <address of other site>" - - -

# What I expected to find here:

- - - eg "Documentation tell me how to <do something>" - - -

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2015-12-09T18:27:10+0000:75b86a620d7b0512dc78ec599fb095fbbb99d616:8087d388b9570252e4a5a47baea416efb4da45e8
 - Page requested: /manual/en/language.oop5.constants.php
 - Page requested at: Wed, 09 Dec 2015 18:54:14 +0000

**Comment by fredemmott** [comment]
What led you to that URL? That URL is for PHP5 documentation, not Hack/HHVM.

**Comment by fredemmott** [comment]
^ fixed in next push with that commit, leaving open as it would be good to know how you found that page

**Comment by ravigummadi** [comment]
Fred,

I tried a google search "Hack Const" and its the first link. Attached is
the screenshot.

**Comment by fredemmott** [comment]
Thanks. Hopefully this will fix themselves over the next few days as google re-indexes.
