### ISSUE TITLE
Footer not centered properly on pages without nav

### ISSUE THREAD

**Issue by fredemmott** [hhvm/user-documentation#188]
![screen shot 2015-12-09 at 11 03 48 am](https://cloud.githubusercontent.com/assets/360927/11695544/9c635728-9e64-11e5-9742-e0bb557276a5.png)
![screen shot 2015-12-09 at 11 04 21 am](https://cloud.githubusercontent.com/assets/360927/11695547/9f1542e2-9e64-11e5-84d2-7dfc0bd66e34.png)

**Comment by fredemmott** [comment]
Heh, alternatively, the see something wrong thing shouldn't be centered on the 404 page

**Comment by AndrewDiMola** [comment]
footerPanel and footerWrapper were inheriting center text-align prop from notFoundMessage. Reset footer CSS to initial text-align value so they don't inherit on 404 pages. Fixed here: https://github.com/hhvm/user-documentation/commit/45f03ffb6986d73793ff2b58e7dac322713070ab.

![image](https://user-images.githubusercontent.com/5179225/109551343-7158d280-7a9e-11eb-9c38-c64dd7538307.png)
