### ISSUE TITLE
404: /hhvm/advanced-usage/fastcgi

### ISSUE THREAD

**Issue by war59312** [hhvm/user-documentation#189]
# How I got to this page:

I clicked a link on "http://docs.hhvm.com/hhvm/advanced-usage/introduction" titled "FastCGI".

# What I expected to find here:

Documentation on FastCGI of course.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2015-12-09T22:15:53+0000:98afdd71b35b995c761963ec241f9ed5d12f9299:583baeccc5dc786e2263350f6c57c12a6f0b4838
 - Page requested: /hhvm/advanced-usage/fastcgi
 - Page requested at: Wed, 09 Dec 2015 23:32:08 +0000

Edit:

Correct URL Is: http://docs.hhvm.com/hhvm/advanced-usage/fastCGI

That said I think you are better off making CGI lower case.

So it's case sensitive. Really should fix that. ;)

If you make lower case and still have case sensitive on then remember to fix button on:

http://docs.hhvm.com/hhvm/advanced-usage/admin-server

That's how I found correct page.

http://docs.hhvm.com/hhvm/basic-usage/proxygen also points to lower case cgi.

Probally should do a full web site search for "fastCGI" and replace with "fastcgi".

**Comment by JoelMarcey** [comment]
Thanks. Good catch. Fix upcoming.

**Comment by war59312** [comment]
No problem.

**Comment by JoelMarcey** [comment]
They will go live with the next push

**Comment by war59312** [comment]
10-4

Thanks!
