### ISSUE TITLE
A whole load of 404 on /hack/collections/interfaces

### ISSUE THREAD

**Issue by fredemmott** [hhvm/user-documentation#190]
Most (all?) of the function links in the bottom table are 404s

Found by a test I'm adding...

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2015-12-09T22:15:53+0000:98afdd71b35b995c761963ec241f9ed5d12f9299:583baeccc5dc786e2263350f6c57c12a6f0b4838
 - Page requested: /hack/collections/interfaces
 - Page requested at: Thu, 10 Dec 2015 00:40:14 +0000

**Comment by fredemmott** [comment]
Full output: https://gist.github.com/fredemmott/692fe5d32622cde70c9c
I'll look into the undefined index errors. The rest appear to either be this page, or `/hack/someguide/` => `/hack/someguide/introduction` - I'll improve the test to deal with that.

**Comment by JoelMarcey** [comment]
:+1: I will fix the links

Your test suite is going to be the glue that keeps this together :)

**Comment by JoelMarcey** [comment]
Oooh -- this more than links not existing. Basically, it is that `contains()` isn't a method on `ConstSet` at all. :/

**Comment by JoelMarcey** [comment]
because `contains()` is on `ConstSetAccess` which we don't expose (and I don't really think we should). Bugger.

**Comment by JoelMarcey** [comment]
I am going to add those back in, add a new table and go on. 

I will also test your linkifying too. Won't add specific links :)
