### ISSUE TITLE
Add a helpful tip section somewhere on the site

### ISSUE THREAD

**Issue by JoelMarcey** [hhvm/user-documentation#195]
Maybe the footer. Maybe the sidebar.

The /j/searchterm stuff is great, but many people may not initially know it is available.

**Comment by JoelMarcey** [comment]
@fredemmott Do you think we should say anything about us supporting opensearch anywhere in the footer? (or anywhere else on the site?)?

If not I will probably close this.

**Comment by fredemmott** [comment]
Not really - if people know what opensearch is they'll probably notice anyway (as you don't need to manually add it in modern browsers), and if not, they're unlikely to look into it.
