### ISSUE TITLE
Complete list of 404s

### ISSUE THREAD

**Issue by fredemmott** [hhvm/user-documentation#198]
Test incoming. PHPUnit output: https://gist.github.com/fredemmott/99d0e753ba1ce6122434

**Comment by fredemmott** [comment]
Well, this doesn't include relative links '../foo.md' - will look into those shortly.

**Comment by JoelMarcey** [comment]
Maybe I should be consistent in the links and remove all the `.md` style links and replace it with the `/hack/guides`, etc. style links?

**Comment by JoelMarcey** [comment]
A lot of your failing tests were breadcrumb related. See fix above...

Looking at the others.

**Comment by fredemmott** [comment]
nice catch!
