### ISSUE TITLE
FAQ Question on Set

### ISSUE THREAD

**Issue by JoelMarcey** [hhvm/user-documentation#202]
> Why does $set->values() return Vector<Tv>, but $set->keys() return a Vector<mixed>?

Internal discussion about this might be interesting to the outside world.

**Comment by fredemmott** [comment]
Needs more back ticks :) mixed is interesting, not just because not tk, but why not array key?

**Comment by fredemmott** [comment]
Also, IIRC we want to fix this soon (3.12 hopefully)
