### ISSUE TITLE
Cannot Install

### ISSUE THREAD

**Issue by tommoholmes** [hhvm/user-documentation#203]
I cannot install hhvm in ubuntu 15.04

**Comment by JoelMarcey** [comment]
We need more information. 

How are you trying to install HHVM on Ubuntu 15.04? A package? Or compilation?

If package, did you follow instructions here: http://docs.hhvm.com/hhvm/installation/linux#ubuntu-15.04-vivid

If compilation, did you follow instructions here: http://docs.hhvm.com/hhvm/installation/building-from-source#ubuntu-15.04-vivid

Depending on answers to your questions, we might direct you to the HHVM issue queue.

**Comment by JoelMarcey** [comment]
I am going to close this assuming that you got it to work with the instructions above, or if you followed the instructions above and are having another problem, you could post directly to the HHVM repo.

Thanks.
