### ISSUE TITLE
Split out Router.php as a library

### ISSUE THREAD

**Issue by fredemmott** [hhvm/user-documentation#206]
https://github.com/hhvm/user-documentation/blob/master/src/site/Router.php

This could be made more re-usable:

 - more thought should go into the exception naming (some have 'HTTP', some don't) and interfaces - the 'getResponse' thing probably isn't appropriate
 - should use generics - eg:

```
namespace SomeLibrary;

class Router<
TBaseController,
TGETController as TBaseController,
TPostController as TBaseController> {
... similar stuff to what we have now
}
```

```
namespace HHVM\UserDocumentation;

class Router extends \SomeLibrary\Router<WebController, WebController, WebController> {
...
}
```

```
namespace SomeOtherSite;

class Router extends \SomeLibrary\Router<WebController,WebReadOnlyController,WebControllerWithWrites> {
...
}
```

cc @nikic and @SiebelsTim: I'd appreciate ideas/feedback :)

**Comment by SiebelsTim** [comment]
I first thought we might need an interface for the controller, but then I was surprised how decoupled the router is from all that.
However I think the WebController and friends should be included in that library and maybe also the HHVMDocumentationSite.
You'd still need a lot of work to get a site running with the router alone and I think the router alone is not *that* much of an improvement to FastRoute itself.

Having to just add in Routes and Controllers belonging to it and have a site running would be great for a library in my opinion.

**Comment by fredemmott** [comment]
so,there's much more passionate and varied opinions about controller structures IMO; could work of a few were provided, eg:

 - WebController to rule them all (eg docs site)
 - ReadController and WriteController always using GET/POST respectively 
 - The verb-heavy form of REST

The Site class would be cool, though will need a fair bit of thought into how to make exception handling flexible and nestable (eg making it so that "foo" 404 => 301 "foo/" 200 isn't a special case)

**Comment by fredemmott** [comment]
There's also the question of if it should use PSR-7 or include a more type-safe wrapped around it

**Comment by SiebelsTim** [comment]
If you're going for including useful controllers, the StaticResourcesController might be useful too.

**Comment by fredemmott** [comment]
That'd be fairly easy, but IMO in general the right thing to do is put it on a CDN; we didn't do that for this site because:

 - we want to keep it extremely easy for anyone else to deploy exactly what we've deployed
 - relatedly, we want to avoid external dependencies

**Comment by SiebelsTim** [comment]
It'd be nice for the "smaller" user as step into the language though.

**Comment by fredemmott** [comment]
This is in a usable state here: https://github.com/fredemmott/hack-router

More funky stuff here: https://github.com/fredemmott/hack-router-codegen

I'll send a PR to this repo to migrate at some point.
