### ISSUE TITLE
Live errors for review

### ISSUE THREAD

**Issue by fredemmott** [hhvm/user-documentation#210]
Some are likely reasonable to be 404. Output:

404: https://gist.github.com/fredemmott/4c9fd294b2e7aea7c49d
500:

```
/s/2fbe887a80845d08/css/main.css/	HTTP/1.1 500 hphp_invoke
/s/b55e75ece7149e89/css/main.css/	HTTP/1.1 500 hphp_invoke
/s/d062d8ca1a1fa6ff/js/APINavData.js/	HTTP/1.1 500 hphp_invoke
```

Script:

```
for path in $(<urls-uniq.txt); do HEADER=$(curl -I --silent http://127.0.0.1:8080$path | head -n 1); if ! echo "$HEADER" | egrep -q 'HTTP/1.1 (200|301)'; then  echo -e "$path\t$HEADER"; fi; done > errors
```

**Comment by fredemmott** [comment]
favicon.ico 404: Firefox 42 will sometimes go looking for this, I'm guessing before it loads the page. Logs show that the same user is also getting favicon.png

**Comment by fredemmott** [comment]
.../class/HH/Foo/Bar/ 404: already fixed, however http://www.majestic12.co.uk/projects/dsearch/mj12bot.php states that it intentionally re-tries 404s for some time

**Comment by fredemmott** [comment]
hw_* are hyperwave, documented on the polish PHP docs site (in english...) but not on the english site.

**Comment by JoelMarcey** [comment]
How do we want to support Hack specific shortcut stuff like:

```
arrayaccesstktv.offsetget
map
pairtv1tv2.tostring
```

Maybe we can have a router through `/j/search` or something, where we remove any `tk`, `tv`, etc. from the search since we don't have that anymore?

**Comment by fredemmott** [comment]
/maptktv.filter for example

**Comment by fredemmott** [comment]
With those diffs in, refined list with:

```
for path in $(<urls-uniq.txt); do
  HEADER=$(curl -I --silent http://127.0.0.1:8080$path)
  if ! echo "$HEADER" | egrep -q 'HTTP/1.1 (200|301)'; then
    if ! curl --silent http://127.0.0.1:8080$path | grep -q 'maybe you want'; then
      echo -e "$path\t$( echo "$HEADER" | head -n 1)"
    fi
  fi
done > errors
```

Result: https://gist.github.com/38e67e673b4c930e3f29

**Comment by fredemmott** [comment]
https://gist.github.com/ab5b1f8b139da4c47f07 10 fewer...

**Comment by fredemmott** [comment]
For getting the list of 404s out of the nginx log:

```
grep -v MK12Bot access.log | grep 'HTTP/1.1" 404' | egrep --only-matching '] "GET [^ ]+' | awk '{print $NF}' | sort | uniq
```

Ignoring MK12Bot as it intentionally looks at known 404s
