### ISSUE TITLE
Give big list of PHP INI settings that we support

### ISSUE THREAD

**Issue by fredemmott** [hhvm/user-documentation#216]
http://docs.hhvm.com/hhvm/configuration/INI-settings just links to the PHP list and says most are supported. the PHP list is fine for the actual documentation, but not specifying which are supported isn't.

**Comment by JoelMarcey** [comment]
Ref Revert: 2bd2b64f8a0d149f59a173bb177a0419dc48debd

**Comment by JoelMarcey** [comment]
![screenshot 2015-12-16 11 29 18](https://cloud.githubusercontent.com/assets/3757713/11851615/5dce877e-a3e8-11e5-975c-284d24b7df4e.png)
