### ISSUE TITLE
j/<attribute> doesn't redirect to the attribute

### ISSUE THREAD

**Issue by simonwelsh** [hhvm/user-documentation#220]
http://docs.hhvm.com/j/__Memoize redirects to the search, rather than the Attributes: Special page at the __Memoize anchor point.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2015-12-14T23:18:37+0000:fbcad638fac8f31c02b94edb3c6659b0c7b4560e:4eac8cbe94695ad0a14584a4d7fc99421fd7f074
 - Page requested: /search
 - Page requested at: Tue, 15 Dec 2015 19:19:26 +0000

**Comment by JoelMarcey** [comment]
Got a simple solution out there a pull request. Want to see if @fredemmott is ok with it.

**Comment by JoelMarcey** [comment]
Really /j search is for direct shortcuts to API reference; search otherwise. But I can see attributes being a special case.
