### ISSUE TITLE
Lots of hhvm-specific ini settings have no documentation

### ISSUE THREAD

**Issue by fredemmott** [hhvm/user-documentation#221]
Listed, but empty cells in table. 2x survey comments

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2015-12-16T00:19:45+0000:c6f9088e0b36ab1e2247f583425925c4eff3576a:4d00fb13c9e3724a084f82920e21837bae747e70
 - Page requested: /hhvm/configuration/INI-settings
 - Page requested at: Wed, 16 Dec 2015 18:04:21 +0000

**Comment by JoelMarcey** [comment]
This is my highest priority for the rest of the week. I want to get them all documented before Christmas :)

**Comment by JoelMarcey** [comment]
Well, not all have been documented, and certainly not before Christmas, but we are getting a lot closer now. Trying to go for 10-15 day.
