### ISSUE TITLE
Links in extension list are wrong

### ISSUE THREAD

**Issue by thewavelength** [hhvm/user-documentation#230]
# Where is the problem?

https://docs.hhvm.com/hhvm/extensions/introduction

# What is the problem?

Links in the extension list are wrong. Most of them point to ctype.

 - Build ID: 2015-12-18T23:24:12+0000:989c9dd19452720cbb0acda2731acecea2a48f19:8e8e633aef0e5b34ca96c181adab499d2343c47e
 - Page requested: /hhvm/extensions/introduction
 - Page requested at: Sun, 20 Dec 2015 13:26:57 +0000
 - Controller: GuidePageController

**Comment by SiebelsTim** [comment]
These are simply wrong in the markdown.

If anyone wants to fix this:

https://github.com/hhvm/user-documentation/blob/9b037c935af71573041944cc76b35d7c7699821b/guides/hhvm/05-extensions/01-intro.md
