### ISSUE TITLE
Can't use protected methods with inst_meth either

### ISSUE THREAD

**Issue by HRMsimon** [hhvm/user-documentation#244]
`inst_meth($this, 'protectedMethod')` gives `This is a protected method. You cannot use it with inst_meth.`

The warning on this page is only about private methods.

Also, there's no warning on [`inst_meth`](https://docs.hhvm.com/j/inst_meth) page itself.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2015-12-26T19:24:03+0000:777ca13ba74d6f13a4fa3d398950b9260cdd2760:0e853b502ae123b225bdbb3b61a75e10a9f459f6
 - Page requested: /hack/callables/special-functions
 - Page requested at: Mon, 28 Dec 2015 22:16:00 +0000
 - Controller: GuidePageController

**Comment by fredemmott** [comment]
Also the meth_caller() docs are wrong

**Comment by fredemmott** [comment]
![screencapture-172-25-46-196-8080-hack-callables-special-functions-1451344274185](https://cloud.githubusercontent.com/assets/360927/12027003/459e8ae6-ad75-11e5-94d9-21856b5b0ae9.png)

**Comment by JoelMarcey** [comment]
Looks good. The Callables introduction also discusses these a bit with examples.
