### ISSUE TITLE
Should have a link to the section on callable special functions

### ISSUE THREAD

**Issue by HRMsimon** [hhvm/user-documentation#245]
The `See also` section should have a link to https://docs.hhvm.com/hack/callables/special-functions

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2015-12-26T19:24:03+0000:777ca13ba74d6f13a4fa3d398950b9260cdd2760:0e853b502ae123b225bdbb3b61a75e10a9f459f6
 - Page requested: /hack/reference/function/HH.inst_meth/
 - Page requested at: Mon, 28 Dec 2015 22:18:08 +0000
 - Controller: APIGenericPageController

**Comment by JoelMarcey** [comment]
Internal diff: D2800956
