### ISSUE TITLE
Typechecker: Running - References a .hh_config file. Is this correct?

### ISSUE THREAD

**Issue by Server4001** [hhvm/user-documentation#248]
Please complete the information below:

# Where is the problem?

Typechecker: Running
https://docs.hhvm.com/hack/typechecker/running

# What is the problem?

The page references a .hh_config file. Is this correct? Or should it be .hhconfig (no underscore)?

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2015-12-29T22:41:18+0000:2e8e16d66883216bf44c9a804e4ae31170925aed:2ccf90dd9aaa1b34bf177704b509d6bec1d49e53
 - Page requested: /hack/typechecker/running
 - Page requested at: Sat, 02 Jan 2016 08:05:59 +0000
 - Controller: GuidePageController

**Comment by SiebelsTim** [comment]
The underscore is wrong. Feel free to send a PR :)

**Comment by Server4001** [comment]
@SiebelsTim, pull request submitted!

**Comment by JoelMarcey** [comment]
Fixed by: https://github.com/hhvm/user-documentation/commit/a3642f1cd3093ba8f708cd2ee71f6efc92ecf741

Thanks!
