### ISSUE TITLE
A number of problems with the Type Constants: Intro spec

### ISSUE THREAD

**Issue by RexJaeschke** [hhvm/user-documentation#258]
1. Abstract class

Class A itself needs to be declared abstract, as it contains 2 abstract members (Foo and Bar).

2. Concrete class

Change, "You can declare a type constant in a concrete class, but it requires a special type of syntax:"

to

"You can declare a type constant in a concrete class, but it requires different syntax:"

3. Concrete class

To be consistent with Abstract class, change

const type <name> as mixed = mixed;

to

const type <name> [as <constraint>] = <type>; // constraint optional; defaults to mixed

Then strike the second sentence in, "Basically you are declaring that the type constant can
be pretty much any type. And in any child class, if no type constraint is specified, then mixed
will be the default."

4. Concrete class

The following example won't compile:

class NA {
  const type Foo as mixed = mixed;
}

class C1 extends NA {
  const type Foo = int;
}

class C2 extends NA {
  const type Foo; // defaults to mixed
}

tc.php:69:7,8: This object is of type NS_type_constants\C2 (Typing[4142])
  tc.php:69:18,19: It is incompatible with this object of type NS_type_constants\NA
because some declarations are incompatible.
Read the following to see why:
  tc.php:70:14,16: Cannot re-declare this type constant as abstract
  tc.php:62:14,16: Previously defined here
tc.php:69:7,8: This class must be declared abstract, or provide an implementation for the abstract type constant 

'Foo' (Typing[4047])
  tc.php:70:14,16: Declaration is here
tc.php:70:14,16: This type constant is not declared as abstract, it must have an assigned type (NastCheck[3026])

I'm quite new to type constants, so still don't have a full understanding, but it seems to me that the "= <type>" can only be omitted if abstract is present. As such, in C2, "const type Foo" implies that Foo is abstract, yet C2 itself is not declared abstract.

Then the comment "// defaults to mixed" is confusing. Yes, the constraint may well have that default but the <type> doesn't default. And the fact that you've used "as mixed = mixed" is confusing. Which of these 2 mixed's are you referring to in the comment? If I understand correctly, class C1 also defaults to a mixed constraint.

5. Referencing the Type Constant

In

this::T;

remove the trailing semicolon, as we're talking about an expression, not a statement.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2016-01-09T02:22:10+0000:acb72069f49f946edaa4f53c1610f5bcdc484da0:9fabe36576fc89848617f8f22b36d30bdcebc74c
 - Page requested: /hack/type-constants/introduction
 - Page requested at: Sun, 10 Jan 2016 14:51:24 +0000
 - Controller: GuidePageController

**Comment by JoelMarcey** [comment]
I made a fix to the introduction, which I will push later today. 

Looking at it again, I am not convinced that the default to `mixed` information is correct. So I removed it all together.

I also think I am going to make a separate section on constraints too.

**Comment by JoelMarcey** [comment]
I made an entirely separate section on constraints, outside the introduction.

I am thinking about a few other things possibly to add as well.
