### ISSUE TITLE
Native C++ to HHVM

### ISSUE THREAD

**Issue by PhilGo20** [hhvm/user-documentation#259]
Please complete the information below:

# Where is the problem?

-

# What is the problem?

Is it possible to compile C++ with HHVM? A customer of ours is using HHVM and would like to use some of our C++ modules. How would we go about it?
--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2016-01-11T00:34:50+0000:054e7c946ab378efea71cc45b0493c7412e77596:d3c23223d1dbda60a8a7d2ec9cade319956c1cb0
 - Page requested: /
 - Page requested at: Tue, 12 Jan 2016 16:54:51 +0000
 - Controller: HomePageController

**Comment by fredemmott** [comment]
HHVM does not compile C++, however g++ can be used to compile C++ extensions for HHVM. See https://github.com/facebook/hhvm/wiki/Extension-API
