### ISSUE TITLE
Document the Hack pipe operator

### ISSUE THREAD

**Issue by JoelMarcey** [hhvm/user-documentation#266]
`|>`

**Comment by JoelMarcey** [comment]
https://github.com/facebook/hhvm/commit/992c816e19428ad3bae026702a0755827a3cba9c

**Comment by JoelMarcey** [comment]
See internal diff D2842828 for more context as well:

cc @paulbiss @dlreeves

**Comment by fredemmott** [comment]
https://docs.hhvm.com/hack/operators/pipe-operator
