### ISSUE TITLE
Clarify that <<__Memoize>> is request duration only; not lifetime.

### ISSUE THREAD

**Issue by JoelMarcey** [hhvm/user-documentation#269]
You need `memcache` or something similar for TTL to be across requests.

**Comment by JoelMarcey** [comment]
Entry here: https://docs.hhvm.com/hack/attributes/special#__memoize__gotchas , probably

**Comment by fredemmott** [comment]
apc might be a better alternative suggestion than memcache

**Comment by fredemmott** [comment]
I'm assuming the page has changed since this was filed: it's in gotchas, and in the main description of __Memoize now.
