### ISSUE TITLE
Reword proxygen section

### ISSUE THREAD

**Issue by fredemmott** [hhvm/user-documentation#27]
cc @jamesgpearce @JoelMarcey 

From our docs, it sounds like proxygen is a proxy server - all this stuff about proxying requests. Given we use (and proxygen describes itself) as a set of C++ libraries which among other things makes it easy to embed an HTTP server, this seems probably incorrect (unless you consider calling/implementing C++ methods proxying), and at the least confusing.

**Comment by JoelMarcey** [comment]
I have been normally trying to refer to it overall as HHVM's built-in web server. Maybe instead of saying "proxy the request", I can say "serve the request" ??
