### ISSUE TITLE
Sample code

### ISSUE THREAD

**Issue by paymog** [hhvm/user-documentation#274]
Please complete the information below:

# Where is the problem?

The whole article

# What is the problem?

There are no code samples for the Map class. 

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2016-01-22T23:00:49+0000:cc7774204c740a5dab75ab8bbeae2b108ac585e9:30dce805afa6dc6336f0d14e77a682f6cb54639d
 - Page requested: /hack/reference/class/Map/
 - Page requested at: Tue, 02 Feb 2016 23:11:09 +0000
 - Controller: APIGenericPageController

**Comment by fredemmott** [comment]
This is covered in the main collections documentation, linked to from the top.
