### ISSUE TITLE
HH\invariant documents only the first argument as being required

### ISSUE THREAD

**Issue by fredemmott** [hhvm/user-documentation#276]
- HHVM only requires one argument to invariant
- The typechecker requires at least two - the explanation is not optional

---

Please don't change anything below this point.

---
- Build ID: 2016-02-03T18:32:05+0000:d24f8c9d85900b1fb3756fa3b7ded196f50d6b03:9bc85b2582399b39fb8a3858e51e913ae4cd6afb
- Page requested: /hack/reference/function/HH.invariant/
- Page requested at: Fri, 05 Feb 2016 20:34:08 +0000
- Controller: APIGenericPageController

**Comment by lexidor** [comment]
This is the current definition. It is missing a `$format_string,`.
```
function invariant(
  \mixed $condition,
  \  FormatString<\PlainSprintf> ...$args,
): \void;
```

**Comment by AndrewDiMola** [comment]
is there a supported tag for @required or @optional? or just add explicitly in a line of text or description which is required for HHVM v. the typechecker?

Also looks like the page has evolved over the years: https://docs.hhvm.com/hack/reference/function/HH.invariant/

**Comment by Wilfred** [comment]
Yeah, looks like it's now fixed and mentions the format string parameter.
