### ISSUE TITLE
API Rendering fixes

### ISSUE THREAD

**Issue by JoelMarcey** [hhvm/user-documentation#28]
- [x] Will markdown syntax in docblocks render as markdown in the final API reference? It would make the docs look cleaner.
- [x]  Parameter types aren't being shown for methods if there aren't put in the docblock. For parameter types that are in docblocks (e.g., `AsyncMysqlClient`), the types do show. I think we were thinking of deducing the parameter type from the signature instead.
- [x] Empty parameters shouldn't show Parameters heading.
- [x] Alphabetize the listing of the class methods. I think right now they are ordered by how they are reflected upon in the HHI or HNI file, maybe.
- [x] Get any API examples associated with a method to show on the API page (e.g., we have examples for `AsyncMysqlXXX` and `MCRouterXXX` classes).
- [x] Everything says "Interface Synopsis" -- can we distinguish between classes, interfaces, etc.
- [x]  `@internal` seems to work not showing the docblock information for a method; but the method signature itself still shows in the docs. We need to link the `@internal` with not showing the method at all in the API reference.
- [x] do not include private methods
- [x] Render the links to guides when coming across an `@guide` tag in the docblock.

cc @fredemmott

**Comment by fredemmott** [comment]
Do we want to use @internal instead of an attribute? Seems a bit weird to have an attribute for HipHopSpecific but a docblock tag for this.

**Comment by JoelMarcey** [comment]
We could...

Custom attribute called `<__InternalOnly>` ?

I only used `@internal` because it was a builtin tag in phpdocumentor

**Comment by fredemmott** [comment]
The attribute would be easier to implement, and more consistent. Possibly __HHVMInternal instead?

**Comment by fredemmott** [comment]
(and hopefully we'll get rid of it soon by moving stuff to the __Systemlib namespace anyway...)

**Comment by JoelMarcey** [comment]
For classes yes ...

But for `private` constructors, it will still be useful.

**Comment by fredemmott** [comment]
`private` things shouldn't be documented anyway. If private functions are being documented, that's a bug.

**Comment by JoelMarcey** [comment]
I mostly see this in `AsyncMysql` classes.

Yeah, we are showing the `private` constructors in the API reference. So I tagged them with @internal and the docblock info doesn't show anymore, but the constructor signature is still displayed in the API reference.

**Comment by JoelMarcey** [comment]
Btw, I did think we were going to be able to blacklist things like `IndexAccess` and `ConstSetAccess`, but it looks like we need them be cause they declare key methods for the Collections classes. So I am documenting them in the hhi.

**Comment by fredemmott** [comment]
@internal is only meant to mark specific documentation as internal, not the thing being documented: http://manual.phpdoc.org/HTMLSmartyConverter/HandS/phpDocumentor/tutorial_tags.internal.pkg.htm

**Comment by JoelMarcey** [comment]
Ah, ok. Fair enough. Let's use the attribute if needed then.

However, the doc generator code should probably just throw out `private` methods.

**Comment by fredemmott** [comment]
Yep, that's a bug :)

**Comment by fredemmott** [comment]
All done \o\ \o/ /o/

**Comment by JoelMarcey** [comment]
\o/ \o/ ....
