### ISSUE TITLE
HH\invariant links to itself

### ISSUE THREAD

**Issue by TJ09** [hhvm/user-documentation#281]
Please complete the information below:
# Where is the problem?

"See also" on https://docs.hhvm.com/hack/reference/function/HH.invariant/
# What is the problem?

Link to "invariant" guide takes me back to the function reference for HH\invariant.

---

Please don't change anything below this point.

---
- Build ID: 2016-02-12T19:24:55+0000:58fe1d6065f81eec19d52e4efa1ffb791629df8d:c4260308b1d2c49a96a9d0d06751cf475796bd2e
- Page requested: /hack/reference/function/HH.invariant/
- Page requested at: Thu, 18 Feb 2016 00:20:58 +0000
- Controller: APIGenericPageController

**Comment by SiebelsTim** [comment]
Is this supposed to link to http://localhost:8080/hack/types/refining#invariant?

**Comment by fredemmott** [comment]
This is fixed with the new markdown pipeline.
