### ISSUE TITLE
want some help

### ISSUE THREAD

**Issue by MetaiR** [hhvm/user-documentation#287]
Please complete the information below:

# Where is the problem?

im using elementaryOs which is based on ubuntu 14.04 LTS
when i wanted to install hhvm in step two (sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0x5a16e7281be7a449)

# What is the problem?

i got this error message gpg: keyserver receive failed: keyserver error

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2016-03-01T23:48:01+0000:184cb7b546e1d21752c9c9c0b7b077e5f5ebc40d:35b5d05c52340a60b5770cd1007674f573c47949
 - Page requested: /hhvm/installation/linux
 - Page requested at: Thu, 03 Mar 2016 00:38:06 +0000
 - Controller: GuidePageController

**Comment by fredemmott** [comment]
You need to ask for help in an ubuntu support area; that isn't an area we can control.
