### ISSUE TITLE
Text cutoff in wide window

### ISSUE THREAD

**Issue by jrwats** [hhvm/user-documentation#288]
Please complete the information below:
# Where is the problem?

https://docs.hhvm.com/hack/attributes/special
I suspect some CSS rules are wrong for certain form factors (globally, not just this page)
https://docs.hhvm.com/s/12e18873438f7ec0/css/main.css
I suspect the (min-width: 1400px) rule 
# What is the problem?

When I drag the window to a wide enough point, text gets cut off (and even worse, the browser doesn't show it as scrollable)
![screenshot 2016-03-03 12 18 38](https://cloud.githubusercontent.com/assets/1821462/13508002/15ab7260-e13a-11e5-9aa6-6bea766a99c4.png)

![screenshot 2016-03-03 12 14 10](https://cloud.githubusercontent.com/assets/1821462/13507872/8a49caf0-e139-11e5-8930-39b82e81b31e.png)

---

Please don't change anything below this point.

---
- Build ID: 2016-03-01T23:48:01+0000:184cb7b546e1d21752c9c9c0b7b077e5f5ebc40d:35b5d05c52340a60b5770cd1007674f573c47949
- Page requested: /hack/attributes/special
- Page requested at: Thu, 03 Mar 2016 20:08:42 +0000
- Controller: GuidePageController

**Comment by AndrewDiMola** [comment]
Similar to https://github.com/hhvm/user-documentation/issues/304, closing because docs are now responsive.
