### ISSUE TITLE
Search result are not sorted by relevancy

### ISSUE THREAD

**Issue by andrii-korotkov** [hhvm/user-documentation#293]
Please complete the information below:

# Where is the problem?

In the search results

# What is the problem?

When I search for collection name (e.g. Vector), the relevant result appears at the bottom of results, since results from "Hack guides" are presented first. There are a lot of guides containing Vector, so I have to scroll to see the link to page about Vector in "Hack Classes" section.

I think reference to the Vector collection page should appear in the top as most relevant result.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2016-03-01T23:48:01+0000:184cb7b546e1d21752c9c9c0b7b077e5f5ebc40d:35b5d05c52340a60b5770cd1007674f573c47949
 - Page requested: /search
 - Page requested at: Tue, 15 Mar 2016 23:51:00 +0000
 - Controller: SearchController

**Comment by fredemmott** [comment]
Intentional - before this, people were frequently looking up the API reference for how to do one specific thing with eg Vectors, but not understanding the overall concepts (eg object semantics, not arrays), leading to many issues.
