### ISSUE TITLE
I'm Special

### ISSUE THREAD

**Issue by Orvid** [hhvm/user-documentation#296]
Please complete the information below:
# Where is the problem?

The MSVC section.
# What is the problem?

I _may_ not be an external contributor anymore. Also, that workaround list is no longer relevant.

---

Please don't change anything below this point.

---
- Build ID: 2016-03-01T23:48:01+0000:184cb7b546e1d21752c9c9c0b7b077e5f5ebc40d:35b5d05c52340a60b5770cd1007674f573c47949
- Page requested: /hhvm/installation/windows
- Page requested at: Tue, 22 Mar 2016 23:19:47 +0000
- Controller: GuidePageController

**Comment by fredemmott** [comment]
You're now special here too :p

**Comment by fredemmott** [comment]
https://github.com/hhvm/user-documentation/blob/master/guides/hhvm/01-installation/04-windows.md

**Comment by fredemmott** [comment]
:'(
