### ISSUE TITLE
Build list of HHVM-specific definitions by cross-referencing with PHP docs

### ISSUE THREAD

**Issue by fredemmott** [hhvm/user-documentation#3]
Current approach: check for `<<__HipHopSpecific>>`, use of generics/awaitables, or specific namespaces: https://github.com/hhvm/user-documentation/blob/master/src/ScannedDefinitionFilters.php#L10-L34

Also tried using class_exists()/function_exists() and friends: https://github.com/hhvm/user-documentation/commit/4f45ba649def19c22d1a7664f77db8527ac37f1f

I decided not to pursue that approach as a *complete* PHP build including all extensions needs to be present, which isnt' contributor-friendly.

**Comment by oyamauchi** [comment]
Does this mean just manually build a list of HH-specific things? Surely that would be easier than any automated approach.

**Comment by fredemmott** [comment]
We want to make sure that any future additions can be automatically detected. The list is likely to be fairly long (https://gist.github.com/fredemmott/131bc25a7d16e0e99f81 is the current automated result)

**Comment by oyamauchi** [comment]
Ah, OK. Separate point, though: wouldn't it be good if HH-specific things were, in fact, recognizable as such without consulting PHP docs? This is why we have the HH namespace and `hphp_` and `fb_` prefixes and whatnot.

Point being, maybe we should make it so that the current automation *is* correct, by enforcing (in code review) that any new HH-specific stuff has one of these telltale signs?

**Comment by fredemmott** [comment]
Ideally everything should be in the the HH or __SystemLib namespaces, hphp_ and fb_ prefixes should not exist, and <<__HipHopSpecific>> should only be needed for additional methods on standard PHP classes.

- some automation may be helpful to identify where this is not currently the case
- we don't want shipping new docs to be blocked by adapting www to cope with moving stuff to HH\

**Comment by oyamauchi** [comment]
I hacked up a script that tries to pull all function, class, and method references from a checkout of the php.net docbook source. I'll see how well it works.

**Comment by oyamauchi** [comment]
Here's a first pass at a list extracted from the PHP docs. I got it by extracting for every <refname> node in the reference section of the docs source tree. (The subtree en/reference/)

https://gist.github.com/oyamauchi/d8ac3efb55052abef4f7

And here's the result: things that exist in hhvm/hack that don't exist in this set. (I haven't subtracted the ones from your existing HH-specific list.)

https://gist.github.com/oyamauchi/eba1d8bafa7c04a805ac

There's a whole slew of extension functions like `magick*` and `draw*` that I'm not sure should be there. There are some interesting ones, though: all the AsyncMysql stuff, a bunch of Exception subclasses, the xdebug functions...

Assuming this is suitable, I can put up the script I used to generate it somewhere. To generate the list yourself, all you need is the script plus a checkout of the php.net docs tree (http://doc.php.net/tutorial/structure.php)

**Comment by fredemmott** [comment]
magick* and draw* aren't in upstream PHP - they're a clone of http://www.magickwand.org/

This is mostly suitable, we probably want to just blacklist magick* and draw*
