### ISSUE TITLE
Async iterators?

### ISSUE THREAD

**Issue by jwatzman** [hhvm/user-documentation#30]
The docs are missing any information and examples of async iterators. First, are they ready to be announced and documented -- I think so? Check with @jano. Second, do we want to document them, since they're such a niche feature -- probably? Third, actually coming up with not-totally-contrived examples and motivation is interesting; I'd probably go for some sort of streaming/reactive API? Or maybe an async API that fetches and returns its results in batches of 10000 or something, since there's a ton of results that are expensive to fetch in aggregate? (AIUI we don't use the feature much at FB, and this last example is one place where we do use it.)

**Comment by JoelMarcey** [comment]
I purposely didn't document them because I wasn't sure yet (1) if they were ready (2) are they going to benefit the user base as a whole.

I was actually thinking of blacklisting them from our API reference until we were sure what we wanted to do with them.

cc @fredemmott

**Comment by jano** [comment]
AsyncIterator interface, foreach (... await as ...) and async generators are stable, but there are no libraries yet that return AsyncIterators. Two possible use cases that would benefit the OSS community (which we don't support yet):

- MySQL result streaming (could be used to send a huge query to MySQL and process stuff on the PHP side one row at a time without requiring memory to store complete result)
- streamable curl client / pagelet server (no need to wait for the complete result before it's flushed to the user)

There's no harm in documenting them, but they are not many ways these features can be used yet.

**Comment by JoelMarcey** [comment]
@oyamauchi's book mentions them in a sorta not-just-in-passing way. I could take his lead in the user guide for now, if we want.

I did go ahead and document the `AsyncIterator` interfaces in the Hack hhi files (where we get part of our new API reference from). So they will be documented there for those that stumble upon them (if we decide to expose them in the end).
