### ISSUE TITLE
curl.namedPools isn't documented

### ISSUE THREAD

**Issue by jazzdan** [hhvm/user-documentation#300]
Please complete the information below:
# Where is the problem?

https://docs.hhvm.com/hhvm/configuration/INI-settings, in the supported PHP INI section.
# What is the problem?

`curl.namedPools` is not an INI option in PHP, so linking to the PHP documentation when you click on `curl.namedPools` doesn't really help. :\

---

Please don't change anything below this point.

---
- Build ID: 2016-03-25T19:44:16+0000:59945858b91b58253f39c91d5ff11f685e228917:ded7f690201f02c37531b00bb6a6fc0091e9945e
- Page requested: /hhvm/configuration/INI-settings
- Page requested at: Tue, 05 Apr 2016 14:06:49 +0000
- Controller: GuidePageController

**Comment by AndrewDiMola** [comment]
Abstracted out of PHP table with description added in https://github.com/hhvm/user-documentation/commit/5ad814af567cc3b2639773b456afcd6ccff42735.

**Comment by jazzdan** [comment]
Thanks @AndrewDiMola!
