### ISSUE TITLE
hhvm bin/build.php   error

### ISSUE THREAD

**Issue by javacty** [hhvm/user-documentation#303]
Fatal error: Uncaught exception 'HH\InvariantException' with message 'expected a type' in /opt/new/user-documentation/vendor/fredemmott/definition-finder/src/consumers/TypehintConsumer.php:147
Stack trace:
#0 /opt/new/user-documentation/vendor/fredemmott/definition-finder/src/consumers/TypehintConsumer.php(147): HH\invariant_violation()
#1 /opt/new/user-documentation/vendor/fredemmott/definition-finder/src/consumers/TypehintConsumer.php(9): FredEmmott\DefinitionFinder\TypehintConsumer->consumeType()
#2 /opt/new/user-documentation/vendor/fredemmott/definition-finder/src/consumers/FunctionAbstractConsumer.php(61): FredEmmott\DefinitionFinder\TypehintConsumer->getTypehint()
#3 /opt/new/user-documentation/vendor/fredemmott/definition-finder/src/consumers/ScopeConsumer.php(184): FredEmmott\DefinitionFinder\FunctionAbstractConsumer->getBuilder()
#4 /opt/new/user-documentation/vendor/fredemmott/definition-finder/src/consumers/ScopeConsumer.php(143): FredEmmott\DefinitionFinder\ScopeConsumer->consumeDefinition()
#5 /opt/new/user-documentation/vendor/fredemmott/definition-finder/src/consumers/NamespaceConsumer.php(32): FredEmmott\DefinitionFinder\ScopeConsumer->getBuilder()
#6 /opt/new/user-documentation/vendor/fredemmott/definition-finder/src/consumers/ScopeConsumer.php(168): FredEmmott\DefinitionFinder\NamespaceConsumer->getBuilder()
#7 /opt/new/user-documentation/vendor/fredemmott/definition-finder/src/consumers/ScopeConsumer.php(143): FredEmmott\DefinitionFinder\ScopeConsumer->consumeDefinition()
#8 /opt/new/user-documentation/vendor/fredemmott/definition-finder/src/FileParser.php(12): FredEmmott\DefinitionFinder\ScopeConsumer->getBuilder()
#9 /opt/new/user-documentation/vendor/fredemmott/definition-finder/src/FileParser.php(38): FredEmmott\DefinitionFinder\FileParser->__construct()
#10 /opt/new/user-documentation/src/build/RawYAMLBuildStep.php(41): FredEmmott\DefinitionFinder\FileParser::FromData()
#11 /opt/new/user-documentation/src/build/RawYAMLBuildStep.php(15): HHVM\UserDocumentation\RawYAMLBuildStep->buildSources()
#12 /opt/new/user-documentation/bin/build.php(62): HHVM\UserDocumentation\RawYAMLBuildStep->buildAll()
#13 /opt/new/user-documentation/bin/build.php(69): HHVM\UserDocumentation\build_site()
#14 {main}

Next exception 'FredEmmott\DefinitionFinder\ParseException' with message '/opt/new/hhvm/hphp/runtime/ext/array/ext_array.php:1392: expected a type' in /opt/new/user-documentation/vendor/fredemmott/definition-finder/src/FileParser.php:19
Stack trace:
#0 /opt/new/user-documentation/vendor/fredemmott/definition-finder/src/FileParser.php(38): FredEmmott\DefinitionFinder\FileParser->__construct()
#1 /opt/new/user-documentation/src/build/RawYAMLBuildStep.php(41): FredEmmott\DefinitionFinder\FileParser::FromData()
#2 /opt/new/user-documentation/src/build/RawYAMLBuildStep.php(15): HHVM\UserDocumentation\RawYAMLBuildStep->buildSources()
#3 /opt/new/user-documentation/bin/build.php(62): HHVM\UserDocumentation\RawYAMLBuildStep->buildAll()
#4 /opt/new/user-documentation/bin/build.php(69): HHVM\UserDocumentation\build_site()
#5 {main}
[root@192 user-documentation]# vim /opt/new/user-documentation/vendor/fredemmott/definition-finder/src/consumers/TypehintConsumer.php

**Comment by fredemmott** [comment]
What version of HHVM are you building against? I'm guessing master?

**Comment by javacty** [comment]
yes, latest, 
hhvm --version
HipHop VM 3.14.0-dev (rel)
Compiler: heads/master-0-g29e922eec4a445297bcc01035fa76edbd4dbf098
Repo schema: 8c5d808ceda42f8b87988b134894f69b9414719a

**Comment by fredemmott** [comment]
This is fixed by a dev-master fredemmott/definition-finder, though the Map documentation vanishes, and I want to trace down why that's happened before bumping this.

**Comment by fredemmott** [comment]
Map documentation moves to HH\Map, given HNI changes
