### ISSUE TITLE
doc page does not show an horizontal scroll bar

### ISSUE THREAD

**Issue by greenscientist** [hhvm/user-documentation#304]
Please complete the information below:
# Where is the problem?

Reading https://docs.hhvm.com/hack/async/introduction on my smallish laptop screen, I don't see the full width of the main pane. It does not show an horizontal scroll bar, so it's not easy to scroll left/right. 
It would be great to adjust width dynamically or be able to reduce the size of the TOC pane. 

(On firefox 44)
- \- - eg "It doesn't explain that widgets are singletons" - - -

---

Please don't change anything below this point.

---
- Build ID: 2016-03-25T19:44:16+0000:59945858b91b58253f39c91d5ff11f685e228917:ded7f690201f02c37531b00bb6a6fc0091e9945e
- Page requested: /hack/async/introduction
- Page requested at: Thu, 14 Apr 2016 13:30:29 +0000
- Controller: GuidePageController

**Comment by ThrashAbaddon** [comment]
![image](https://cloud.githubusercontent.com/assets/7493180/17059752/fdadaab4-5026-11e6-9e5b-adf61b2a0dd4.png)

It seems that the horizontal bar is on the very end of the page, which is inconvenient.

**Comment by AndrewDiMola** [comment]
Closing because docs are now responsive.
