### ISSUE TITLE
No update in Release Schedule of HHVM

### ISSUE THREAD

**Issue by corientdev** [hhvm/user-documentation#306]
Please complete the information below:

# Where is the problem?

https://docs.hhvm.com/hhvm/installation/release-schedule

# What is the problem?

No update since december 2015 i guess

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2016-03-25T19:44:16+0000:59945858b91b58253f39c91d5ff11f685e228917:ded7f690201f02c37531b00bb6a6fc0091e9945e
 - Page requested: /hhvm/installation/release-schedule
 - Page requested at: Fri, 15 Apr 2016 06:49:23 +0000
 - Controller: GuidePageController

**Comment by SiebelsTim** [comment]
@paulbiss More and more people want this ;)

**Comment by fredemmott** [comment]
Done here, waiting for push:

https://github.com/hhvm/user-documentation/commit/d041294fbeef2f1d578fd1f17fdd4baaff2feb90
