### ISSUE TITLE
vim README link in editors page is dead

### ISSUE THREAD

**Issue by Yostage** [hhvm/user-documentation#310]
Please complete the information below:

# Where is the problem?

The list of hack plugins for source editors, specifically the VIM one

# What is the problem?

the README link to https://github.com/hhvm/vim-hack/blob/master/README is 404

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2016-03-25T19:44:16+0000:59945858b91b58253f39c91d5ff11f685e228917:ded7f690201f02c37531b00bb6a6fc0091e9945e
 - Page requested: /hack/typechecker/editors
 - Page requested at: Thu, 21 Apr 2016 16:23:52 +0000
 - Controller: GuidePageController

**Comment by SiebelsTim** [comment]
It's `.md` for years.
https://github.com/hhvm/vim-hack/blob/master/README.md

**Comment by Orvid** [comment]
PR it then!

**Comment by SiebelsTim** [comment]
@Orvid I might as well push it, if I have the time :P

**Comment by fredemmott** [comment]
It's correct in the markdown - we remove .md from guide links, but should only do it for internal ones :(
