### ISSUE TITLE
Clarify that supporting all major distros !== packaging for all major distributions

### ISSUE THREAD

**Issue by laurfx** [hhvm/user-documentation#315]
Please complete the information below:

# Where is the problem?

I don't find a CentOS package.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2016-03-25T19:44:16+0000:59945858b91b58253f39c91d5ff11f685e228917:ded7f690201f02c37531b00bb6a6fc0091e9945e
 - Page requested: /hhvm/installation/building-from-source
 - Page requested at: Thu, 28 Apr 2016 18:39:37 +0000
 - Controller: GuidePageController

**Comment by fredemmott** [comment]
This is already clear on https://docs.hhvm.com/hhvm/installation/linux

This was specifically on the building from source page, so doesn't seem relevant.
