### ISSUE TITLE
Typo "Mint 16 (Preta)" should be "Mint 16 (Petra)"

### ISSUE THREAD

**Issue by carlwhittick** [hhvm/user-documentation#319]
Please complete the information below:

# Where is the problem?

Installation introduction in the list below "Also, there are currently LTS releases for".

# What is the problem?

I believe that "Mint 16 (Preta)" should be "Mint 16 (Petra)".

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2016-04-28T21:23:55+0000:ed6b193ca0ff86400ad7186ba96bcb7482e1b9b8:502d92c171e7ced3bbaf7a23f507ce871152ca12
 - Page requested: /hhvm/installation/introduction
 - Page requested at: Fri, 06 May 2016 07:03:45 +0000
 - Controller: GuidePageController

**Comment by JoelMarcey** [comment]
Fixed by https://github.com/hhvm/user-documentation/commit/781e38a5305a60e47a055a9b2d84ac352a9b0dd4
