### ISSUE TITLE
Pipe Operator Examples missing semicolons

### ISSUE THREAD

**Issue by RexJaeschke** [hhvm/user-documentation#321]
Please complete the information below:
# Where is the problem?

In both pipe-style examples
# What is the problem?

The return statement is missing a terminating semicolon.

---

Please don't change anything below this point.

---
- Build ID: 2016-04-28T21:23:55+0000:ed6b193ca0ff86400ad7186ba96bcb7482e1b9b8:502d92c171e7ced3bbaf7a23f507ce871152ca12
- Page requested: /hack/operators/pipe-operator
- Page requested at: Fri, 06 May 2016 21:20:52 +0000
- Controller: GuidePageController

**Comment by fredemmott** [comment]
This was fixed by 49341385b6fc71ba074742c1617180361dd54367
