### ISSUE TITLE
Introductory code in 'Test hhvm' section fails when typechecker is not set up (and it's not set up by default)

### ISSUE THREAD

**Issue by mkacik** [hhvm/user-documentation#324]
Please complete the information below:

# Where is the problem?

'Test hhvm' section

# What is the problem?

The example code uses <?hh, but default installation does not set up typechecker, so the code fails.

```index.php appears to be a Hack file, but you do not appear to be running the Hack typechecker. See the documentation at http://docs.hhvm.com/hack/typechecker/setup for information on getting it running. You can also set `-d hhvm.hack.lang.look_for_typechecker=0` to disable this check (not recommended).```

Probably should be <?php instead.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2016-04-28T21:23:55+0000:ed6b193ca0ff86400ad7186ba96bcb7482e1b9b8:502d92c171e7ced3bbaf7a23f507ce871152ca12
 - Page requested: /hhvm/getting-started/getting-started
 - Page requested at: Mon, 16 May 2016 02:41:23 +0000
 - Controller: GuidePageController

**Comment by fredemmott** [comment]
@JoelMarcey : this should probably just be `<?php` - otherwise, need to cover `.hhconfig`, and put the stuff in a function. We shouldn't be encouraging pseudomains in `<?hh`
