### ISSUE TITLE
Examples for extracting nullables

### ISSUE THREAD

**Issue by mgild** [hhvm/user-documentation#325]
Please complete the information below:
# Where is the problem?
- \- - eg "The section describing how widgets work" - - -
# What is the problem?

For the section on nullables, the concept is well explained but i cannot easily find a good example on variable extraction from a nullable.  I want to perform comparison on a nullable int and an int and cannot find the best way to do so.

---

Please don't change anything below this point.

---
- Build ID: 2016-04-28T21:23:55+0000:ed6b193ca0ff86400ad7186ba96bcb7482e1b9b8:502d92c171e7ced3bbaf7a23f507ce871152ca12
- Page requested: /hack/operators/null-safe
- Page requested at: Fri, 20 May 2016 16:26:58 +0000
- Controller: GuidePageController

**Comment by SiebelsTim** [comment]
I think this is what you're searching for:
https://docs.hhvm.com/hack/types/refining#nullable-to-non-nullable

**Comment by RexJaeschke** [comment]
Yes, type refinement is the place to read more about this. The revised version of the tutorial contains a major rewrite of this topic (now called types/type-refinement) that now uses `is` and `nonnull`.
