### ISSUE TITLE
Mentions of the Enum method `assert()` should not link to the documentation for the built-in PHP function named `assert`

### ISSUE THREAD

**Issue by lazytype** [hhvm/user-documentation#326]
Please complete the information below:
# Where is the problem?

Mentions of the `assert()` function
# What is the problem?

Mentions of `assert()` link to the PHP function php.net/manual/en/function.assert.php
but shouldn't since this is a method of Enum types

---

Please don't change anything below this point.

---
- Build ID: 2016-04-28T21:23:55+0000:ed6b193ca0ff86400ad7186ba96bcb7482e1b9b8:502d92c171e7ced3bbaf7a23f507ce871152ca12
- Page requested: /hack/enums/functions
- Page requested at: Fri, 20 May 2016 23:20:29 +0000
- Controller: GuidePageController

**Comment by AndrewDiMola** [comment]
No longer an issue. These functions don't auto-link anymore.
