### ISSUE TITLE
Variable names & local names correspondence 

### ISSUE THREAD

**Issue by Shereen92** [hhvm/user-documentation#329]
Please complete the information below:

# Where is the problem?

How hhvm deals with PHP variables.

# What is the problem?

There is no correspondence between real variable names in PHP and locals in byetcode. 
Is it not supported yet, or can I find it somewhere?

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2016-04-28T21:23:55+0000:ed6b193ca0ff86400ad7186ba96bcb7482e1b9b8:502d92c171e7ced3bbaf7a23f507ce871152ca12
 - Page requested: /hhvm/basic-usage/introduction
 - Page requested at: Wed, 25 May 2016 10:48:18 +0000
 - Controller: GuidePageController

**Comment by fredemmott** [comment]
You want one out of:

 - #hhvm on freenode
 - https://www.facebook.com/groups/hhvm.general/
 - github.com/facebook/hhvm/
