### ISSUE TITLE
kinetic scrolling is disabled in mobile safari

### ISSUE THREAD

**Issue by fredemmott** [hhvm/user-documentation#33]
Latest iOS.

**Comment by matthewjohnston4** [comment]
Is this just in the nav, or everywhere?

**Comment by fredemmott** [comment]
everywhere

**Comment by fredemmott** [comment]
fwiw, I can't reproduce in the simulator, only on a real device.

**Comment by matthewjohnston4** [comment]
I think this is now solved, @fredemmott can you confirm?

**Comment by fredemmott** [comment]
Yep, fixed. Got a commit ID?

**Comment by matthewjohnston4** [comment]
Yep a4c86d7303fe7553e6fa8ed556f4ce8547da662e fixed it
