### ISSUE TITLE
Uncaught exception 'HH\InvariantException' with message 'found two things that look like typehints for the same parameter 

### ISSUE THREAD

**Issue by web3d** [hhvm/user-documentation#330]
2016-05-28 01:57:24] Build sources for /root/user-documentation/build/systemlib-yaml.......................................................
Fatal error: Uncaught exception 'HH\InvariantException' with message 'found two things that look like typehints for the same parameter at line 1178' in /root/user-documentation/vendor/fredemmott/definition-finder/src/consumers/FunctionAbstractConsumer.php:169
Stack trace:
#0 /root/user-documentation/vendor/fredemmott/definition-finder/src/consumers/FunctionAbstractConsumer.php(169): HH\invariant_violation()
#1 /root/user-documentation/vendor/fredemmott/definition-finder/src/consumers/FunctionAbstractConsumer.php(55): FredEmmott\DefinitionFinder\FunctionAbstractConsumer->consumeParameterList()
#2 /root/user-documentation/vendor/fredemmott/definition-finder/src/consumers/ScopeConsumer.php(202): FredEmmott\DefinitionFinder\FunctionAbstractConsumer->getBuilder()
#3 /root/user-documentation/vendor/fredemmott/definition-finder/src/consumers/ScopeConsumer.php(156): FredEmmott\DefinitionFinder\ScopeConsumer->consumeDefinition()
#4 /root/user-documentation/vendor/fredemmott/definition-finder/src/consumers/ClassConsumer.php(84): FredEmmott\DefinitionFinder\ScopeConsumer->getBuilder()
#5 /root/user-documentation/vendor/fredemmott/definition-finder/src/consumers/ScopeConsumer.php(194): FredEmmott\DefinitionFinder\ClassConsumer->getBuilder()
#6 /root/user-documentation/vendor/fredemmott/definition-finder/src/consumers/ScopeConsumer.php(156): FredEmmott\DefinitionFinder\ScopeConsumer->consumeDefinition()
#7 /root/user-documentation/vendor/fredemmott/definition-finder/src/FileParser.php(12): FredEmmott\DefinitionFinder\ScopeConsumer->getBuilder()
#8 /root/user-documentation/vendor/fredemmott/definition-finder/src/FileParser.php(38): FredEmmott\DefinitionFinder\FileParser->__construct()
#9 /root/user-documentation/src/build/RawYAMLBuildStep.php(41): FredEmmott\DefinitionFinder\FileParser::FromData()
#10 /root/user-documentation/src/build/RawYAMLBuildStep.php(15): HHVM\UserDocumentation\RawYAMLBuildStep->buildSources()
#11 /root/user-documentation/bin/build.php(62): HHVM\UserDocumentation\RawYAMLBuildStep->buildAll()
#12 /root/user-documentation/bin/build.php(69): HHVM\UserDocumentation\build_site()
#13 {main}

Next exception 'FredEmmott\DefinitionFinder\ParseException' with message '/root/hhvm/hphp/system/php/phar/Phar.php:1178: found two things that look like typehints for the same parameter at line 1178' in /root/user-documentation/vendor/fredemmott/definition-finder/src/FileParser.php:19
Stack trace:
#0 /root/user-documentation/vendor/fredemmott/definition-finder/src/FileParser.php(38): FredEmmott\DefinitionFinder\FileParser->__construct()
#1 /root/user-documentation/src/build/RawYAMLBuildStep.php(41): FredEmmott\DefinitionFinder\FileParser::FromData()
#2 /root/user-documentation/src/build/RawYAMLBuildStep.php(15): HHVM\UserDocumentation\RawYAMLBuildStep->buildSources()
#3 /root/user-documentation/bin/build.php(62): HHVM\UserDocumentation\RawYAMLBuildStep->buildAll()
#4 /root/user-documentation/bin/build.php(69): HHVM\UserDocumentation\build_site()
#5 {main}

**Comment by fredemmott** [comment]
https://github.com/fredemmott/definition-finder/issues/18

**Comment by fredemmott** [comment]
HHVM bug, that file uses Hack generics, but has `<?php`, not `<?hh`. Fix up internally (FB: D3406816)
