### ISSUE TITLE
Spelling issue

### ISSUE THREAD

**Issue by Orvid** [hhvm/user-documentation#332]
Please complete the information below:

# Where is the problem?

Main summary block.

# What is the problem?

Requires is misspelled.
`This function requrires a deprecated, MySQL resource`

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2016-04-28T21:23:55+0000:ed6b193ca0ff86400ad7186ba96bcb7482e1b9b8:502d92c171e7ced3bbaf7a23f507ce871152ca12
 - Page requested: /hack/reference/class/AsyncMysqlClient/adoptConnection/
 - Page requested at: Mon, 30 May 2016 22:16:21 +0000
 - Controller: APIMethodPageController

**Comment by fredemmott** [comment]
To fix this, edit hphp/runtime/ext/async_mysql/ext_async_mysql.php
