### ISSUE TITLE
switch over a string!

### ISSUE THREAD

**Issue by Shereen92** [hhvm/user-documentation#333]
I've been running some php tests with switches and noticed that hhvm does not behave correctly when given the following example, which supposedly deals with strings:

<?php
$val='2';
switch($val){
case '2.' : echo '2.0!??';
	 break;
case '2' : echo '2.'; 
	break;
}
?>

Is this normal or is there something I'm missing here?

Thanks

**Comment by Orvid** [comment]
This is the behavior of PHP itself: https://3v4l.org/eGV0m

**Comment by SiebelsTim** [comment]
Note that reordering the case labels will affect the output

https://3v4l.org/VhR2O

This is documented behaviour: 

> Note:
> Note that switch/case does [loose](http://php.net/manual/en/types.comparisons.php#types.comparisions-loose) comparison. 

http://php.net/manual/en/control-structures.switch.php

**Comment by Shereen92** [comment]
Thank you.

I guess PHP executes whatever it finds matching first.
