### ISSUE TITLE
Double escaping in AsyncMysqlConnection::escapeString example

### ISSUE THREAD

**Issue by eryi** [hhvm/user-documentation#336]
Please complete the information below:

# Where is the problem?

The example provided.

# What is the problem?

The example uses queryf to demonstrate usage of escapeString. However, queryf already escapes all strings passed to it. The string is therefore escaped twice in the example.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2016-06-09T22:37:18+0000:76d80b065bdb2617e5c907f306401f1e717aeb9d:3925e0c2ccab87656f3d687e71632218f7d25d1d
 - Page requested: /hack/reference/class/AsyncMysqlConnection/escapeString/
 - Page requested at: Tue, 14 Jun 2016 09:56:53 +0000
 - Controller: APIMethodPageController

**Comment by fredemmott** [comment]
Nice catch, thanks :)

**Comment by fredemmott** [comment]
Text under the examples heading is also wrong...

**Comment by fredemmott** [comment]
Also got a change to HHVM up to make it so that the query/multiquery/escape pages say to use queryf instead.
