### ISSUE TITLE
Error while trying to install hhvm on mac osx version 10.11

### ISSUE THREAD

**Issue by ghost** [hhvm/user-documentation#338]
Please complete the information below:
I tried to install hhvm  on osx by using home brew  but finally I got an error : 
first I typed:
**brew tap hhvm/hhvm**
and then typed:
**brew install hhvm**

but I got below error:
**Error: Could not create /usr/local/Cellar
Check you have permission to write to /usr/local**

what should I do for resolving that issue? 
thanks

**Comment by Orvid** [comment]
This sounds like a general issue with homebrew rather than HHVM itself.

**Comment by toru-aine** [comment]
+1 for Homebrew issue, I ran `sudo chown -R $USER /usr/local` to fix brew permissions and it worked
