### ISSUE TITLE
How to create mysql with hack language 

### ISSUE THREAD

**Issue by hamidebadi** [hhvm/user-documentation#339]
Please complete the information below:

# What is the problem?

- - - eg "I want to install mysql with Hack but where should I put mysql for working with hack?
is there any tutorial to help me?
" - - -

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2016-06-09T22:37:18+0000:76d80b065bdb2617e5c907f306401f1e717aeb9d:3925e0c2ccab87656f3d687e71632218f7d25d1d
 - Page requested: /hack/
 - Page requested at: Fri, 01 Jul 2016 12:53:00 +0000
 - Controller: GuidesListController

**Comment by SiebelsTim** [comment]
MySQLi is interoperable with hack.
Although you may want to look at http://docs.hacklang.org/hack/reference/class/AsyncMysqlClient/
