### ISSUE TITLE
HH\Traversable page has doc for file, not interface. Also, wtf?

### ISSUE THREAD

**Issue by fredemmott** [hhvm/user-documentation#34]
http://staging.docs.hhvm.com/hack/reference/interface/HH.Traversable/

WTF: given that \Traversable is standard PHP, I hope that there isn't really such a thing as HH\Traversable

**Comment by JoelMarcey** [comment]
I have a diff out that documents Traverable<T> in our hhi. I just figured that was HH/Traversable (with the type parameter).
