### ISSUE TITLE
Weirdly-formatted code in "Types: Type System > Callables"

### ISSUE THREAD

**Issue by ucarion** [hhvm/user-documentation#340]
# Where is the problem?

In https://docs.hhvm.com/hack/types/type-system#callables, namely the example code in that section.

# What is the problem?

The code is formatted very weirdly. Here's how it looks today:

```hack
function use_callable(
  Vector<int> $vec,
  (function(int) : ?int) $callback
  ): Vector<?int> {
  $ret = Vector {};
  foreach ($vec as $item) {
    $ret[] = $callback($item);
  }
  return $ret;
}
```

Is there any reason it can't be written as:

```hack
function use_callable(Vector<int> $vec, (function(int) : ?int) $callback): Vector<?int> {
  $ret = Vector {};
  foreach ($vec as $item) {
    $ret[] = $callback($item);
  }
  return $ret;
}
```

It took my brain many passes before correctly parsing that code sample as it is online today, and that's not how real-life Hack is formatted. If the goal is to emphasize how to declare a callable argument, you could put a comment asking the reader to take note of how `$callback`'s type is declared.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2016-06-09T22:37:18+0000:76d80b065bdb2617e5c907f306401f1e717aeb9d:3925e0c2ccab87656f3d687e71632218f7d25d1d
 - Page requested: /hack/types/type-system
 - Page requested at: Wed, 06 Jul 2016 22:43:03 +0000
 - Controller: GuidePageController

**Comment by simonwelsh** [comment]
It's almost correctly formatted. Just need a trailing comma and to have the closing parenthesis be in the same column as `function`:

```hack
function use_callable(
  Vector<int> $vec,
  (function(int) : ?int) $callback,
): Vector<?int> {
  $ret = Vector {};
  foreach ($vec as $item) {
    $ret[] = $callback($item);
  }
  return $ret;
}
```

**Comment by SiebelsTim** [comment]
I agree with Simon. Having one parameter per line if that line would exceed 80 cols is the preferred style in the hhvm codebase.
