### ISSUE TITLE
Using a var inside single quotes

### ISSUE THREAD

**Issue by NinoSkopac** [hhvm/user-documentation#346]
Please complete the information below:

# Where is the problem?

First code snippet, line 4: `return 'Hello $user';`

# What is the problem?

A variable is used within single quotes, where it should've been used in double quotes.

`'Hello $user'` should be `"Hello $user"`

ps.
I've never used Hack/HHVM in my life, so forgive me if I'm an idiot.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2016-06-09T22:37:18+0000:76d80b065bdb2617e5c907f306401f1e717aeb9d:3925e0c2ccab87656f3d687e71632218f7d25d1d
 - Page requested: /hack/operators/lambda
 - Page requested at: Sat, 16 Jul 2016 01:19:17 +0000
 - Controller: GuidePageController

**Comment by fredemmott** [comment]
This is correct; additionally, interpolation is discouraged and we shouldn't be using it at all. This should be `'Hello '.$user` (the typechecker doesn't understand interpolation)
