### ISSUE TITLE
E: Unable to locate package hhvm

### ISSUE THREAD

**Issue by djmohsen** [hhvm/user-documentation#347]
Please complete the information below:

# Where is the problem?

E: Unable to locate package hhvm

# What is the problem?

and can not install
root@server:~# deb http://dl.hhvm.com/debian jessie main
-bash: deb: command not found
root@server:~# apt-get install deb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package deb
and
root@server:~# apt-get install hhvm
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package hhvm
root@server:~# 
and
nano /etc/apt/sources.list.d/hhvm.list
deb http://dl.hhvm.com/debian jessie main

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2016-06-09T22:37:18+0000:76d80b065bdb2617e5c907f306401f1e717aeb9d:3925e0c2ccab87656f3d687e71632218f7d25d1d
 - Page requested: /hhvm/installation/linux
 - Page requested at: Sun, 17 Jul 2016 10:17:58 +0000
 - Controller: GuidePageController

**Comment by fredemmott** [comment]
The instructions do not say to run a command called deb. Run the commands on https://docs.hhvm.com/hhvm/installation/linux#debian-8-jessie exactly as given.

**Comment by boyan-sharic** [comment]
I did exactly that adn this is the output :(
`root@vps3:~# sudo apt-get update
Hit http://ftp.de.debian.org wheezy Release.gpg
Hit http://ftp.de.debian.org wheezy-updates Release.gpg
Hit http://dl.hhvm.com jessie Release.gpg
Hit http://ftp.de.debian.org wheezy Release
Hit http://security.debian.org wheezy/updates Release.gpg
Hit http://ftp.de.debian.org wheezy-updates Release
Hit http://security.debian.org wheezy/updates Release
Hit http://dl.hhvm.com jessie Release
Hit http://ftp.de.debian.org wheezy/main Sources
Hit http://http.debian.net wheezy-backports Release.gpg
Hit http://security.debian.org wheezy/updates/main Sources
Hit http://ftp.de.debian.org wheezy/contrib Sources
Hit http://security.debian.org wheezy/updates/contrib Sources
Hit http://dl.hhvm.com jessie/main i386 Packages
Hit http://ftp.de.debian.org wheezy/non-free Sources
Hit http://security.debian.org wheezy/updates/non-free Sources
Hit http://security.debian.org wheezy/updates/main i386 Packages
Hit http://ftp.de.debian.org wheezy/main i386 Packages
Hit http://http.debian.net wheezy-backports Release
Hit http://security.debian.org wheezy/updates/contrib i386 Packages
Hit http://ftp.de.debian.org wheezy/contrib i386 Packages
Hit http://security.debian.org wheezy/updates/non-free i386 Packages
Hit http://ftp.de.debian.org wheezy/non-free i386 Packages
Hit http://security.debian.org wheezy/updates/contrib Translation-en
Hit http://security.debian.org wheezy/updates/main Translation-en
Hit http://ftp.de.debian.org wheezy/contrib Translation-en
Hit http://security.debian.org wheezy/updates/non-free Translation-en
Hit http://ftp.de.debian.org wheezy/main Translation-en
Hit http://http.debian.net wheezy-backports/main i386 Packages/DiffIndex
Hit http://ftp.de.debian.org wheezy/non-free Translation-en
Hit http://ftp.de.debian.org wheezy-updates/main Sources
Hit http://http.debian.net wheezy-backports/main Translation-en/DiffIndex
Hit http://ftp.de.debian.org wheezy-updates/contrib Sources
Hit http://ftp.de.debian.org wheezy-updates/non-free Sources
Hit http://ftp.de.debian.org wheezy-updates/main i386 Packages/DiffIndex
Hit http://ftp.de.debian.org wheezy-updates/contrib i386 Packages
Hit http://ftp.de.debian.org wheezy-updates/non-free i386 Packages/DiffIndex
Hit http://ftp.de.debian.org wheezy-updates/contrib Translation-en
Hit http://ftp.de.debian.org wheezy-updates/main Translation-en/DiffIndex
Hit http://ftp.de.debian.org wheezy-updates/non-free Translation-en/DiffIndex
Ign http://dl.hhvm.com jessie/main Translation-en_US
Ign http://dl.hhvm.com jessie/main Translation-en
Reading package lists... Done
root@vps3:~# apt-get install hhvm
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package hhvm
root@vps3:~#
`

**Comment by fredemmott** [comment]
@boyan-sharic: HHVM only supports 64-bit operating systems, and that VM appears to be i386.
