### ISSUE TITLE
[docs] Just add instruction for Ubuntu Xenial

### ISSUE THREAD

**Issue by firodj** [hhvm/user-documentation#348]
Please complete the information below:

https://docs.hhvm.com/hhvm/installation/linux

Just add instruction for Ubuntu 16.04 Xenial, which is exactly same with Ubuntu 15.10 Wily Werewolf.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2016-06-09T22:37:18+0000:76d80b065bdb2617e5c907f306401f1e717aeb9d:3925e0c2ccab87656f3d687e71632218f7d25d1d
 - Page requested: /hhvm/installation/linux
 - Page requested at: Mon, 18 Jul 2016 09:33:18 +0000
 - Controller: GuidePageController

**Comment by SiebelsTim** [comment]
d0980d5
