### ISSUE TITLE
Attributes/Syntax should indicate that attributes work on hack enums

### ISSUE THREAD

**Issue by admdikramr** [hhvm/user-documentation#352]
Please complete the information below:
# Where is the problem?

Attributes/Syntax
# What is the problem?

"Attributes can be placed on any reflectable piece of code. These include:" --> Native enums are missing from the list of things these include! But they work just the same.

---

Please don't change anything below this point.

---
- Build ID: 2016-06-09T22:37:18+0000:76d80b065bdb2617e5c907f306401f1e717aeb9d:3925e0c2ccab87656f3d687e71632218f7d25d1d
- Page requested: /hack/attributes/syntax
- Page requested at: Thu, 28 Jul 2016 16:32:11 +0000
- Controller: GuidePageController

**Comment by RexJaeschke** [comment]
The revised tutorial no longer attempts to enumerate the things to which an attribute can be applied. Instead, it states, "Programmers can invent a new kind of declarative information, called an *attribute*. Attributes can be attached to various program entities, and information about those attributes can be retrieved at run-time via reflection (see library class `Reflection`, et al)."
