### ISSUE TITLE
Pre-built packages for Ubuntu 16.04 (Xenial Xerus) is not listed

### ISSUE THREAD

**Issue by gromero** [hhvm/user-documentation#353]
Please complete the information below:

# Where is the problem?

The section on prebuilt-packages:
https://docs.hhvm.com/hhvm/installation/introduction#prebuilt-packages

- - - eg "The section describing how widgets work" - - -

# What is the problem?

Pre-built packages for Ubuntu 16.04 (Xenial Xerus) is not listed in the pointed out doc, although it's already available here: http://dl.hhvm.com/ubuntu/pool/main/h/hhvm/ 

- - - eg "It doesn't explain that widgets are singletons" - - -

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2016-06-09T22:37:18+0000:76d80b065bdb2617e5c907f306401f1e717aeb9d:3925e0c2ccab87656f3d687e71632218f7d25d1d
 - Page requested: /hhvm/installation/introduction
 - Page requested at: Wed, 03 Aug 2016 00:14:36 +0000
 - Controller: GuidePageController

**Comment by SiebelsTim** [comment]
d0980d5
