### ISSUE TITLE
Rename Intro to Introduction

### ISSUE THREAD

**Issue by JoelMarcey** [hhvm/user-documentation#36]
Use the full word `Introduction` in our page titles.

Also, look at renaming one other page. We have a page called `Vs Arrays` in the Collections guides. It compares Collections with arrays. Thinking about coming up with a better name.

**Comment by matthewjohnston4** [comment]
Please beware of this when changing - https://github.com/hhvm/user-documentation/blob/master/public/js/SideNav.js#L67
