### ISSUE TITLE
Can the docs be versionized

### ISSUE THREAD

**Issue by web3d** [hhvm/user-documentation#362]
docs site in master branch does not work when hhvm be updated and recompiled in many times.

**Comment by fredemmott** [comment]
This is something we're considering depending on future uptake, but currently would take too much time for the benefit it would get, and increase the maintenance cost beyond what the team can spare.

If you just want to be able to run a copy of the site, see https://github.com/hhvm/user-documentation#running-a-local-copy for a docker-based approach, which will get you exactly what docs.hhvm.com is running (docs.hhvm.com is that docker image running on AWS). If you want an older version, replace 'hhvm/user-documentation' with 'hhvm/user-documentation:SOME_TAG' where SOME_TAG is listed here: https://hub.docker.com/r/hhvm/user-documentation/tags/
