### ISSUE TITLE
type_structure page should document return type as TypeStructure shape

### ISSUE THREAD

**Issue by Daniel15** [hhvm/user-documentation#369]
The return type for `type_structure` is just documented as `array`. It should instead document the `TypeStructure` shape (https://github.com/facebook/hhvm/blob/master/hphp/hack/hhi/typestructure.hhi#L39)

---

Please don't change anything below this point.

---
- Build ID: 2016-08-15T18:49:04+0000:e756f9162e96b867a06b2805e03056a63fc17931:2b940b7ef772640b5980b78c645f89cbd216d81f
- Page requested: /hack/reference/function/HH.type_structure/
- Page requested at: Tue, 20 Sep 2016 04:30:11 +0000
- Controller: APIGenericPageController

**Comment by fredemmott** [comment]
This API is planned to be changed, we might actually want to remove it from the docs

**Comment by fredemmott** [comment]
(though yes, it is a bug in the code generation that we're preferring array over some shape definition)

**Comment by fredemmott** [comment]
> This API is planned to be changed, we might actually want to remove it from the docs

Yep (confirmed with @dlreeves)
