### ISSUE TITLE
This mirror is no longer available

### ISSUE THREAD

**Issue by cicku** [hhvm/user-documentation#372]
https://docs.hhvm.com/hhvm/installation/linux#mirrors

`http://mirrors.noc.im/hhvm/ (CN)` doesn't exist anymore.
--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2016-08-15T18:49:04+0000:e756f9162e96b867a06b2805e03056a63fc17931:2b940b7ef772640b5980b78c645f89cbd216d81f
 - Page requested: /hhvm/installation/linux
 - Page requested at: Thu, 29 Sep 2016 04:37:27 +0000
 - Controller: GuidePageController

**Comment by bauerj** [comment]
That mirror was added to the original wiki page by @ym.

**Comment by ym** [comment]
This mirror is discontinued, I'll create a pull request to remove this link.
Sorry :-(

**Comment by bauerj** [comment]
No problem, I know that it takes a lot of disk space 😄 

Just wanted to make sure that it's not a temporary issue on your side.

**Comment by ym** [comment]
PR was created. :-)

https://github.com/hhvm/user-documentation/pull/388

**Comment by Orvid** [comment]
PR merged.
