### ISSUE TITLE
Unable to install (Package not found)

### ISSUE THREAD

**Issue by caymanroe** [hhvm/user-documentation#373]
Please complete the information below:

# Where is the problem?

Installing hhvm

# What is the problem?

After following the instructions [here](https://docs.hhvm.com/hhvm/installation/linux#ubuntu-14.04-trusty), I receive the error 'Unable to locate package hhvm' when running 'sudo apt-get install hhvm'.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2016-08-15T18:49:04+0000:e756f9162e96b867a06b2805e03056a63fc17931:2b940b7ef772640b5980b78c645f89cbd216d81f
 - Page requested: /hhvm/installation/linux
 - Page requested at: Sat, 01 Oct 2016 22:27:23 +0000
 - Controller: GuidePageController

**Comment by Orvid** [comment]
This should be filed against the main HHVM repo rather than the docs.

Also, are you sure that you've run both:
```
sudo add-apt-repository "deb http://dl.hhvm.com/ubuntu $(lsb_release -sc) main"
sudo apt-get update
```
Before trying to install HHVM?

**Comment by caymanroe** [comment]
Apologies, I just followed the link at the bottom of the documentation. I should have checked.

Yes I ran both of those commands. Still showing the package can't be found. Absolutely no idea what's causing it.

**Comment by fredemmott** [comment]
What's the output of:

 - `lsb_release -sc`
 - `uname -a`

**Comment by caymanroe** [comment]
> lsb_release -sc

`xenial`

> uname -a

`Linux mars 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:06:14 UTC 2016 i686 i686 i686 GNU/Linux`

**Comment by fredemmott** [comment]
`i686`

HHVM only supports 64-bit operating systems.

**Comment by caymanroe** [comment]
That would make sense. Never occurred to me. Thanks for getting back to me.
