### ISSUE TITLE
Installation: Release Schedule is out of date

### ISSUE THREAD

**Issue by photodude** [hhvm/user-documentation#380]
Please complete the information below:

# Where is the problem?

Installation: Release Schedule

# What is the problem?

The Installation: Release Schedule does not have information for 3.15, and future version planning 3.16 and beyond has not been created.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2016-08-15T18:49:04+0000:e756f9162e96b867a06b2805e03056a63fc17931:2b940b7ef772640b5980b78c645f89cbd216d81f
 - Page requested: /hhvm/installation/release-schedule
 - Page requested at: Wed, 05 Oct 2016 12:18:21 +0000
 - Controller: GuidePageController

**Comment by paulbiss** [comment]
I've updated it but haven't had a chance to push the changes to the docs site. 362c1ba3c30a4155aef06271defa3c7f65bf4695 75064dc86aaef324bc5af5fc40773fbcd4d55133

**Comment by photodude** [comment]
Thanks @paulbiss
