### ISSUE TITLE
nuclide-hack package link invalid

### ISSUE THREAD

**Issue by juehuizh** [hhvm/user-documentation#384]
Please complete the information below:
# Where is the problem?

On page https://docs.hhvm.com/hack/getting-started/getting-started#overview
nuclide-hack package link
# What is the problem?

The link (https://github.com/facebook/nuclide/blob/master/pkg/nuclide/hack/README.md) has 404 error
![screen shot 2016-10-11 at 4 35 51 pm](https://cloud.githubusercontent.com/assets/2183049/19292417/cc7c9538-8fd0-11e6-9f58-b727e1a1c8e4.png)

---

Please don't change anything below this point.

---
- Build ID: 2016-10-05T21:47:03+0000:7e6e72a26df5c3d1ecc8feb244d6ef6d8d5dc924:3bcf6ed75043817b82363c6f7aa00050ccc8ff53
- Page requested: /hack/getting-started/getting-started
- Page requested at: Tue, 11 Oct 2016 04:19:57 +0000
- Controller: GuidePageController

**Comment by fredemmott** [comment]
Kind-of should be https://github.com/facebook/nuclide/blob/master/pkg/nuclide-hack/README.md , but given that it's empty and Nuclide now ships as a single massive package (sub-packages like `nuclide-hack` are no longer separately installable), should probably just be removed.

**Comment by juehuizh** [comment]
Should we update the link url?

**Comment by Wilfred** [comment]
This docs page no longer has a link to nuclide-hack.
