### ISSUE TITLE
fcontext.hpp is located in a different folder on MacOS 10.10.5

### ISSUE THREAD

**Issue by janoszen** [hhvm/user-documentation#386]
Please complete the information below:

# Where is the problem?

HHVM doesn't build with libboost 1.62 installed from Homebrew on MacOS 10.10.5

# What is the problem?

HHVM does not build with libboost 1.62. Instead, it must be built with libboost 1.55. The brew package for the older version is called `homebrew/versions/boost155` and the `brew --prefix boost` lines must be replaced with `brew --prefix boost155`.

(Newer versions of boost have fcontext.hpp in a different location, and seems to be incompatible with HHVM, even after patching the path for fcontext.hpp)

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2016-10-05T21:47:03+0000:7e6e72a26df5c3d1ecc8feb244d6ef6d8d5dc924:3bcf6ed75043817b82363c6f7aa00050ccc8ff53
 - Page requested: /hhvm/installation/building-from-source
 - Page requested at: Sat, 15 Oct 2016 06:11:45 +0000
 - Controller: GuidePageController

**Comment by fredemmott** [comment]
Not a documentation issue - you want https://github.com/hhvm/homebrew-hhvm

**Comment by janoszen** [comment]
No I don't because the homebrew version doesn't work either. And besides, if there is a documentation, it should actually tell the truth, or it should be deleted.

**Comment by fredemmott** [comment]
Sorry, thought you were on the installing from homebrew page, not building from source.

> the homebrew version doesn't work either

Please file an issue for that at https://github.com/hhvm/homebrew-hhvm/issues

**Comment by janoszen** [comment]
I will, as soon as I figure out what's wrong with it. :)

**Comment by simonwelsh** [comment]
Folly currently doesn't build with Boost 1.61 or later (facebook/folly#413), which is why you need to use an older version.

**Comment by Orvid** [comment]
We have a diff up internally to fix building with >=1.61. It should hopefully land within the next couple of days.

**Comment by Orvid** [comment]
Correction: Within the next hour :D (it's landed, just waiting for it to sync to Github, then I'll close this issue, and the Folly issues as well)

**Comment by Orvid** [comment]
I appear to have forgotten that the syncs are faster with Folly than they are with HHVM. The sync is now done. https://github.com/facebook/folly/commit/0b894c40e54e645bf1da19bcb9a28147ee2ce2b4 fixes Folly to build with Boost >= 1.61. We still need to update HHVM-third-party before HHVM will be able to build against it though.
