### ISSUE TITLE
Repo authoritative + Laravel + Virtual Host

### ISSUE THREAD

**Issue by ahmadazimi** [hhvm/user-documentation#391]
Documention for `hhvm.server.source_root` says:
> For server mode, this will hold the path to the root of the directory of the code being served up. **This setting is useless** in repo-authoritative mode.

So, how can I setup my Laravel app which only my **app** folder is bytecoded by repo authoritative? I mean how should I configue hhvm ini to handle both not bytecodded codes and bytecodded hhbc file?

And also can I use **repo authoritative** mode with **virtual hosts**?

--------------------------------

 - Build ID: 2016-10-05T21:47:03+0000:7e6e72a26df5c3d1ecc8feb244d6ef6d8d5dc924:3bcf6ed75043817b82363c6f7aa00050ccc8ff53
 - Page requested: /hhvm/configuration/INI-settings
 - Page requested at: Wed, 16 Nov 2016 04:03:13 +0000
 - Controller: GuidePageController

**Comment by mofarrell** [comment]
There is no concept of a "mixed" repo mode, so you can't only put certain files in the repo (see discussion here https://github.com/facebook/hhvm/issues/6777).  Repo mode is meant to be run on your production servers, so there is no reason files should be changing.  The main benefit of repo mode is it knows that the source won't change, and can do optimizations base on that.

I also see no reason why virtual hosts would not work with repo mode.

**Comment by ahmadazimi** [comment]
@mofarrell Thank you for your reply.
As you may know, Laravel include many other packages (libraries) in its composer vendor folder.
I tried to compile Laravel root folder, but many errors occurred when validating vendor folder!
I'm trying to find a solution to just compile my app folder.

**Comment by AndrewDiMola** [comment]
Closing because `hhvm ini` questions were addressed and because additional Laravel discussion seems to have concluded.
