### ISSUE TITLE
"the only way"...

### ISSUE THREAD

**Issue by ekandrot** [hhvm/user-documentation#392]
Please complete the information below:

# Where is the problem?

https://docs.hhvm.com/hack/async/guidelines#dont-forget-to-await-an-awaitable

# What is the problem?

the paragraph says "the only way" for speak to complete is with an await.  That is not correct, one can also make the calling function non-async and invoking speak with a join.  So there are two ways to fix the code to get the results one wants, but one of them is listed as the only way.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2016-10-05T21:47:03+0000:7e6e72a26df5c3d1ecc8feb244d6ef6d8d5dc924:3bcf6ed75043817b82363c6f7aa00050ccc8ff53
 - Page requested: /hack/async/guidelines
 - Page requested at: Thu, 17 Nov 2016 23:59:17 +0000
 - Controller: GuidePageController

**Comment by fredemmott** [comment]
Specifically `HH\Asio\join()`; the `$x->join()` methods on awaitable and waithandles have been removed from HHVM master

**Comment by ekandrot** [comment]
As an aside:  So https://docs.hhvm.com/hack/reference/function/HH.Asio.join/ as well as all of the references on the other pages of the HHVM programming guide(s) are slated to be updated to remove join?  Was the await guildlines page updated prematurely or was it just missing that case previously?  

If join is gone, then this paragraph is correct.

**Comment by fredemmott** [comment]
```Hack
<?hh

$func = async () ==> null;
$awaitable = $func();

// This will continue to work:
\HH\Asio\join($awaitable);
// This is gone:
$awaitable->join();
```

As top level code is not async, somewhere there needs to be an `\HH\Asio\join()` - ideally, there should be one per request.

**Comment by fredemmott** [comment]
Closing: `->join()` no longer exists, and `<<__Entrypoint>>` removes the need for `\HH\Asio\join()`
