### ISSUE TITLE
No installation on OSX 10.12 ?!

### ISSUE THREAD

**Issue by harrysandhu** [hhvm/user-documentation#397]
# No Installation on OSX 10.12?!
IT SAYS," We do not provide support for this pre-release version.".

 - Build ID: 2016-10-05T21:47:03+0000:7e6e72a26df5c3d1ecc8feb244d6ef6d8d5dc924:3bcf6ed75043817b82363c6f7aa00050ccc8ff53
 - Page requested: /hhvm/installation/mac
 - Page requested at: Tue, 13 Dec 2016 20:11:16 +0000
 - Controller: GuidePageController

**Comment by mofarrell** [comment]
I don't see where it says  "We do not provide support for this pre-release version."

**Comment by fredemmott** [comment]
We definitely support 10.12 and 10.13 now, and there's insufficient information to investigate this.
