### ISSUE TITLE
fail in linux install 

### ISSUE THREAD

**Issue by rotasul** [hhvm/user-documentation#401]
# Where is the problem?
the linux xenial install fail!

# What is the problem?
I follow step by step an nothing!
no warning, just not install
the trial was in a good machine with lot of RAM and i7 proc.

-------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2017-01-03T20:16:48+0000:84ad9cd989e2467bb262c8d3cbe326bbdde54163:14202af5a6cd7ba7c897ddf934a4967aca952405
 - Page requested: /hhvm/installation/linux
 - Page requested at: Wed, 04 Jan 2017 12:14:27 +0000
 - Controller: GuidePageController

**Comment by mofarrell** [comment]
I can't reproduce on Ubuntu 16.04.1 LTS.  You will need to provide more information.

**Comment by mofarrell** [comment]
Does running `lsb_release -sc`  return `xenial`?

http://dl.hhvm.com/ubuntu/dists/xenial/main/binary-amd64/Packages
If you look in the dependencies, it is looking for libgcrypt20, libgd3, libgnutls30...
Everyone of the packages that can't be found during your installation is not in the dependency list.  For some reason it seems you have pulled an older repository.  It seems to grab an older version like this: http://dl.hhvm.com/ubuntu/dists/precise/main/binary-amd64/Packages

If you are actually on a xenial host, try the same build instructions, but replace the `$(lsb_release -sc)` with `xenial`.  It seems like your machine doesn't think its running xenial.

**Comment by rotasul** [comment]
sorry!! y are right!! not xenial >> yak
