### ISSUE TITLE
document vec/dict/keyset

### ISSUE THREAD

**Issue by Cypher1** [hhvm/user-documentation#402]
Please complete the information below:

# Where is the problem?
https://docs.hhvm.com/hack/reference/class/vec/

Vec type has almost no documentation

# What is the problem?
The documentation gives no explanation of what a Vec is in Hack, why it should be used over array and when it shouldn't be used.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2017-01-03T20:16:48+0000:84ad9cd989e2467bb262c8d3cbe326bbdde54163:14202af5a6cd7ba7c897ddf934a4967aca952405
 - Page requested: /hack/reference/class/vec/
 - Page requested at: Wed, 04 Jan 2017 18:09:54 +0000
 - Controller: APIClassPageController

**Comment by Cypher1** [comment]
At bare minimum we should link to 
https://docs.hhvm.com/hack/reference/class/HH.Vector/

**Comment by paulbiss** [comment]
Hmm, vec isn't a class, it's a new type. We need to document all of the new hack arrays.

http://hhvm.com/blog/10649/improving-arrays-in-hack

**Comment by Cypher1** [comment]
Fixed my first comment, ta

**Comment by fredemmott** [comment]
```
hphp/hack/hhi/experimental/interfaces.hhi [blame][history] [copy path] [copy filename]
abstract final class vec<+T> implements Indexish<int, T> {}
```

This is where the docs site is finding it, but as @paulbiss said, it's not accurate :(

**Comment by Cypher1** [comment]
Thanks @fredemmott!
Good to see this get done
