### ISSUE TITLE
AsyncMysqlConnectionPool lifecycle

### ISSUE THREAD

**Issue by leric** [hhvm/user-documentation#407]
IMHO a connection pool is meant to reuse and limit connections to db, but tell from ->getPoolStats(), it doesn't seem to be a shared pool across requests, every request is using a new pool, mysql is exhausted. is there some trick on handling this pool object?

**Comment by mofarrell** [comment]
I believe that AsyncMysqlConnectionPool does exactly that on a request by request basis.  This enables you to reuse and limit the connections each request creates with the database.

The idea of a shared pool across requests would be nice, but it breaks php's model of each request being entirely independent.  If you see this as a beneficial feature.  Open an issue on the [main repo](https://github.com/facebook/hhvm)
