### ISSUE TITLE
Add doc page for HHVM Docker image

### ISSUE THREAD

**Issue by vicvolk** [hhvm/user-documentation#408]
Hello, guys! I'm using Docker heavily in my projects and I'm interested to know, if there is an official HHVM Docker image. I've seen many HHVM repositories at Docker Hub, but none of them is marked as official.

**Comment by SiebelsTim** [comment]
I think https://github.com/hhvm/hhvm-docker can be labeled official, as it's hosted by the `hhvm`-organisation.

**Comment by mofarrell** [comment]
@vicvolk all the packages are on docker hub here https://hub.docker.com/u/hhvm/
It would be good for us to document docker as an installation method.

**Comment by vicvolk** [comment]
Thank you, guys, for this information!

**Comment by mofarrell** [comment]
I am actually going to keep this open until I add a doc page for the Docker image.
