### ISSUE TITLE
HHVM Brew Install Source - imagemagick

### ISSUE THREAD

**Issue by team92** [hhvm/user-documentation#409]
Please complete the information below:

# Where is the problem?

https://docs.hhvm.com/hhvm/installation/building-from-source#mac-os-x-homebrew 

# What is the problem?
Install dependencies - Doesn't work with:
   brew install imagemagick
need to use:
   brew install imagemagick@6

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2017-01-27T19:49:24+0000:871b2d5328fd88ead184ac9ef296d931076e3168:e34c65d9a3e19063b233353707cedc593e3f0a5c
 - Page requested: /hhvm/installation/building-from-source
 - Page requested at: Sun, 29 Jan 2017 06:52:05 +0000
 - Controller: GuidePageController

**Comment by mofarrell** [comment]
Fixed to using `imagemagick@6`.  Also update the brew formula to build the imagick extension, which had been disabled.
