### ISSUE TITLE
Indicate static methods

### ISSUE THREAD

**Issue by fredemmott** [hhvm/user-documentation#41]
eg `Vector::fromItems()`

**Comment by JoelMarcey** [comment]
Yeah, the `static` is in the HHI signature for `Vector::fromItems()`.

And we have `static` in the HNI definitions for something like async mysql.

So, maybe it is just a matter of the tooling picking it up as part of the YAML.

**Comment by fredemmott** [comment]
probably not putting it in the YAML. Should be an easy change though.
