### ISSUE TITLE
need info how to get version of extension

### ISSUE THREAD

**Issue by btangmu** [hhvm/user-documentation#410]
Please complete the information below:

# Where is the problem?

https://docs.hhvm.com/hhvm/extensions/introduction

# What is the problem?

There's no information about how to get the version number of an extension. With phpinfo() or "php -i", PHP5 reports:
```
intl

Internationalization support => enabled
version => 1.1.0
ICU version => 56.1
ICU Data version => 56.1
```
What is the corresponding method with hhvm? It should be documented along with get_loaded_extensions(). 

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2017-01-27T19:49:24+0000:871b2d5328fd88ead184ac9ef296d931076e3168:e34c65d9a3e19063b233353707cedc593e3f0a5c
 - Page requested: /
 - Page requested at: Fri, 03 Feb 2017 18:15:16 +0000
 - Controller: HomePageController

**Comment by mofarrell** [comment]
This is documented in the php documentation:
https://secure.php.net/manual/en/function.phpversion.php
