### ISSUE TITLE
typo on page /hack/tools/transpiler

### ISSUE THREAD

**Issue by seeekr** [hhvm/user-documentation#411]
Please complete the information below:

# Where is the problem?

`cp -r /usr/share/hhvm/hack/hacklib /tmp/traspiled`

should be

`cp -r /usr/share/hhvm/hack/hacklib /tmp/transpiled`

(notice missing **n**)

- - - eg "The section describing how widgets work" - - -

# What is the problem?

- - - eg "It doesn't explain that widgets are singletons" - - -

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2017-01-27T19:49:24+0000:871b2d5328fd88ead184ac9ef296d931076e3168:e34c65d9a3e19063b233353707cedc593e3f0a5c
 - Page requested: /hack/tools/transpiler
 - Page requested at: Sun, 05 Feb 2017 18:27:39 +0000
 - Controller: GuidePageController

**Comment by mofarrell** [comment]
Fixed the typo: e78928a6f1eafdd8f7be3b87edfbaa5503e11d5f
