### ISSUE TITLE
Table syntax error in INI setting hhvm.filter_gc_points

### ISSUE THREAD

**Issue by jwatzman** [hhvm/user-documentation#414]
Please complete the information below:

# Where is the problem?

https://docs.hhvm.com/hhvm/configuration/INI-settings#garbage-collector-settings

# What is the problem?

There is some sort of markdown syntax error in the table row for `hhvm.filter_gc_points` causing the table to be obviously incorrectly formatted.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2017-02-15T22:24:27+0000:e05aef1e014cc0166d7cc098895834dec8dc358d:22529b98d9ca2b7aaf52731f7e008ce05ae40adc
 - Page requested: /hhvm/configuration/INI-settings
 - Page requested at: Thu, 16 Feb 2017 09:49:38 +0000
 - Controller: GuidePageController

**Comment by mofarrell** [comment]
Fixed.
