### ISSUE TITLE
Document typehints for generators

### ISSUE THREAD

**Issue by fredemmott** [hhvm/user-documentation#419]
There's documentation for async generators (use `AsyncIterator<T>`), but not for normal generators. It looks like `Iterator<T>` is usually the right type to use, but I'm not entirely certain this is 'best', or what other options are.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2017-03-03T21:59:52+0000:bc17cad77c05e05f915f0b0f8932063ff752021e:4021ad54335437180b9af62219a662df9f86158f
 - Page requested: /hack/types/advanced-rules
 - Page requested at: Tue, 21 Mar 2017 21:32:22 +0000
 - Controller: GuidePageController

**Comment by fredemmott** [comment]
cc @jwatzman, @elgenie for correctness :)

**Comment by RexJaeschke** [comment]
The revised tutorial covers generators under the `yield` operator. There are 3 examples: generating a series with `int` key, a series with `string` key, and reading text records from a file. All use `foreach`; none use `Iterator<t>` directly.
