### ISSUE TITLE
Traits documentation is missing some stuff.

### ISSUE THREAD

**Issue by talldean** [hhvm/user-documentation#421]
Please complete the information below:

# Where is the problem?

The document on Traits is missing some stuff.

# What is the problem?

If I have two traits applied to the same class, and they both implement the same method, what happens there?  Does one or the other take precedence?  Do they both fire?

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2017-03-23T19:06:12+0000:2801be46a87fcf7758326f0287f092540e104672:5c6349fa6882ab5a833315bd005d9067b5852cef
 - Page requested: /hack/other-features/trait-and-interface-requirements
 - Page requested at: Fri, 31 Mar 2017 21:36:10 +0000
 - Controller: GuidePageController

**Comment by RexJaeschke** [comment]
Following PHP's model, I tried the following:

```Hack
trait T1 {
  public function f(): void {}
}

trait T2 {
  public function f(): void {}
}

class C {
  use T1, T2 {
    T2::f as g;     // ERROR!
  }
}
```
However, the checker reported, "Trait use aliasing is not supported in Hack. (Naming[2092])".

When I asked the language developers if there was a workaround, I got the following reply: "Not at the moment. We're working on some proposals, but currently you simply cannot use two traits with the same function unless you reimplement the method on the using class."
