### ISSUE TITLE
hhvm does support typed variadic arguments now

### ISSUE THREAD

**Issue by pweng** [hhvm/user-documentation#422]
Please complete the information below:

# Where is the problem?
docs say hhvm doesn't support typed variadic arguments and recommends using partial mode
- - - eg "The section describing how widgets work" - - -

# What is the problem?

- - - eg "It doesn't explain that widgets are singletons" - - -

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2017-03-23T19:06:12+0000:2801be46a87fcf7758326f0287f092540e104672:5c6349fa6882ab5a833315bd005d9067b5852cef
 - Page requested: /hack/types/advanced-rules
 - Page requested at: Fri, 31 Mar 2017 22:39:33 +0000
 - Controller: GuidePageController

**Comment by mofarrell** [comment]
Sorry what is wrong with that statement?  A little more info about what you want changed would be nice.

**Comment by pweng** [comment]
Hhvm now supports typed variadic arguments so you don't need to run in
partial mode.

**Comment by fredemmott** [comment]
This was fixed a few months ago by a41fb9078be8d2607a9302500048fcae8b66a964
