### ISSUE TITLE
Typo in Collections introduction

### ISSUE THREAD

**Issue by showmethewei** [hhvm/user-documentation#423]
Please complete the information below:

# Where is the problem?
https://docs.hhvm.com/hack/collections/introduction
- - - eg "The section describing how widgets work" - - -

# What is the problem?
Typo - search for "occaisionally"
- - - eg "It doesn't explain that widgets are singletons" - - -

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2017-03-23T19:06:12+0000:2801be46a87fcf7758326f0287f092540e104672:5c6349fa6882ab5a833315bd005d9067b5852cef
 - Page requested: /hack/collections/introduction
 - Page requested at: Fri, 07 Apr 2017 18:06:09 +0000
 - Controller: GuidePageController

**Comment by Daniel15** [comment]
You can submit a pull request to fix this if you like :) The contents are in this repository and you can edit the file directly using GitHub: https://github.com/hhvm/user-documentation/blob/master/guides/hack/23-collections/01-introduction.md
