### ISSUE TITLE
The syntax higlighting in the pipe docs mark $$ as a syntax error

### ISSUE THREAD

**Issue by Daniel15** [hhvm/user-documentation#425]
Please complete the information below:

# Where is the problem?
Examples on "Operators: Pipe Operator" page  (https://docs.hhvm.com/hack/operators/pipe-operator)

# What is the problem?
All instances of `$$` are marked as a syntax error:
![](http://ss.dan.cx/2017/04/chrome_12-10.58.57.png)

--------------------------------

 - Build ID: 2017-03-23T19:06:12+0000:2801be46a87fcf7758326f0287f092540e104672:5c6349fa6882ab5a833315bd005d9067b5852cef
 - Page requested: /hack/operators/pipe-operator
 - Page requested at: Wed, 12 Apr 2017 17:58:45 +0000
 - Controller: GuidePageController

**Comment by fredemmott** [comment]
Switched as part of changign the markdown pipeline. It's not understood, but it's not an error
