### ISSUE TITLE
Page links to itself

### ISSUE THREAD

**Issue by betodealmeida** [hhvm/user-documentation#426]
Please complete the information below:

# Where is the problem?

The invariant page has a section "See also" which links to itself.

# What is the problem?

"See also" should link to something else and give more information (unless this was a page for recursion).

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2017-04-13T17:22:59+0000:1f7f374ac3d8d9c810df6cf46a63873345f6ed14:c4e655476174fc7cd467ece4b54bb3f9b58025cd
 - Page requested: /hack/reference/function/HH.invariant/
 - Page requested at: Fri, 14 Apr 2017 19:00:20 +0000
 - Controller: APIClassPageController

**Comment by fredemmott** [comment]
Fix isn't in prod yet, but it's done partially with the referenced commit, and partially as part of #471 - fix will be deployed when we cut over from the ruby markdown pipeline.
