### ISSUE TITLE
HHVM installation 

### ISSUE THREAD

**Issue by alfredo-ardito** [hhvm/user-documentation#441]
Please complete the information below:

# Where is the problem?

Installing HHVM on Debian 8.8 after a clean install

# What is the problem?

The following packages have unmet dependencies:
 hhvm : Depends: libsodium but it is not installable
E: Unable to correct problems, you have held broken packages.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2017-04-13T17:22:59+0000:1f7f374ac3d8d9c810df6cf46a63873345f6ed14:c4e655476174fc7cd467ece4b54bb3f9b58025cd
 - Page requested: /hhvm/installation/linux
 - Page requested at: Tue, 06 Jun 2017 20:03:41 +0000
 - Controller: GuidePageController

**Comment by Orvid** [comment]
See https://github.com/facebook/hhvm/issues/7871 we mistakenly pushed a package with an invalid dependency. @mofarrell is working on getting a new version pushed with the correct dependency.
