### ISSUE TITLE
Failed to build the site

### ISSUE THREAD

**Issue by qfu** [hhvm/user-documentation#442]
Trying to build the site locally on Macos but getting this error:

2017-06-12 16:07:49] Undefined function: HH\get_headers_secure..
Fatal error: Uncaught exception 'HH\InvariantException' with message 'Didn't see anything that looked like a type
' in /Users//Desktop/user-documentation/vendor/facebook/definition-finder/src/consumers/TypehintConsumer.php:1
79

Version:10.12.5 (16F2073)

**Comment by SiebelsTim** [comment]
Have you pointed `LocalConfig::HHVM_TREE` to your checkout of the hhvm source tree cloned fromhttps://github.com/facebook/hhvm?

If so, which commit points to HEAD?

**Comment by qfu** [comment]
$ cat .git/HEAD 
ref: refs/heads/master

**Comment by SiebelsTim** [comment]
Great! :)
