### ISSUE TITLE
Suggestion Execute a function every x seconds

### ISSUE THREAD

**Issue by Punxor** [hhvm/user-documentation#445]
Suggestion:

Execute a function every x seconds, This will be very useful if you plan on developing a CLI to do stuff for you!

Basically like JavaScript setInterval or something thanks.

--------------------------------

 - Build ID: 2017-06-13T17:55:28+0000:7edf21e5f737fb6fc6f06ed33b8715de5314aee1:6304d6685058fdc0f5f17cfe4d7841d45ad14740
 - Page requested: /
 - Page requested at: Sun, 16 Jul 2017 19:10:56 +0000
 - Controller: HomePageController

**Comment by SiebelsTim** [comment]
This is probably not something the language will include. Eventhandling libraries could solve your problem (Maybe look into https://github.com/reactphp/event-loop).

Furthermore, this probably isn't the correct repository to discuss such a change.
