### ISSUE TITLE
Introduction Not Responsive

### ISSUE THREAD

**Issue by NipunSingh** [hhvm/user-documentation#451]
Please complete the information below:

# Where is the problem?

https://docs.hhvm.com/hack/XHP/introduction

# What is the problem?

The website isn't correctly responsive. When viewing full screen on Chrome on a Macbook Pro 13'inch, the content of the website doesn't fit on a page and I get a horizontal scroll bar. Makes reading the docs way harder having to scroll from left / right side for reach and every sentence.

Pic here showing cut off right edge:
https://pasteboard.co/GF6CiF0.png
--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2017-08-01T23:18:35+0000:96c71d3a1daea96542fc54559a7da687922dc37a:1cda87cb4b13fce2acc952825f8aecf6813b098a
 - Page requested: /hack/XHP/introduction
 - Page requested at: Fri, 11 Aug 2017 04:42:06 +0000
 - Controller: GuidePageController

**Comment by AndrewDiMola** [comment]
Similar to #304, closing because docs are now responsive.
