### ISSUE TITLE
Cannot install HHVM on Debian 9

### ISSUE THREAD

**Issue by joernneumeyer** [hhvm/user-documentation#452]
Please complete the information below:

# Where is the problem?

Installation of HHVM on Debian 9 "Stretch"

# What is the problem?

After adding the keys to "apt-get" and trying to install hhvm (sudo apt-get install hhvm) I get the following errors:

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 hhvm : Depends: libboost-filesystem1.55.0 but it is not installable
        Depends: libboost-program-options1.55.0 but it is not installable
        Depends: libboost-system1.55.0 but it is not installable
        Depends: libboost-regex1.55.0 but it is not installable
        Depends: libgnutls-deb0-28 but it is not installable
        Depends: libicu52 but it is not installable
        Depends: libmysqlclient18 but it is not installable
        Depends: libonig2 but it is not installable
        Depends: libvpx1 but it is not installable
        Depends: libpng12-0 but it is not installable
        Depends: libssl1.0.0 but it is not installable
        Depends: libboost-thread1.55.0 but it is not installable
        Depends: libboost-context1.55.0 but it is not installable
        Depends: libmagickwand-6.q16-2 but it is not installable
        Depends: libgoogle-glog0 but it is not installable
        Depends: libzip2 but it is not installable
        Depends: libsnappy1 but it is not installable
        Depends: libsodium13 but it is not installable
E: Unable to correct problems, you have held broken packages.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2017-08-01T23:18:35+0000:96c71d3a1daea96542fc54559a7da687922dc37a:1cda87cb4b13fce2acc952825f8aecf6813b098a
 - Page requested: /hhvm/installation/introduction
 - Page requested at: Thu, 17 Aug 2017 15:14:01 +0000
 - Controller: GuidePageController

**Comment by fredemmott** [comment]
Not currently supported, and not a documentation issue. https://github.com/hhvm/packaging/issues/128
