### ISSUE TITLE
404: /hack/tools/transpiler

### ISSUE THREAD

**Issue by morrisonlevi** [hhvm/user-documentation#454]
Please complete the information below:

# How I got to this page:

I came from a Google search when searching for `h2tp`.

# What I expected to find here:

Documentation on transpiling HHVM to PHP.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2017-08-30T21:18:06+0000:8cd4e0ba1b69cd6f886c69105cc88494eff5691a:688fc658056e4f639625475a4fb92cfae15b46a4
 - Page requested: /hack/tools/transpiler
 - Page requested at: Tue, 05 Sep 2017 15:54:43 +0000
 - Controller: HTTP404Controller

**Comment by fredemmott** [comment]
h2tp was removed from HHVM in https://github.com/facebook/hhvm/commit/486f44ac4f3607ea8e3f1665fd67945364120280 as it hadn't been compatible with modern Hack code for quite some time; the page was removed more recently, and should vanish from google shortly.
