### ISSUE TITLE
Vec -> vec

### ISSUE THREAD

**Issue by lydxlx1** [hhvm/user-documentation#455]
Please complete the information below:

# Where is the problem?
This page https://docs.hhvm.com/hack/collections/hack-arrays.

Additionally, Hack provides the following conversion functions:
`vec<Tv>(Traversable<Tv>): Vec<Tv>`

# What is the problem?

Vec should be vec.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2017-08-30T21:18:06+0000:8cd4e0ba1b69cd6f886c69105cc88494eff5691a:688fc658056e4f639625475a4fb92cfae15b46a4
 - Page requested: /hack/collections/hack-arrays
 - Page requested at: Tue, 05 Sep 2017 17:31:21 +0000
 - Controller: GuidePageController

**Comment by fredemmott** [comment]
Fixed by c1dbab789e14dce0edc798010aba792776bd147a , but I typoed issue there
