### ISSUE TITLE
Docker documentation does not explain why you should not be putting all your code in /var/www/public

### ISSUE THREAD

**Issue by mmartinez0** [hhvm/user-documentation#463]
Please complete the information below:

# Where is the problem?

Page "Installation: Docker" - https://docs.hhvm.com/hhvm/installation/docker

# What is the problem?

Dockerfile is incorrect as is. Lines 3 and 4 currently reads
```
RUN rm -rf /var/www
ADD . /var/www
```
Instead it should be
```
RUN rm -rf /var/www/public
ADD . /var/www/public
```
I found the correct documentation in the Docker page: https://hub.docker.com/r/hhvm/hhvm-proxygen/
--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2017-08-30T21:18:06+0000:8cd4e0ba1b69cd6f886c69105cc88494eff5691a:688fc658056e4f639625475a4fb92cfae15b46a4
 - Page requested: /hhvm/installation/docker
 - Page requested at: Sat, 23 Sep 2017 21:42:49 +0000
 - Controller: GuidePageController

**Comment by mofarrell** [comment]
Thank you.  Fixed.  https://github.com/hhvm/user-documentation/commit/d99126bb11989e85d134cece8d1a4c17440342fd

**Comment by fredemmott** [comment]
Reverting: this change is only correct if all your code is in the public document root. This is bad practice. We should update the documentation to explain why.

**Comment by fredemmott** [comment]
I've also updated the text on dockerhub.

**Comment by fredemmott** [comment]
Re-opening as I still have stuff to do here: once the improvements are deployed to docs.hhvm.com, we should change the dockerhub docs to link to the explanation here instead of duplicating it.

**Comment by fredemmott** [comment]
Done.
