### ISSUE TITLE
Please add yum package

### ISSUE THREAD

**Issue by esk79** [hhvm/user-documentation#466]
Please complete the information below:

# Where is the problem?

The "Installation: Building From Source" section

# What is the problem?

Please considering adding a yum install package considering FB employee dev servers are running CentOS 7+, deeming the install packages provided here useless. 

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2017-09-28T18:54:39+0000:245dcec7bef798454454dcdae140ebec650cecb7:aee3ea4fb9c11499ddf0e0d51128992f56f1f3e4
 - Page requested: /hhvm/installation/building-from-source
 - Page requested at: Tue, 10 Oct 2017 21:49:31 +0000
 - Controller: GuidePageController

**Comment by fredemmott** [comment]
HHVM is installed on FB devservers already. If not, you want the devserver support group.

Additionally, a public centos7 build will not be suitable for any FB www work.
