### ISSUE TITLE
Spaceship operator is now type-checked

### ISSUE THREAD

**Issue by periodic1236** [hhvm/user-documentation#467]
Please complete the information below:

# Where is the problem?

The intro section

# What is the problem?

The second paragraph is out of date. It states:

> The current exception of support is the "spaceship" (<=>) operator; you can use it in your Hack code since HHVM supports it, but it will not be type checked.

Type checker support for spaceship has been provided by facebook/hhvm@4ccb650.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2017-09-28T18:54:39+0000:245dcec7bef798454454dcdae140ebec650cecb7:aee3ea4fb9c11499ddf0e0d51128992f56f1f3e4
 - Page requested: /hack/operators/introduction
 - Page requested at: Tue, 17 Oct 2017 19:24:51 +0000
 - Controller: GuidePageController

**Comment by fredemmott** [comment]
#461

**Comment by periodic1236** [comment]
Oops, sorry.

**Comment by fredemmott** [comment]
No problem, thanks for reporting anyway :)
