### ISSUE TITLE
HHVM public key not available for Trusty

### ISSUE THREAD

**Issue by chiqomar** [hhvm/user-documentation#478]
Since Friday, we have been having the following problem:
In trying to install HHVM in an Ubuntu Trusty docker image, installation throws the following error when running `apt-get update`: 
```
W: GPG error: https://dl.hhvm.com trusty InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5A16E7281BE7A449
```
And the following during install using `apt-get install -y hhvm`:
```
WARNING: The following packages cannot be authenticated!
  hhvm
E: There are problems and -y was used without --force-yes
```
Using `--force-yes` allows us to install, but is not ideal. If you could please update the public key for the trusty package, that would be appreciated.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2017-11-23T07:45:10+0000:2555282b8f6ccf911b335e1d4f3b976dc5bfc9b0
 - Page requested: /hhvm/installation/introduction
 - Page requested at: Tue, 28 Nov 2017 17:10:54 +0000
 - Controller: GuidePageController

**Comment by fredemmott** [comment]
Re-filed against packaging. FYI, 3.18 was the last release to support trusty, and we drop support for 3.18 in < 2 months: https://docs.hhvm.com/hhvm/installation/release-schedule
