### ISSUE TITLE
Mirrors not up to date

### ISSUE THREAD

**Issue by bauerj** [hhvm/user-documentation#481]
All the mirrors linked [here](https://docs.hhvm.com/hhvm/installation/linux#mirrors) do not contain recent packages.

Apparently the source that I've been using since 2014 (`rsync.osuosl.org::hhvm`) is not updated any more. Since this affects all mirrors, I suggest you do either:

* Remove the section from the docs altogether and inform the mirror maintainers that they can shut down their service
* Inform all maintainers about the new mirroring source
* Re-enable the old mirroring source

**Comment by fredemmott** [comment]
I've reached out to OSUOSL to see if they can switch.

If you're running a mirror and have the AWS utilities, you can update it with:

```
 aws s3 sync --no-sign-request --region us-west-2 s3://hhvm-downloads/ ./localpath/ --exclude '*index.html' --dryrun
```

This is currently ~ 300GB; we're being less aggressive about pruning old packages than we have in the past.

**Comment by fredemmott** [comment]
Hopeful that OSUOSL are going to update shortly, but removing for now.

**Comment by fredemmott** [comment]
OSUOSL should now be up-to-date, but they will have limited retention of nightly builds.
