### ISSUE TITLE
Explain basic type constant usages

### ISSUE THREAD

**Issue by hurrymaplelad** [hhvm/user-documentation#484]
Please complete the information below:

# Where is the problem?

https://docs.hhvm.com/hack/type-constants/introduction

# What is the problem?

We jump straight into explaining abstract type constants as an alternative to generics. We don't mention the simplest syntax of concrete type constants, useful for namespacing.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2017-12-18T23:35:16+0000:1fa61acce1c6a8319d7b3ce2b305350571200b70
 - Page requested: /hack/type-constants/introduction
 - Page requested at: Wed, 20 Dec 2017 23:47:28 +0000
 - Controller: GuidePageController

**Comment by fredemmott** [comment]
If you've got some time, a pull request would be very welcome :) https://github.com/hhvm/user-documentation/tree/master/guides/hack/43-type-constants

**Comment by RexJaeschke** [comment]
The topic of type constants has been overhauled in the tutorial revision. The comparison to generics was removed.
