### ISSUE TITLE
Improper generated HTML in Types: Casting page

### ISSUE THREAD

**Issue by pittsw** [hhvm/user-documentation#485]
Please complete the information below:

# Where is the problem?

https://docs.hhvm.com/hack/types/casting

# What is the problem?

Screenshot:
<img width="774" alt="screen shot 2017-12-22 at 2 17 15 pm" src="https://user-images.githubusercontent.com/1612952/34313807-dc7d8faa-e722-11e7-8b67-aee626d72413.png">

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2017-12-18T23:35:16+0000:1fa61acce1c6a8319d7b3ce2b305350571200b70
 - Page requested: /hack/types/casting
 - Page requested at: Fri, 22 Dec 2017 22:15:38 +0000
 - Controller: GuidePageController

**Comment by fredemmott** [comment]
Markdown source is incorrect, the link is invalid - https://github.github.com/gfm/#link-destination
