### ISSUE TITLE
Hack language example is broken/not showing

### ISSUE THREAD

**Issue by huitsing** [hhvm/user-documentation#487]
Please complete the information below:

# Where is the problem?

The section that shows the hack language example, as a counter-example to pure PHP, does not render on `/hack/types/introduction` 

# What is the problem?

The Hack language example does not render. See screenshot.
![screen shot 2018-01-05 at 9 26 32 am](https://user-images.githubusercontent.com/9354037/34620567-ba9163ac-f1fa-11e7-8ceb-19b258cf9ef5.png)

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2017-12-28T19:46:04+0000:1027b39d7f9aaab5afeab44844df4e0fae8633bf
 - Page requested: /hack/types/introduction
 - Page requested at: Fri, 05 Jan 2018 17:25:09 +0000
 - Controller: GuidePageController

**Comment by fredemmott** [comment]
can't build the image to push this change as security.ubuntu.com is currently inconsistent >_<
