### ISSUE TITLE
404: /hack/reference/function/HH.Lib.Str.join/

### ISSUE THREAD

**Issue by hrp** [hhvm/user-documentation#491]
Please complete the information below:

# How I got to this page:

- - - eg "I clicked a link on <address of other site>" - - -

# What I expected to find here:

- - - eg "Documentation tell me how to <do something>" - - -

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2018-01-17T21:46:58+0000:6b8b2654c739da9b49b20f6d7a5fb4d9a5a6822b
 - Page requested: /hack/reference/function/HH.Lib.Str.join/
 - Page requested at: Sun, 21 Jan 2018 08:18:12 +0000

**Comment by fredemmott** [comment]
How did you get to this page? This page should not exist.

**Comment by fredemmott** [comment]
Facebook internal search are looking into how this is still indexed; I'll be digging into why google's not done the same: we have a sitemap, and it's been a 404 since November.

I'm also adding a redirect.
