### ISSUE TITLE
Integrated Extensions: Extension thread link wrong

### ISSUE THREAD

**Issue by pprasse** [hhvm/user-documentation#492]
Please complete the information below:

# Where is the problem?

The section "Integrated Extensions"

# What is the problem?

The Link "thread" links to http://php.net/manual/en/class.thread.php
The Thread class is not implemented in hhvm. In hhvm ext/thread refers to hhvm-specific functions hphp_get_thread_id() and hphp_gettid().
See https://github.com/facebook/hhvm/blob/7625626aa476421ff9c2aca91af8ea3fe4e16102/hphp/runtime/ext/thread/ext_thread.php

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2018-01-17T21:46:58+0000:6b8b2654c739da9b49b20f6d7a5fb4d9a5a6822b
 - Page requested: /hhvm/extensions/introduction
 - Page requested at: Sun, 21 Jan 2018 09:17:37 +0000
 - Controller: GuidePageController

**Comment by AndrewDiMola** [comment]
Fixed in https://github.com/hhvm/user-documentation/commit/9f590b7a6fe991a8843147977254f35dca6574b1.
