### ISSUE TITLE
Explain syntax used in Enum examples

### ISSUE THREAD

**Issue by Nick-the-BinaryTree** [hhvm/user-documentation#493]
Please complete the information below:

# Where is the problem?
"What are Enums?" section

# What is the problem?
Code someone reading the overview of the language might not understand:

`enum DayOfWeek: **int as int** {`

`?string`

`return $opening_hours->get(**DayOfWeek::assert($x)**)`

`echo getOpeningHours(**DayOfWeek::Wednesday**);`

Maybe add some links to documentation for these different bits of syntax.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2018-01-17T21:46:58+0000:6b8b2654c739da9b49b20f6d7a5fb4d9a5a6822b
 - Page requested: /hack/overview/collections
 - Page requested at: Sun, 21 Jan 2018 14:43:13 +0000
 - Controller: GuidePageController

**Comment by RexJaeschke** [comment]
The whole "Enum" topic has been revised, and the new version avoids the problem cited.
