### ISSUE TITLE
Information on serialization_size_limit is incorrect

### ISSUE THREAD

**Issue by jkedgar** [hhvm/user-documentation#496]
Please complete the information below:

# Where is the problem?

In the section documenting serialization_size_limit

# What is the problem?

It indicates that the default value is about 2Mb, but the value specified is about 2Gb.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2018-01-25T18:26:21+0000:828272c7809792d44ecf17f9a8c9492cc20c311c
 - Page requested: /hhvm/configuration/INI-settings
 - Page requested at: Mon, 29 Jan 2018 18:50:17 +0000
 - Controller: GuidePageController

**Comment by AndrewDiMola** [comment]
Fixed in https://github.com/hhvm/user-documentation/commit/b082c44992355a25fd57d900f9eab5c20efa4518.
