### ISSUE TITLE
From some pages in the HHVM guide, clicking 'Getting Started' redirects to the Hack Guide

### ISSUE THREAD

**Issue by CatherineGasnier** [hhvm/user-documentation#501]
Please complete the information below:

# Where is the problem?

From some pages in the HHVM guide, like 'Repo Authoritative' (https://docs.hhvm.com/hhvm/advanced-usage/repo-authoritative), clicking 'Getting Started' redirects to the getting started page of the Hack Guide instead of the one from the HHVM guide. This may be the case from other pages of the HHVM guide as well.

# What is the problem?

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2018-01-25T18:26:21+0000:828272c7809792d44ecf17f9a8c9492cc20c311c
 - Page requested: /hack/getting-started/getting-started
 - Page requested at: Tue, 30 Jan 2018 17:13:40 +0000
 - Controller: GuidePageController

**Comment by fredemmott** [comment]
Turns out this is a caching issue: the 'static' XHP is put into APC, as it has a significant affect on unit test time (we crawl the entire set) - but it was only keyed on label and parent label. Whichever was loaded first would poison the other.
