### ISSUE TITLE
keyserver not available for debian 9

### ISSUE THREAD

**Issue by abkrim** [hhvm/user-documentation#504]
Please complete the information below:

# Where is the problem?

Manual for install HVMMin Debian 9

```
apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xB4112585D386EB94
```

# What is the problem?
```
apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xB4112585D386EB94
Executing: /tmp/apt-key-gpghome.bLO1t59mZL/gpg.1.sh --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xB4112585D386EB94
gpg: keyserver receive failed: No keyserver available
```
--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2018-02-05T19:47:41+0000:d396172dc2eb68247a4378d63b7df67b6cb56caa
 - Page requested: /hhvm/installation/linux
 - Page requested at: Mon, 12 Feb 2018 12:19:32 +0000
 - Controller: GuidePageController

**Comment by fredemmott** [comment]
Assuming your local network isn't blocking it, this would be an intermittent problem with Ubuntu's infrastructure.

We can't directly fix this, but I'll add an alternative:

```
apt-get install -y curl
curl https://dl.hhvm.com/conf/hhvm.gpg.key | apt-key add -
```
