### ISSUE TITLE
[Docs] What are valid types for class constants

### ISSUE THREAD

**Issue by bcherny** [hhvm/user-documentation#506]
According to the [spec](https://github.com/hhvm/hack-langspec/blob/master/spec/16-classes.md#constants):

> Note: Although the grammar allows a class constant to have any type, there is no way to write a constant-expression for closures, tuples, or shapes.

However, Objects (like `Map` or `ImmMap`) also can't be class constants.

We should document this, and suggest some workarounds:

- Using a `dict` instead
- Using a `static` property instead of a `const`

**Comment by RexJaeschke** [comment]
In the revised Tutorial, I've added the following text to the "Classes" topic "Constants": 

Note that for some types---the legacy container types `Vector`, `Map`, `Set`, et al., and closures---there is *no* way to write an initializer that is considered to be a compile-time constant. Therefore, a class constant cannot have such a type. However, the types `array`, `vec`, `dict`, and `set`, can be used *provided* all their subinitializers are constant expressions.
