### ISSUE TITLE
Async vs Awaitable should suggest using async when the return type is Awaitable

### ISSUE THREAD

**Issue by sfilipco** [hhvm/user-documentation#511]
Please complete the information below:

# Where is the problem?

https://docs.hhvm.com/hack/async/async-vs-awaitable

# What is the problem?

While functions that return Awaitables don't need to be async if they don't use await, it is recommended that all the functions use async because the VM works better that way.
Outside of typing and readability, it is rare to come up with a reason to leave a function non async.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2018-02-12T16:55:44+0000:15d534bde9bfa75fd172b4d5ac76c072f9568172
 - Page requested: /hack/async/async-vs-awaitable
 - Page requested at: Tue, 27 Feb 2018 23:13:21 +0000
 - Controller: GuidePageController

**Comment by fredemmott** [comment]
This page was primarily intended to cover why `async` is banned for interface methods; the diff adds a section at the bottom clarifying that - it'll be live next time we update the site.
