### ISSUE TITLE
Broken link to tutorial

### ISSUE THREAD

**Issue by letharion** [hhvm/user-documentation#512]
Please complete the information below:

# Where is the problem?

Link to tutorial on https://docs.hhvm.com/hack/getting-started/getting-started

# What is the problem?

Link yields a 404 at http://hacklang.org/tutorial/

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2018-02-12T16:55:44+0000:15d534bde9bfa75fd172b4d5ac76c072f9568172
 - Page requested: /hack/getting-started/getting-started
 - Page requested at: Tue, 06 Mar 2018 19:20:14 +0000
 - Controller: GuidePageController

**Comment by SiebelsTim** [comment]
It's supposed to be http://hacklang.org/tutorial.html
