### ISSUE TITLE
https://www.facebook.com/recover/code?recover_method=send_sms&ce=1625022&hash=AUb3kNulTuZ68uPi

### ISSUE THREAD

**Issue by redarsurgul** [hhvm/user-documentation#515]
Please complete the information below:

# Where is the problem?

- - - eg "The section describing how widgets work" - - -

# What is the problem?

- - - eg "It doesn't explain that widgets are singletons" - - -

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2018-03-15T22:49:42+0000:f2c2ba1cc03498116980137a484defa1c827857b
 - Page requested: /search
 - Page requested at: Mon, 19 Mar 2018 21:34:02 +0000
 - Controller: SearchController

**Comment by fredemmott** [comment]
@redsargurl: posting these recovery links to github is certainly not doing what you intend.
