### ISSUE TITLE
No information on keyset usage

### ISSUE THREAD

**Issue by eryi** [hhvm/user-documentation#516]
Please complete the information below:

# Where is the problem?

There is no information on how to use keyset

# What is the problem?

While usage of dict and vec is similar to php arrays, the usage of keyset is unclear. An updated outline similar to the one found on facebook/hhvm#6453 would be very helpful.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2018-03-15T22:49:42+0000:f2c2ba1cc03498116980137a484defa1c827857b
 - Page requested: /hack/collections/hack-arrays
 - Page requested at: Wed, 28 Mar 2018 09:54:34 +0000
 - Controller: GuidePageController

**Comment by RexJaeschke** [comment]
The revised tutorial "Types" chapter covers "Arrays", of which "keyset" is one subtopic. As well as introducing this topic and showing some small examples of its use, I added to that a hyperlinked table of library functions (each with a brief description) that can be used to manipulate a keyset.

For symmetry, I also added a library-function table for the types `vec`, `dict`, and `string`.
