### ISSUE TITLE
How to install HHVM on Windows server?

### ISSUE THREAD

**Issue by kego67** [hhvm/user-documentation#517]
Dear HHVM team,

I have a problem about CPU 100% always peak of running PHP on windows server. As I have looked into the HHVM, and might able to help to improve speed of running PHP coding. 

But, I have no idea how to install HHVM on IIS/Fastcgi and Windows server 2012 R2

Best Regards,
Nattapat
--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2018-03-30T16:53:45+0000:88aaddd5256aaa347894ce88542a44aadbb921d0
 - Page requested: /hhvm/installation/windows
 - Page requested at: Mon, 09 Apr 2018 09:52:29 +0000
 - Controller: GuidePageController

**Comment by fredemmott** [comment]
We do not currently support Windows; you might have luck with https://docs.microsoft.com/en-us/windows/wsl/install-win10 , however I wouldn't recommend your use-case for this - for PHP code, we recommend using PHP. See https://hhvm.com/blog/2017/09/18/the-future-of-hhvm.html
