### ISSUE TITLE
Searched for 'using', and had no useful results.

### ISSUE THREAD

**Issue by talldean** [hhvm/user-documentation#521]
Please complete the information below:

# Where is the problem?

There's a 'using' keyword in Hacklang.

# What is the problem?

If you search for 'using', the doc doesn't come up.
https://docs.hhvm.com/hack/disposables/introduction

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2018-03-30T16:53:45+0000:88aaddd5256aaa347894ce88542a44aadbb921d0
 - Page requested: /search
 - Page requested at: Thu, 19 Apr 2018 17:00:17 +0000
 - Controller: SearchController

**Comment by muglug** [comment]
👍, ran into this as well

**Comment by AndrewDiMola** [comment]
Typing in `using` as a keyword now leads readers to the `using` page here: https://docs.hhvm.com/hack/statements/using. This page links to [Object Disposal](https://docs.hhvm.com/hack/classes/object-disposal) too.

https://docs.hhvm.com/hack/statements/using

![image](https://user-images.githubusercontent.com/5179225/109557932-bf71d400-7aa6-11eb-9d89-7a93813b1a4f.png)

![image](https://user-images.githubusercontent.com/5179225/109557951-c698e200-7aa6-11eb-832d-3908f577ff2c.png)
