### ISSUE TITLE
suggestion about page Generics: Introduction

### ISSUE THREAD

**Issue by teddywang1992** [hhvm/user-documentation#524]
Please complete the information below:

# Where is the problem?

In the section about "Methods and functions can also be generic". I think the output "3 44 3a bb a" is a little bit confusing. I know it is right, but I do recommend to modify the format of it in the previous echo.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2018-03-30T16:53:45+0000:88aaddd5256aaa347894ce88542a44aadbb921d0
 - Page requested: /hack/generics/introduction
 - Page requested at: Thu, 26 Apr 2018 23:37:47 +0000
 - Controller: GuidePageController

**Comment by AndrewDiMola** [comment]
Closing because, to my knowledge, this example no longer exists.
