### ISSUE TITLE
Object Iteration unsupported but not listed

### ISSUE THREAD

**Issue by nickgarvey** [hhvm/user-documentation#525]
Please complete the information below:

# What is the problem?

Missing an unsupported feature under misc.
http://php.net/manual/en/language.oop5.iterations.php

There's a workplace post referencing this I can refer to, but don't want to do so on a public medium.

Please don't change anything below this point.

--------------------------------

 - Build ID: 2018-03-30T16:53:45+0000:88aaddd5256aaa347894ce88542a44aadbb921d0
 - Page requested: /hack/unsupported/others
 - Page requested at: Wed, 02 May 2018 23:33:53 +0000
 - Controller: GuidePageController

**Comment by fredemmott** [comment]
Source for these sections here: https://github.com/hhvm/user-documentation/tree/master/guides/hack/60-unsupported

We're likely to entirely remove that section as hack moves away from being a PHP dialect.

"it works in PHP" doesn't really lead to "it should work in Hack" any more, and a manually curated list of differences is going to stop scaling.

**Comment by AndrewDiMola** [comment]
Closing because (to my knowledge) we don't support this content on the site anymore.
