### ISSUE TITLE
Style is broken

### ISSUE THREAD

**Issue by Rekoz** [hhvm/user-documentation#529]
Please complete the information below:

# Where is the problem?

Any page of the doc

# What is the problem?

The side page blocks the content of the doc.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2018-05-22T20:33:05+0000:bb89df40dd6e5a8501362ce41535876ebcfa4d3f
 - Page requested: /hack/attributes/special
 - Page requested at: Fri, 25 May 2018 17:47:24 +0000
 - Controller: GuidePageController

**Comment by Wilfred** [comment]
I can't replicate this. Please say what browser and device (smartphone/desktop/tablet) you're using, and I'm happy to take a look.
