### ISSUE TITLE
Content pane is only partially visible

### ISSUE THREAD

**Issue by 4vanger** [hhvm/user-documentation#531]
Please complete the information below:

# Where is the problem?
Content pane

# What is the problem?
Sometimes after page loads content pane is partially covered with left pane
https://pxl.cl/dWWR
--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2018-05-22T20:33:05+0000:bb89df40dd6e5a8501362ce41535876ebcfa4d3f
 - Page requested: /hack/shapes/introduction
 - Page requested at: Thu, 07 Jun 2018 23:59:38 +0000
 - Controller: GuidePageController

**Comment by AndrewDiMola** [comment]
Closing because the docs site has undergone many refactors in the last 5 year and I believe this is no longer an issue.

@4vanger If the sidebar is still covering content because of site speeds, please reopen and let me know. If anyone else is experiencing this same issue, please also comment here.
