### ISSUE TITLE
How do I start the CLI Server?

### ISSUE THREAD

**Issue by WoLpH** [hhvm/user-documentation#533]
# Where is the problem?

The CLI Server section in the Advanced Usage section: https://docs.hhvm.com/hhvm/advanced-usage/CLI-server

# What is the problem?

Most of the "advanced usage" documentation has a few examples of which binary to execute. I can't seem to find the same for the "CLI Server" section though.

--------------------------------

 - Build ID: 2018-05-22T20:33:05+0000:bb89df40dd6e5a8501362ce41535876ebcfa4d3f
 - Page requested: /hhvm/
 - Page requested at: Tue, 03 Jul 2018 14:42:31 +0000
 - Controller: GuidesListController

**Comment by fredemmott** [comment]
#483
