### ISSUE TITLE
the overview link should not go to the typing page

### ISSUE THREAD

**Issue by seebs** [hhvm/user-documentation#534]
Please complete the information below:

# Where is the problem?

Clicked link on left side labeled "overview"

# What is the problem?

Got a description of something specific about "typing".

I was looking for "is Hack a programming language, a tool for programming, a philosophy, one of the roguelikes that was the ancestor of NetHack, or something else?"

I would suggest an actual *overview*, like "this is the kind-of-thing Hack is, here is where it fits in the field, here are the design goals that made it desireable to make this thing." With more detailed concepts like "typing" showing up later, after I have a context for them.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2018-05-22T20:33:05+0000:bb89df40dd6e5a8501362ce41535876ebcfa4d3f
 - Page requested: /hack/FAQ/faq
 - Page requested at: Thu, 05 Jul 2018 18:47:48 +0000
 - Controller: GuidePageController

**Comment by AndrewDiMola** [comment]
FAQ doesn't exist anymore but I added some helpful info in the Overview. More content lives within the home page of hacklang.org.

Added here: https://github.com/hhvm/user-documentation/commit/6cf71caddb9daf51582302928b28e0cdcf73fe17.
