### ISSUE TITLE
Edge Case with `HH\Lab\Math\abs(PHP_INT_MIN)`

### ISSUE THREAD

**Issue by RexJaeschke** [hhvm/user-documentation#541]
Consider the case of calling `abs` on the smallest-valued `int`. On a twos-complement system, this value **has no positive equivalent**, and the function returns **the exact same value**. Of course, a programmer would not ordinarily expect `abs` to return a negative value, but it does in this case. 

I just looked at the Java API specs, and it states: "Note that if the argument is equal to the value of Integer.MIN_VALUE, the most negative representable int value, the result is that same value, which is negative."

As the only other choice you have is to throw an exception (which is probably *not* done by other languages/libraries), at the very least, you should document this behavior, so the programmer can be forewarned.

**Comment by fredemmott** [comment]
Do you have a code example of this? It isn't what I'm seeing:

```
hphpd> =HH\Lib\Math\abs(PHP_INT_MIN)
=HH\Lib\Math\abs(PHP_INT_MIN)
9.2233720368548E+18
hphpd> =gettype(HH\Lib\Math\abs(PHP_INT_MIN))
=gettype(HH\Lib\Math\abs(PHP_INT_MIN))
"double"
hphpd> =HH\Lib\Math\abs(PHP_INT_MIN) === PHP_INT_MIN
=HH\Lib\Math\abs(PHP_INT_MIN) === PHP_INT_MIN
false
```

That said, silently converting to double should probably be explicitly documented

**Comment by RexJaeschke** [comment]
When I run the following:

[abs-test.php.txt](https://github.com/hhvm/user-documentation/files/2267298/abs-test.php.txt)

I get

$v = 1234.56
$v = -9223372036854775808
int(-9223372036854775808)

BTW, as I can't access HH\Lib from this server (we discussed this last week), I used the PHP constant version, but that still showed the issue.

**Comment by fredemmott** [comment]
Heh, we have incorrectly defined INT64_MIN:

hphpd> =HH\Lib\Math\INT64_MIN
=HH\Lib\Math\INT64_MIN
9.2233720368548E+18
hphpd> =HH\Lib\Math\INT64_MIN > 0
=HH\Lib\Math\INT64_MIN > 0
true

**Comment by fredemmott** [comment]
Also, please file an issue at https://github.com/hhvm/hsl/issues - this can't be fixed in the user-documentation repository, it needs fixing there
