### ISSUE TITLE
No results found for gen_map

### ISSUE THREAD

**Issue by Wilfred** [hhvm/user-documentation#542]
# Where is the problem?

Search page: Searching for aliases of functions defined at Facebook doesn't find any results.

# What is the problem?

https://docs.hhvm.com/search?term=gen_map shows zero results, even though https://docs.hhvm.com/hsl/reference/function/HH.Lib.Vec.map_async/ mentions that gen_map is an alias for map_async.

--------------------------------

 - Build ID: 2018-07-06T21:05:29+0000:0afe35d8f6fa936bb97d49ea0448dab4d6a1b159
 - Page requested: /search
 - Page requested at: Fri, 10 Aug 2018 23:37:26 +0000
 - Controller: SearchController

**Comment by AndrewDiMola** [comment]
@Wilfred - Looks like this isn't a supported alias anymore. Do you have another example?

**Comment by Wilfred** [comment]
Aha, we did indeed clean this up recently to use `map_async` internally too.

@fredemmott are you aware of any other internal aliases that the search should support? If not, I'll close this.

**Comment by fredemmott** [comment]
no - and we definitely have no more find-replace syncing between internal repositories and github.
