### ISSUE TITLE
Misinterpretation of names inside backticks

### ISSUE THREAD

**Issue by RexJaeschke** [hhvm/user-documentation#545]
a.	I have numerous occurrences of `null`. However, when these are rendered, they do *not* get set in constant-width font, as one would want/expect. Apparently, the rendering tool looks at the text inside `…` for names from the library, and when it finds one, if generates a link to that library function, set in orange and roman font, in this case, to HH\Asio\null, a generic library function. This is *not* correct! This may well be a special case, as `null` is both a language source element and the name of a library function, which is probably not true of most names.
b.	`main` is also redirected elsewhere when I’m just using it as an entry-point function name.
c.	`name` is redirected to “HH\Asio\name” when it’s just a local name.
d.	`m` is redirected to “HH\Asio\m” when it’s just a local name.

**Comment by Wilfred** [comment]
The `null` issue occurs on https://docs.hhvm.com/hack/XHP/methods too.

**Comment by Wilfred** [comment]
The same issue occurs with `int` and `string`, which point to `HH\Lib\SecureRandom\string`. I think this feature isn't worth keeping.

**Comment by fredemmott** [comment]
I think it needs tweaking:
- if it thinks it's a function reference, it should require `()` - e.g. `string` shouldn't link, but `string()` should
- short blacklist; if the previous point is done, `main` is the only one that immediately comes to mind

**Comment by Wilfred** [comment]
@fredemmott that's a really interesting heuristic. I don't think docs will generally use `()`, but using fully qualified names like `Vec\map` would really well.

Do you have an examples where it's working well today? I haven't spotted any prose taking advantage of this functionality.

**Comment by fredemmott** [comment]
It’s used pretty heavily and well by the API documentation generated from doc comments; it would also be possible to /only/ use it there

**Comment by AndrewDiMola** [comment]
`null` and `int` and `string` and others no longer auto-link. Closing.

![image](https://user-images.githubusercontent.com/5179225/109567505-7411f280-7ab3-11eb-9f68-df6809fa06b5.png)
