### ISSUE TITLE
Text with parentheses inside brackets is mishandled

### ISSUE THREAD

**Issue by RexJaeschke** [hhvm/user-documentation#547]
The following paragraph,

When called, function `is_leap_year` takes one argument, of type `int`, and returns a value of type `bool`. [A year is a leap year if it is a multiple of 4 but not a multiple of 100 (for example, 1700, 1800, and 1900 were *not* leap years), or it’s a multiple of 400. Some redundant grouping parentheses have been added to aid readability.]

Is rendered thus:

![parens-in-brackets](https://user-images.githubusercontent.com/6708936/44673013-505c2600-a9f8-11e8-942f-459037d5dd4e.JPG)
 
The text “leap years … have been” is missing.

**Comment by fredemmott** [comment]
I'm not able to reproduce this problem; can you either:
- create a pull request against this repository including the change to the file that shows this problem, in full context
- provide an example that can be reproduced by running `hhvm bin/docs-markdown.php` from the user-documentation/ directory? Paste in the text, then hit ctrl+d to get HTML output

**Comment by RexJaeschke** [comment]
Problem solved! The apostrophe in "it’s" was U+2019 while it needed to be U+0027. But since the tool doesn't warn about this (and the other non-7-bit ASCII chars I mentioned elsewhere), such "errors" might be hard to spot. Issue closed.
