### ISSUE TITLE
Suppressing the “Output” heading and following empty output

### ISSUE THREAD

**Issue by RexJaeschke** [hhvm/user-documentation#548]
I have some source code fragments that type-check, but do *not* contain a call to any entry-point function. They are not intended to produce output. However, these are executed, and a blank line is shown as the output after the heading “Output”. How can I suppress the empty-output stuff?

**Comment by fredemmott** [comment]
create an empty file ending with `.no.auto.output`

For example, `guides/hack/46-callables/01-introduction-examples/hack-callable-good.php` has `guides/hack/46-callables/01-introduction-examples/hack-callable-good.php.no.auto.output`

**Comment by RexJaeschke** [comment]
Thanks. For completeness, the .no.auto.output *replaces* the usual .hhvm.expect, so don't have the latter as well.
