### ISSUE TITLE
Too much emphasis when rendering `...`

### ISSUE THREAD

**Issue by RexJaeschke** [hhvm/user-documentation#550]
I find that rendering `xxx` as constant-width text to be quite enough to make it stand out. Coloring it as well is not only *unnecessary*, it can be quite distracting when you have a sentence containing a comma-separated list of language tokens, for example, where each token is in backticks and the separating commas are not. I urge you to switch off the coloring!

**Comment by AndrewDiMola** [comment]
This is probably most notable in a page like https://docs.hhvm.com/hack/source-code-fundamentals/keywords or in the attached picture, but I don't have any strong opinions about how it's rendered. If anyone else has feedback, feel free to comment in your thoughts below.

<img width="1288" alt="image" src="https://user-images.githubusercontent.com/5179225/160462902-1ccc5929-3681-4526-9d5a-f0f2f0e5b5b3.png">

**Comment by Wilfred** [comment]
Fixed in d1d2c1ad4cc14e76703ca34ef13584e53f05f2a4.
