### ISSUE TITLE
Links to headings in the same md file do not work

### ISSUE THREAD

**Issue by RexJaeschke** [hhvm/user-documentation#551]
For example:

## String Literals

A string literal can have one of the following forms:
* [single-quoted string](#single-quoted-string-literals)
…
### Single-Quoted String Literals

The link “#single-quoted-string-literals” is not resolved! I tried using relative and absolute path prefixes, but none worked. Am I missing something?

**Comment by fredemmott** [comment]
If you move the cursor over a heading, a link will appear on the right. You can copy the `#` part out of that.

**Comment by RexJaeschke** [comment]
Thanks. I found that while links of the form [...](#xxx) do correctly resolve to level-2 heading xxx, for level-3 headings one needs 

[...](#level-2-heading-name__level-3-heading-name)
