### ISSUE TITLE
Search for 'newtype' returns no results

### ISSUE THREAD

**Issue by talldean** [hhvm/user-documentation#552]
Please complete the information below:

# Where is the problem?

Searching for 'newtype' returns no results 

# What is the problem?

Searching for 'newtype' returns no results 

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2018-07-06T21:05:29+0000:0afe35d8f6fa936bb97d49ea0448dab4d6a1b159
 - Page requested: /hack/type-aliases/introduction
 - Page requested at: Thu, 30 Aug 2018 17:05:42 +0000
 - Controller: GuidePageController

**Comment by AndrewDiMola** [comment]
Closing because searching for `newtype` now leads to the correct page.

![image](https://user-images.githubusercontent.com/5179225/109566972-9eaf7b80-7ab2-11eb-8c58-544b57c9af80.png)
