### ISSUE TITLE
map

### ISSUE THREAD

**Issue by BrianLee608** [hhvm/user-documentation#555]
Please complete the information below:

# Where is the problem?

- - - eg "The section describing how widgets work" - - -

# What is the problem?

- - - eg "It doesn't explain that widgets are singletons" - - -

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2018-09-07T15:59:33+0000:2d5cae5649a1435f6e930b2b0db5698a9d470f2a
 - Page requested: /hsl/reference/
 - Page requested at: Wed, 03 Oct 2018 00:35:02 +0000
 - Controller: APIFullListController

**Comment by Wilfred** [comment]
@BrianLee608 what's the issue you're seeing?
