### ISSUE TITLE
Type Constants: Examples hh syntax error

### ISSUE THREAD

**Issue by sysout** [hhvm/user-documentation#557]
Please complete the information below:

# Where is the problem?
```hack
function get_id_from_userg<Tg as arraykey>(AppUserG $ug): Tg {
  return $ug->getID();
}
```

# What is the problem?
hh error:
The type Hack\UserDocumentation\TypeConstants\Exampes\Examples\Referencing\AppUserG expects 1 type parameter(s)

The correct one should be:
```hack
function get_id_from_userg<Tg as int>(AppUserG<Tg> $ug): Tg {
  return $ug->getID();
}
```

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2018-09-07T15:59:33+0000:2d5cae5649a1435f6e930b2b0db5698a9d470f2a
 - Page requested: /hack/type-constants/examples
 - Page requested at: Thu, 25 Oct 2018 17:12:37 +0000
 - Controller: GuidePageController

**Comment by fredemmott** [comment]
For my reference: the code is valid partial code, not strict. This should be changed to be valid strict code.

**Comment by Wilfred** [comment]
I've fixed the example. It'd be nice to make the whole file `<?hh // strict`, but it contains top-level statements.

**Comment by fredemmott** [comment]
That can be fixed with <<__Entrypoint>> now
