### ISSUE TITLE
MacOS support information is extremely out of date

### ISSUE THREAD

**Issue by fredemmott** [hhvm/user-documentation#560]
Please complete the information below:

# Where is the problem?

The first paragraph

# What is the problem?

It says that there is experimental MacOS 10.10 support; 10.10 is no longer supported. 10.12 and 10.13 are supported.

'Experimental' is probably good to remove too now, but it might be worth clarifying that it's only intendeded for development environements, not production use.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2018-11-05T23:07:00+0000:f4140cf04b7be2c2ede98a9313a9c19c1353d7f5
 - Page requested: /hhvm/installation/introduction
 - Page requested at: Tue, 13 Nov 2018 18:46:24 +0000
 - Controller: GuidePageController

**Comment by tedd4u** [comment]
Also consider updating https://docs.hhvm.com/hhvm/installation/mac where it says `This will install binary packages on recent versions of MacOS (as of 2017-11-08, this means Sierra and High Sierra).`
