### ISSUE TITLE
Broken link in WeakRef description

### ISSUE THREAD

**Issue by Wilfred** [hhvm/user-documentation#562]
The "excerpt from" line seems to have been split on the `.` of `php.net`.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2018-11-05T23:07:00+0000:f4140cf04b7be2c2ede98a9313a9c19c1353d7f5
 - Page requested: /hack/reference/class/WeakRef/
 - Page requested at: Fri, 16 Nov 2018 13:58:35 +0000
 - Controller: APIClassPageController

**Comment by AndrewDiMola** [comment]
Seems to have been fixed at some point. Can't replicate 404 in description.

https://docs.hhvm.com/hack/reference/class/WeakRef/
