### ISSUE TITLE
Document as expressions

### ISSUE THREAD

**Issue by muglug** [hhvm/user-documentation#566]
Couldn't find any documentation about `$a = ($b as Foo)->bar();`. Is this meant to throw an exception/type error when `$b` isn't a `Foo`?

**Comment by muglug** [comment]
Found it documented here: https://hhvm.com/blog/2018/08/28/hhvm-3.28.0.html#type-assertion

**Comment by Wilfred** [comment]
Yep, that's correct.

We've done a big overhaul of the docs to ensure we cover all the features of the type system. It's not deployed to the site yet, but you can read the description of `as` here: https://github.com/hhvm/user-documentation/blob/rex-docs/guides/hack/04-expressions-and-operators/57-as.md

**Comment by muglug** [comment]
Great - happy for this to be closed
