### ISSUE TITLE
__MemoizeLSB not found in Search?

### ISSUE THREAD

**Issue by talldean** [hhvm/user-documentation#584]
Please complete the information below:

# Where is the problem?

What's __MemoizeLSB?

I've found how to *clear* lsb memoization so far.

# What is the problem?

Searching for __MemoizeLSB or MemoizeLSB, both return nothing.

If you can clear lsb memoization, there should be some page explaining what it is.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2019-02-14T15:43:02+0000:295af88d1de39887aa1dab1972d18d2d4a460f14
 - Page requested: /hack/reference/function/HH.clear_lsb_memoization/
 - Page requested at: Fri, 08 Mar 2019 20:16:28 +0000
 - Controller: APIClassPageController

**Comment by fredemmott** [comment]
Fixed on staging.docs.hhvm.com, which should go live on Monday.
