### ISSUE TITLE
":" is a valid start of a name (for xhp classes)

### ISSUE THREAD

**Issue by lexidor** [hhvm/user-documentation#591]
Please complete the information below:

# Where is the problem?

http://staging.docs.hhvm.com/hack/source-code-fundamentals/names @ 1st paragraph

# What is the problem?
This page states that names must start with a word character, but certain names may start with a colon (xhp classes). This may however be intentional.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2019-03-08T20:07:04+0000:dc3e7ed5d57714a7e83c2aedbb04c60b26bab415
 - Page requested: /hack/source-code-fundamentals/names
 - Page requested at: Fri, 08 Mar 2019 23:52:05 +0000
 - Controller: GuidePageController

**Comment by lexidor** [comment]
`xhp class` is a new (almost) released alternative, closing.

**Comment by fredemmott** [comment]
FYI we're not planning on enabling `xhp class` until the XHP namespace support as a whole is usable; there's a PR up, but it's going to take a while to review and to gain enough confidence in it to flip the default
