### ISSUE TITLE
Tables use right-aligned text at small screen widths

### ISSUE THREAD

**Issue by lexidor** [hhvm/user-documentation#592]
Please complete the information below:

# Where is the problem?

http://staging.docs.hhvm.com/hack/source-code-fundamentals/constants @ Context dependent constants

# What is the problem?

On mobile the amount of whitespace between "DESCRIPTION" and the type is inconsistent. In _real_ browsers, the name of the constant and the type are in two different columns, resolving the issue.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2019-03-08T20:07:04+0000:dc3e7ed5d57714a7e83c2aedbb04c60b26bab415
 - Page requested: /hack/source-code-fundamentals/constants
 - Page requested at: Fri, 08 Mar 2019 23:52:33 +0000
 - Controller: GuidePageController

**Comment by Wilfred** [comment]
![Screenshot 2020-01-28 at 11 54 13](https://user-images.githubusercontent.com/70800/73261915-f64f2980-41c4-11ea-819b-3c34ce751591.png)

**Comment by lexidor** [comment]
This is a far better issue. Adding the screenshot makes me remember why I made the issue in the first place.
