### ISSUE TITLE
"$$" links

### ISSUE THREAD

**Issue by lexidor** [hhvm/user-documentation#594]
Please complete the information below:

# Where is the problem?

http://staging.docs.hhvm.com/hack/source-code-fundamentals/namespaces 

# What is the problem?

This page uses the dollardollar token to refer to linked articles. This is not a isolated case.

Example: 

See $$ for an example involving two class types, each defined in its own namespace, used by an application in a third namespace.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2019-03-08T20:07:04+0000:dc3e7ed5d57714a7e83c2aedbb04c60b26bab415
 - Page requested: /hack/source-code-fundamentals/namespaces
 - Page requested at: Fri, 08 Mar 2019 23:53:33 +0000
 - Controller: GuidePageController

**Comment by Wilfred** [comment]
I have no idea how this happened. I don't know if `$$` had some special meaning at some point. Any ideas @fredemmott?

**Comment by fredemmott** [comment]
I think this was just a placeholder, meant for a manual find/replace later (which didn't happen), so they wouldn't need updating if the page titles changed.
