### ISSUE TITLE
Usage of \is_null in example

### ISSUE THREAD

**Issue by lexidor** [hhvm/user-documentation#599]
Please complete the information below:

# Where is the problem?

namespace Hack\UserDocumentation\Types\TypeRefinement\Examples\Test2;

# What is the problem?

The documentation shows the use of a type query function. Afaik, that was being phased out. Suggested to use null identity comparison or is-refinement using the int or nonnull type.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2019-03-08T20:07:04+0000:dc3e7ed5d57714a7e83c2aedbb04c60b26bab415
 - Page requested: /hack/types/type-refinement
 - Page requested at: Sat, 09 Mar 2019 16:01:05 +0000
 - Controller: GuidePageController

**Comment by fredemmott** [comment]
Leaving this for a little bit - we also should have the `null` type enabled soon

**Comment by Lexidor** [comment]
Null type hype. I had a function called array_fill_nulls in a library somewhere. I typed it as varray<?Nothing> where nothing was an empty interface Sealed to noone.
