### ISSUE TITLE
Document alternative ways to run the typechecker

### ISSUE THREAD

**Issue by fredemmott** [hhvm/user-documentation#6]
eg:
 - `hh_single_typecheck`: almost certainly not what you want
 - `hh_server --check`: not for every day usage, but good for automated tests, commit hooks, etc

**Comment by JoelMarcey** [comment]
I am. I have a whole section on other tools that these will be documented in.

**Comment by fredemmott** [comment]
:like:

**Comment by jwatzman** [comment]
Actually please don't document hh_single at all, it's for internal unit testing, and we don't even ship it in our debs.

**Comment by fredemmott** [comment]
A few people have came across it and used it incorrectly (eg 3v4l nearly used it) - it could be worth just a sentence saying "this is an incomplete version and only suitable for Hacks' own unit tests" or similar

**Comment by JoelMarcey** [comment]
https://github.com/hhvm/user-documentation/tree/master/guides/hack/17-tools

If someone files an issue about `hh_single_typecheck`, I will add that sentence -- but I won't call attention to it now.
