### ISSUE TITLE
"write your first hack program" refers to php docs `main` dummy page

### ISSUE THREAD

**Issue by jakemco** [hhvm/user-documentation#603]
Please complete the information below:

# Where is the problem?

https://docs.hhvm.com/hack/getting-started/getting-started#your-first-hack-program__3.-write-your-first-hack-program

# What is the problem?

linking to `main` in php docs, which points to a useless dummy doc. 

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2019-03-11T17:31:47+0000:f6f216d5748ce7012a09735d1b1c2cff1dd807d3
 - Page requested: /hack/getting-started/getting-started
 - Page requested at: Mon, 11 Mar 2019 18:09:00 +0000
 - Controller: GuidePageController

**Comment by jakemco** [comment]
Also, just noticed on https://docs.hhvm.com/hack/getting-started/starting-a-real-project:

"The <<__EntryPoint>> annotation marks this function as the point where execution starts - there is nothing special about the function name main." 

^ that should be included in the bullet point about `__EntryPoint` and `main` on the "write your first hack program" page

**Comment by fredemmott** [comment]
We should probably just completely remove the autolinking to PHP functions in all contexts

**Comment by AndrewDiMola** [comment]
Fixed in https://github.com/hhvm/user-documentation/commit/1f369fe104f52d5988e0c205b661bd3207979260. In addition, autolinking is no longer a concern.
