### ISSUE TITLE
"first hack program" references echo, which isn't used.

### ISSUE THREAD

**Issue by jakemco** [hhvm/user-documentation#604]
Please complete the information below:

# Where is the problem?

https://docs.hhvm.com/hack/getting-started/getting-started#your-first-hack-program__3.-write-your-first-hack-program

# What is the problem?

there's a bullet point explaining echo before printf, but there's no echo in the example program.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2019-03-11T17:31:47+0000:f6f216d5748ce7012a09735d1b1c2cff1dd807d3
 - Page requested: /hack/getting-started/getting-started
 - Page requested at: Mon, 11 Mar 2019 18:09:00 +0000
 - Controller: GuidePageController

**Comment by Wilfred** [comment]
I can see an `echo` there:

```
namespace Hack\GettingStarted\MyFirstProgram;

<<__EntryPoint>>
function main(): void {
  echo "Welcome to Hack!\n\n"; // <-----

  \printf("Table of Squares\n" .
          "----------------\n");
  for ($i = -5; $i <= 5; ++$i) {
    \printf("  %2d        %2d  \n", $i, $i * $i);
  }
  \printf("----------------\n");
}
```

Do keep creating tasks if you spot issues :)
