### ISSUE TITLE
Standardize heading in markdown

### ISSUE THREAD

**Issue by fredemmott** [hhvm/user-documentation#62]
My ideal: every file has `#` as the top level heading. If given it's context it should be an `h2` instead, this can be handled in the markdown renderer. This means that we can change generic structure of the page without having to rewrite all the docs.

**Comment by fredemmott** [comment]
cc @JoelMarcey @matthewjohnston4 - continuation of discussion from #61

**Comment by fredemmott** [comment]
Relatedly, the 'pageTitle' heading really shouldn't be an <h2>

**Comment by matthewjohnston4** [comment]
So - I definitely agree, whatever is the primary title **must be** an `<h1>` - the question is, which of these options do we want to proceed with:

1. Remove [this](https://github.com/hhvm/user-documentation/blob/master/src/site/WebPageController.php#L80) and rely entirely upon Markdown content for titling
2. Downgrade all Markdown content titles to h2 and below manually (or with a grep replace), and upgrade [the pageTitle](https://github.com/hhvm/user-documentation/blob/master/src/site/WebPageController.php#L80) to h1
3. As above but do the downgrading in the md-render.rb stage automatically.
4. Upgrade [pageTitle](https://github.com/hhvm/user-documentation/blob/master/src/site/WebPageController.php#L80) to an h1, and leave Markdown content as-is, potentially having two h1s on the same page.

**Comment by fredemmott** [comment]
1. I kind-of dislike this: do we have cases where the markdown title should be different to the automatic one? If so, which/why? Also, keeping it is good for consistency with the non-markdown pages. I don't feel strongly though
2. Dislike because it ties static content to how it happens to be embedded
3. LIke.
4. Dislike because inconsistency

Also, we can temporarily re-normalize all headings in the renderer, though I'd rather have the source files fixed long-term - eg if headings are h1...hn change them to h2...hn+1, but if they're already h2...hn leave them alone. Really don't want that to be the long-term state though.

**Comment by JoelMarcey** [comment]
I actually I am unclear as to what the real problem is here.... is it that these two things end up having the same heading format `<h1>` in HTML.

![screenshot 2015-11-13 14 01 00](https://cloud.githubusercontent.com/assets/3757713/11158742/11abe258-8a0f-11e5-967c-c3922ed1ab41.png)

What I really want to be able to do, and what I did do with most of the guides is 

```
# Major Title

## Topic

## Topic

### Subtopic

## Topic

### Subtopic

*Italicized* (if we needed a 4th thing)
```

I tried to avoid 4 levels as best I as I could.

If you remember, before, I didn't have the top `#` heading at all in the markdown, but we decided to put one there so that each page had a top-level title even beyond it's page title.

If we keep things the way they are, then we have the renderer take care of things; Otherwise, I could probably relatively easily do a search and replace for `#` to `##`, etc.

**Comment by fredemmott** [comment]
Problems:

# Two page titles

why do we want both a page title and... erm, a content title? Shouldn't these be the same things?

# Page title is an h2

 - the page title is the top level heading, it really should be an h1
 - this means that we have an h2 with no h1 on non-markdown pages (eg the reference index pages)
 - also weird that the page title is currently an h2 but the content title is an h1 -the content is inside the page, so should be a lower level heading 

# Markdown needs to be aware of the context it's rendered in

 - 'cleanliness'
 - need to modify all the markdowns if we change the structure

# Consistency

I think we currently have a mix of top-level h1 and h2 in the md

**Comment by JoelMarcey** [comment]
:/ That's the way I had it before, I believe. I only had `##` and below. And used the page title (`Types: Type System`) as the main page title. But I know we had a discussion to had a `#` in each of the markdown files.

Should we just remove all the `#` headings then. We can go right into text and use the page tiles as the new top level.

**Comment by fredemmott** [comment]
I think because of the third point that the top-most heading in a markdown file should be `#`:

 - if we keep page titles in the markdown, yep. Section headings are `##`
 - if we don't keep page titles in the markdown, then skipping a level of heading violates 3.
