### ISSUE TITLE
Page for "constructor parameter promotion" got removed

### ISSUE THREAD

**Issue by kunigami** [hhvm/user-documentation#620]
Please complete the information below:

# Where is the problem?

The page was here
https://docs.hhvm.com/hack/other-features/constructor-parameter-promotion/

# What is the problem?

The page does not exist anymore. Searching for "constructor-parameter-promotion hack" doesn't yield any useful results.

If we renamed the concept, we should at least keep the old url for redirection / back-compatibility.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2019-03-15T20:34:09+0000:361688e6c740dea5615800d530efcf4090ad0b4c
 - Page requested: /hack/classes/constructors
 - Page requested at: Wed, 27 Mar 2019 21:21:17 +0000
 - Controller: GuidePageController

**Comment by fredemmott** [comment]
This content was rewritten in b35740d55a829e4fc0471fdbd96b148f350fdc82 , and a redirect was added in e245250ec

The redirect works, but not with the trailing / ; sorry, I can't see in history when/if those were supported

**Comment by fredemmott** [comment]
most likely bc35dcbc475002e719c4e5b3a76a5369d43dc7f2
