### ISSUE TITLE
`is` has a higher operator precedence than `!`

### ISSUE THREAD

**Issue by Kilenaitor** [hhvm/user-documentation#625]
Please complete the information below:

# Where is the problem?

https://docs.hhvm.com/hack/expressions-and-operators/operator-precedence

# What is the problem?

The row with 
`instanceof` `is` `as` `?as`

is flipped with the row containing
`!` `~` `+` `-` `++` `--` `(type)` `@` `await`

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2019-03-28T20:35:01+0000:ad1b205f883d45390bd899cf4b713efd1b932fb0
 - Page requested: /hack/expressions-and-operators/operator-precedence
 - Page requested at: Fri, 29 Mar 2019 20:53:00 +0000
 - Controller: GuidePageController

**Comment by Wilfred** [comment]
Well spotted! Thanks :)
