### ISSUE TITLE
Probably easy - Page links to a wiki that mentions zend compat layer.

### ISSUE THREAD

**Issue by lexidor** [hhvm/user-documentation#626]
Please complete the information below:

# Where is the problem?
This link appears at the bottom of this page:
https://github.com/facebook/hhvm/wiki/Extension-API

It might be removed or altered, because of
https://github.com/facebook/hhvm/issues/8475 

# What is the problem?
Ensure that this process does not cause an HTTP404 "Not Found"

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2019-03-28T20:35:01+0000:ad1b205f883d45390bd899cf4b713efd1b932fb0
 - Page requested: /hhvm/extensions/introduction
 - Page requested at: Mon, 01 Apr 2019 17:36:47 +0000
 - Controller: GuidePageController

**Comment by AndrewDiMola** [comment]
Removed in https://github.com/hhvm/user-documentation/commit/fc7a85af17bb065d9eb179ea268d7714fed362fb. Will tackle removal and repurposing of the entire Wiki in a separate issue (https://github.com/facebook/hhvm/issues/8564).
