### ISSUE TITLE
Document HH_FIXME and HH_IGNORE_ERROR

### ISSUE THREAD

**Issue by Wilfred** [hhvm/user-documentation#635]
These belong in 10-comments.md.

**Comment by Wilfred** [comment]
`// FALLTHROUGH` too.

**Comment by fredemmott** [comment]
// UNSAFE and // UNSAFE_EXPR are now dead

**Comment by Wilfred** [comment]
Done in 8851baa2fc79bc4d2ebf62eb0a4784e5e81572bb.
