### ISSUE TITLE
Location of install_fastcgi.sh in page /advanced-usage/fastCGI

### ISSUE THREAD

**Issue by zoltanka** [hhvm/user-documentation#638]
# Where is the problem?

**Page:** https://docs.hhvm.com/hhvm/advanced-usage/fastCGI
Under section **Making it work with nginx**, 3rd paragraph:

> Our included script sudo /usr/share/hhvm/install_fastcgi.sh will configure nginx correctly for stock installs.

**OS:**
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

**HHVM:**
HipHop VM 4.3.0 (rel)
Compiler: 1556643683_468196908
Repo schema: d30aecab0cfaaaab471c9cbc4eac9ae52f26ab6f

# What is the problem?

The file is not located there. Its here: /opt/hhvm/4.3.0/share/hhvm/install_fastcgi.sh

--------------------------------

 - Build ID: 2019-03-28T20:35:01+0000:ad1b205f883d45390bd899cf4b713efd1b932fb0
 - Page requested: /hhvm/advanced-usage/fastCGI
 - Page requested at: Wed, 01 May 2019 13:06:49 +0000
 - Controller: GuidePageController

**Comment by Wilfred** [comment]
Fixed in #639.
