### ISSUE TITLE
No documentation about enum functions (::assert and ::coerce etc)

### ISSUE THREAD

**Issue by Ambroos** [hhvm/user-documentation#648]
Please complete the information below:

# Where is the problem?

https://docs.hhvm.com/hack/types/enumerated-types

# What is the problem?

There is no mention of any of the enum functions on the enum page, or anywhere else in the docs. Content from https://github.com/hhvm/hack-langspec/blob/master/spec/13-enums.md#the-predefined-enumerated-type-methods might be interesting to reuse.

This documentation used to exist (still shows up in `bunny s enum assert`, first result).

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2019-05-07T20:37:42+0000:9e9731fda3c705fc7f2980868c1e6269f23b46d0
 - Page requested: /hack/types/enumerated-types
 - Page requested at: Wed, 08 May 2019 23:34:26 +0000
 - Controller: GuidePageController

**Comment by bar** [comment]
I came looking for this too, it appears that the HHVM maintainers don't want us to use `assert/coerce` anymore?

I was told by a coworker `as` and `?as` are the goto replacements, it might be a good idea if they explicitly state it though.
