### ISSUE TITLE
k

### ISSUE THREAD

**Issue by huy1994** [hhvm/user-documentation#654]
Please complete the information below:

# Where is the problem?

- - - eg "The section describing how widgets work" - - -

# What is the problem?

- - - eg "It doesn't explain that widgets are singletons" - - -

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2019-05-28T22:37:20+0000:e6ba9ed33791280f7644492c0719a6f2d31c7dcf
 - Page requested: /hhvm/installation/mac
 - Page requested at: Thu, 30 May 2019 19:45:25 +0000
 - Controller: GuidePageController

**Comment by Lexidor** [comment]
Probably just a misclick
