### ISSUE TITLE
Many links to extensions are 404ing

### ISSUE THREAD

**Issue by Wilfred** [hhvm/user-documentation#660]
# Where is the problem?

https://docs.hhvm.com/hhvm/extensions/introduction

# What is the problem?

Many of the links 404:

* https://php.net/manual/en/book.date.php
* https://php.net/manual/en/book.string.php

Although some URLs in this format still exist:

* https://php.net/manual/en/book.json.php

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2019-06-03T22:19:27+0000:ea4d91f0608b91b0cfc872e9ef90850af279685e
 - Page requested: /hhvm/extensions/introduction
 - Page requested at: Tue, 04 Jun 2019 09:24:37 +0000
 - Controller: GuidePageController

**Comment by AndrewDiMola** [comment]
Fixed in https://github.com/hhvm/user-documentation/commit/974e880576a8f3f664e382ed46cfd1fd118e0dc1
