### ISSUE TITLE
404: /hack/types/arrays

### ISSUE THREAD

**Issue by NathanielOstrer** [hhvm/user-documentation#669]
Please complete the information below:

# How I got to this page:

Googled "hack arrays"
clicked the first link

# What I expected to find here:

Documentation on Hack arrays.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.10.0:HSL=v4.7.0:2019-06-20T21:30:09+0000:0b6948a2e325fbe4e557e321b9da410999942899
 - Page requested: /hack/types/arrays
 - Page requested at: Fri, 21 Jun 2019 18:45:43 +0000

**Comment by Wilfred** [comment]
Fixed in ab82c2523285454ad00d6bafbdfaa8ba0e80dbf0, should go out in the next deploy.
