### ISSUE TITLE
404: /hack/types/arrays

### ISSUE THREAD

**Issue by zmagg** [hhvm/user-documentation#670]
Please complete the information below:

# How I got to this page:

https://docs.hhvm.com/hack/types/arrays which is linked to from the documentation, as well as the main google search hit for "Hack arrays" 404s. 

# What I expected to find here:

There used to be a page that went through dict/keyset/vecs and how they're different than PHP arrays. 
--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.10.0:HSL=v4.7.0:2019-06-20T21:30:09+0000:0b6948a2e325fbe4e557e321b9da410999942899
 - Page requested: /hack/types/arrays
 - Page requested at: Sun, 23 Jun 2019 19:47:58 +0000

**Comment by Wilfred** [comment]
Fixed in ab82c2523285454ad00d6bafbdfaa8ba0e80dbf0, awaiting deploy.
