### ISSUE TITLE
Link points to same page.

### ISSUE THREAD

**Issue by anarelion** [hhvm/user-documentation#671]
Please complete the information below:

# Where is the problem?

The link at the end pointing to the generic types overview

# What is the problem?

It links to this page.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.10.0:HSL=v4.7.0:2019-06-20T21:30:09+0000:0b6948a2e325fbe4e557e321b9da410999942899
 - Page requested: /hack/types/generic-types
 - Page requested at: Mon, 24 Jun 2019 08:55:48 +0000
 - Controller: GuidePageController

**Comment by Wilfred** [comment]
I can't reproduce this: https://docs.hhvm.com/hack/types/generic-types links to https://docs.hhvm.com/hack/generics/introduction at the bottom, which exists and doesn't redirect.

Happy to reopen if this is still occurring.
