### ISSUE TITLE
Tuple docs are wrong for runtime semantics

### ISSUE THREAD

**Issue by Wilfred** [hhvm/user-documentation#684]
>  The number of elements in a particular tuple is fixed when that tuple is created. After a tuple has been created, no elements can be added or removed, and the type of an existing element cannot be changed. However, the value of any element can be changed.

This is wrong: tuples are copy-on-write, and you can write arbitrary typed values to them (the type of the result changes).

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.14.0:HSL=v4.7.0:2019-07-18T01:19:24+0000:16fa8e099afb8a848c52d0f0302540d7b92020df
 - Page requested: /hack/built-in-types/tuples
 - Page requested at: Thu, 18 Jul 2019 12:52:46 +0000
 - Controller: GuidePageController

**Comment by lexidor** [comment]
@Lexidor self assigned this issue

**Comment by fredemmott** [comment]
@lexidor did #685 fully address this?

**Comment by lexidor** [comment]
- [x] tuples are copy-on-write

- [x] you can write arbitrary typed values

- [x] the type of the result changes

@fredemmott All three mentioned points were addressed.
