### ISSUE TITLE
Wrong example

### ISSUE THREAD

**Issue by mnosseir** [hhvm/user-documentation#715]
Please complete the information below:

# Where is the problem?

The first example in the page.

# What is the problem?

The example shows bitwise OR instead of bitwise XOR.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.16.1:HSL=v4.7.0:2019-08-16T01:13:02+0000:e8c6b2e387dd5d68bd1d49c0d3d52dd171d628a8
 - Page requested: /hack/expressions-and-operators/bitwise-exclusive-OR
 - Page requested at: Sat, 17 Aug 2019 00:00:57 +0000
 - Controller: GuidePageController

**Comment by AndrewDiMola** [comment]
Fixed in https://github.com/hhvm/user-documentation/commit/56c05b97f389d249cbf94425370b516e124acb2f.
