### ISSUE TITLE
Hack Tutorial link is broken

### ISSUE THREAD

**Issue by Fwep** [hhvm/user-documentation#719]
Please complete the information below:

# Where is the problem?

https://docs.hhvm.com/hhvm/getting-started/getting-started, under **Learning Hack and PHP**

# What is the problem?

Link is broken, despite [#512 ](#512) being closed.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.22.0:HSL=v4.15.2:2019-09-09T22:08:37+0000:51a957e0f0b944a40821d6e99c0dd0e9ac3eb056
 - Page requested: /hhvm/getting-started/getting-started
 - Page requested at: Tue, 10 Sep 2019 20:44:00 +0000
 - Controller: GuidePageController

**Comment by jjergus** [comment]
Thanks for reporting!

It looks like the toturial is no longer available: https://github.com/hhvm/hacklang.org/commit/999e7b56276aaeb045dc0d94dee4e430006c3965

I'll remove the links.
