### ISSUE TITLE
Typos in code block

### ISSUE THREAD

**Issue by Fwep** [hhvm/user-documentation#722]
Please complete the information below:

# Where is the problem?

In the declaration of instance properties underneath the class declaration, and in the parameter list of the constructor.

# What is the problem?

The private properties are **described** as having type _float_ when in fact they are type _int_ in the code block. The constructor parameter arguments are described as being of type _num_ when they are in fact type _int_ in the code block.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.22.0:HSL=v4.15.2:2019-09-11T21:37:07+0000:9a8116a87fc236b96bac1d4cb61af26e43b8ba9b
 - Page requested: /hack/classes/constructors
 - Page requested at: Thu, 12 Sep 2019 22:30:56 +0000
 - Controller: GuidePageController

**Comment by jjergus** [comment]
Thanks for reporting!

But I think this one is actually correct. The text talks about the `Point` class from the first example, which has the types as described.

I moved that part of the text into a separate paragraph and highlighted the `Point` class name to make that clearer, hopefully it's easier to understand now.
