### ISSUE TITLE
Add more examples to coalesce operator documentation

### ISSUE THREAD

**Issue by cmcginty** [hhvm/user-documentation#728]
Please complete the information below:

# Where is the problem?

Details of using coalesce operator. Not enough examples.

# What is the problem?

It does not explain usages with index lookups. I've had to explain multiple times (to other FB co-workers) how this works and usage patterns. Specifically how it compares to `idx()`.  It would save a lot of time If I there was accurate documentation that removed all doubt about how it works. Thank you.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.23.0:HSL=v4.15.2:2019-09-20T21:41:50+0000:138dd8d9d3c423f9864bf5952632efca10d6696c
 - Page requested: /hack/expressions-and-operators/coalesce
 - Page requested at: Tue, 24 Sep 2019 20:13:13 +0000
 - Controller: GuidePageController

**Comment by fredemmott** [comment]
Could you give some examples of situations you would like to see included?

**Comment by jjergus** [comment]
> It does not explain usages with index lookups.

I don't understand -- all 3 examples on the page are index lookups, covering the 3 possible cases (non-null value, null value, undefined index).

> Specifically how it compares to idx()

I don't think `idx()` exists outside of Facebook, so that comparison probably wouldn't make sense in the public documentation :(

**Comment by fredemmott** [comment]
`idx()` is public, autoimported from `HH\idx()`

**Comment by jjergus** [comment]
Oh OK, in that case that's probably a reasonable request. Am I correct that `??` replaces `idx` in all cases and `idx` should never be used, or are there still cases where `idx` is needed?

**Comment by fredemmott** [comment]
Probalby worth checking with others, but I'm not aware of cases where idx is preferred

**Comment by jjergus** [comment]
We could also maybe do a migration from `idx()` to `??` (both at Facebook and in the public HHAST) and then kill `idx()`, to avoid any confusion in the future.

**Comment by jjergus** [comment]
#729 adds comparison with idx (turns out there is at least one case where idx might still be useful), and also a section about ??=

Let me know what else to add.
