### ISSUE TITLE
Add examples for all the methods in the Collections API

### ISSUE THREAD

**Issue by JoelMarcey** [hhvm/user-documentation#73]

**Comment by daviddoran** [comment]
@JoelMarcey did you have a plan of attack in mind? Other than auto-generating the skeletons and filling out each method example manually?

**Comment by JoelMarcey** [comment]
@daviddoran So, I figured I would start with an overall Collections example that would live in the top level class information (e.g., http://beta.docs.hhvm.com/hack/reference/class/Vector/). Then, I would basically just surgically go through the API and add examples for each method -- starting with the ones that I think are probably more heavily used.

My theory is that once you have one class done, like `Vector`, you can utilize the same examples with some modifications for the other collection classes.

**Comment by JoelMarcey** [comment]
Although, I need to verify we have the machinery for the overall Collection example that could land somewhere like http://beta.docs.hhvm.com/hack/reference/class/Vector/.

**Comment by JoelMarcey** [comment]
@daviddoran Did you want to take a stab at more of the collections examples? I imagine if we can get through `Vector`, `Map` especially should fall into place, and probably the other two as well.

I was planning on starting on #74 anyway. 

No worries if not, I will get to them at some point :)

**Comment by daviddoran** [comment]
@JoelMarcey Yeah I can try and get `Vector` done in one block. I realised after doing a few that going one-by-one (with screenshots in the PR, etc) is too slow. So if I find time I'll sit down and try and knock out a bunch of examples in one PR this week.

**PS: If someone else decides to do this instead just comment here so we're not doubling our effort.**

**Comment by JoelMarcey** [comment]
That's great :+1: 

I won't work on collections -- I will work on some other issues. Just let me know if you need some help or need me to take over due to time, etc.

**Comment by JoelMarcey** [comment]
\o/

:+1: 

Thanks @daviddoran 

This issue is closable I think. You?

**Comment by daviddoran** [comment]
@JoelMarcey Yup, except for the `Imm*` variants. Should I run a script to generate markdown files for the immutable collections, e.g. "See [`Set::blahMethod`](#examples) for example usage"?

**Comment by JoelMarcey** [comment]
@daviddoran Yeah, that would be great. I don't think we need to duplicate examples for the `ImmXXX` classes (at least initially). If there is pushback when we launch, we can just copy the current `XXX` examples for methods that exist on `ImmXXX` and pretty much change the code to `ImmXXX`.

**Comment by sgolemon** [comment]
Bear in mind that the mutable collections are actually a slight superset of the immutable ones.  ->reserve() for example, will only be found on mutable variants.

**Comment by daviddoran** [comment]
@sgolemon Yeah I just generated placeholders for the methods that exist on `Imm*` (so they link to their counterparts in mutable `Vector`/`Set` etc).

@JoelMarcey I've generated the placeholder preambles for `ImmVector`, `ImmSet` and `ImmMap` so I'll close this out now :)

- f458be242c752c4f2d7d755d1a34d1dba8881476 was needed to make the heading IDs sane so I could link to them
- 6483e9dd0bf82ca2c7dba791c0c33b659e36bf9b was needed to make it possible to have examples with only preamble (Markdown) and no PHP code
- 891c791894d3ef449726d5be2c96cd083a2eb669, 5759d1d430a06fadf9b853857fd5fbb869778662 and a9bc8b2ecc0545913e9f57a6f4c4d6c61f25f208 added the preamble content linking from `Imm*` to the mutable API examples
