### ISSUE TITLE
HH\Lib\Ref has strange typo

### ISSUE THREAD

**Issue by ryangreenberg** [hhvm/user-documentation#731]
At https://docs.hhvm.com/hsl/reference/class/HH.Lib.Ref:

> In eralAsync, it's preferable to refactor to use return values or inout parameters instead of using this class - however, a Ref of a Hack array is generally preferable to a Hack collection - e.g. prefer Ref<vec<T>> over Vector<T>.

"In general" was likely intended?

**Comment by jjergus** [comment]
It's a hilarious bug, I'll fix it as soon as I stop laughing.

We have a different naming convention for async functions internally (genSomething vs somethingAsync) and there's some code that translates between those conventions when internal code is shipped to GitHub.

**Comment by jjergus** [comment]
https://github.com/facebook/fbshipit/pull/80

**Comment by jjergus** [comment]
https://github.com/hhvm/hsl/commit/299ec88a75c7b7de4087218108dbf4815a535eac fixes this.

We'll need to tag a new HSL release (probably not worth doing just for this), so it might be a while longer before the fix is reflected on docs.hhvm.com
