### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Fwep** [hhvm/user-documentation#737]
Please complete the information below:

# Where is the problem?

https://docs.hhvm.com/hack/types/nullable-types

# What is the problem?

The last line

>This allows null to be passed explicitly (or implicitly of the second argument is omitted) to indicate the default behavior should be used:

should read

>This allows null to be passed explicitly (or implicitly if the second argument is omitted) to indicate the default behavior should be used:

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.25.0:HSL=v4.15.2:2019-10-07T23:29:02+0000:c118b76b199117aab2681ec0b752ae5739343f09
 - Page requested: /hack/types/nullable-types
 - Page requested at: Thu, 10 Oct 2019 00:40:33 +0000
 - Controller: GuidePageController

**Comment by jjergus** [comment]
Took me a while to spot the difference :)

Anyway thanks for reporting all these!
