### ISSUE TITLE
The "Function static" link does not link to anything

### ISSUE THREAD

**Issue by jawwad** [hhvm/user-documentation#738]
Please complete the information below:

# Where is the problem?

1. "Function static" link at the top of the page
2. "function static" link in the phrase "Unlike the equivalent function static version"

# What is the problem?

In "Unlike the equivalent function static version" the phrase "function static" is a link but does not link to anything. There is also a "Function static" link at the top of the page.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.25.0:HSL=v4.15.2:2019-10-10T21:18:26+0000:09519b35f78a8075eb2a4e5c99280aad60f20cff
 - Page requested: /hack/source-code-fundamentals/variables
 - Page requested at: Mon, 14 Oct 2019 16:43:24 +0000
 - Controller: GuidePageController

**Comment by jjergus** [comment]
Good catch! Function static variables were removed from the language a few months ago, looks like we didn't properly clean up the documentation.

**Comment by jawwad** [comment]
Thanks @jjergus -  Appreciate the quick fix!
