### ISSUE TITLE
Add examples for all the asio functions

### ISSUE THREAD

**Issue by JoelMarcey** [hhvm/user-documentation#74]
e.g., `v()`, `m()`, etc.

**Comment by JoelMarcey** [comment]
@fredemmott It makes sense to write these examples in the context of the functions being moved into HHVM, as opposed to `asio-utilities`, right ... even though, they haven't made it into an HHVM external point release yet (3.10 is current; they will be in 3.11) ?

**Comment by fredemmott** [comment]
Yep.

**Comment by JoelMarcey** [comment]
\o/

:+1:
