### ISSUE TITLE
HHVM 4+ does not support PHP: /usr/bin/composer

### ISSUE THREAD

**Issue by MaximilianClemens** [hhvm/user-documentation#740]
# Where is the problem?
$ hhvm $(which composer) install;
Fatal error: HHVM 4+ does not support PHP: /usr/bin/composer
AND
composer install
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Installation request for facebook/xhp-lib ~2.10.2 -> satisfiable by facebook/xhp-lib[2.10.2].
    - facebook/xhp-lib 2.10.2 requires hhvm ^4.13.0 -> you are running this with PHP and not HHVM.

# What is the problem?

May I'm too stupid to unterstand but I want to install th xhp_lib.
So I created the composer.json and called composer over hhvm => hhvm does not support php, so I called composer => you are running php not hhvm??

How to install xhp_lib, if composer is not supported any more?

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.28.0:HSL=v4.25.0:2019-10-21T22:24:47+0000:f610a10d3a3cd0ed9b4c312aba7a9bb319d10573
 - Page requested: /hack/XHP/some-basics
 - Page requested at: Tue, 22 Oct 2019 19:28:47 +0000
 - Controller: GuidePageController

**Comment by fredemmott** [comment]
The instructions are outdated, use `composer install` or `php $(which composer) install`

**Comment by MaximilianClemens** [comment]
> The instructions are outdated, use `composer install` or `php $(which composer) install`
I tried, but:

**Comment by fredemmott** [comment]
What versions of HHVM and composer are you using?

**Comment by MaximilianClemens** [comment]
root@A4:/var/www/c0mmander.de# composer --version
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Composer 1.6.3 2018-01-31 16:28:17
root@A4:/var/www/c0mmander.de# hhvm --version
HipHop VM 4.28.0 (rel)
Compiler: 1571678629_197174034
Repo schema: c1068de11223e85fa6f517d694c9df37c23b7732

**Comment by fredemmott** [comment]
You need a more recent version of composer; `composer self-update` may work, otherwise download a phar from getcomposer.org

**Comment by MaximilianClemens** [comment]
Works perfect, thank you @fredemmott

**Comment by fredemmott** [comment]
You're welcome - and thanks for the report :)
