### ISSUE TITLE
Missing documentation on public and protected constructor parameters

### ISSUE THREAD

**Issue by robz** [hhvm/user-documentation#741]
Please complete the information below:

# Where is the problem?

The docs on constructors:
https://docs.hhvm.com/hack/classes/constructors

# What is the problem?

There is no documentation that explicitly describes the behavior where constructor parameters annotated as "public" or "protected" become class instance members:

```
class A { 
  public function __construct(public int $x) {} 
}
(new A(3))->x; // 3
```

The old docs described much more explicitly: https://web.archive.org/web/20170706193234/https://docs.hhvm.com/hack/other-features/constructor-parameter-promotion

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.28.0:HSL=v4.25.0:2019-10-24T22:48:17+0000:20b292e78a5083871964d26362f50b9037c536b0
 - Page requested: /hack/classes/constructors
 - Page requested at: Fri, 25 Oct 2019 05:00:39 +0000
 - Controller: GuidePageController

**Comment by jjergus** [comment]
It's documented in https://docs.hhvm.com/hack/classes/constructors but I agree it does seem a bit hidden. I wonder if that's on purpose (seeing how most of the text there explains why people should be wary of using these) -- I'll see if I can find out who updated it and what the reasoning behind that is.
