### ISSUE TITLE
Description of `Shapes::removeKey` is misleading

### ISSUE THREAD

**Issue by elboman** [hhvm/user-documentation#756]
# Where is the problem?

`Shapes::removeKey` docs

# What is the problem?

The method description is misleading as it's reporting the following:

> Returns a $shape with $index field removed

While actually the method has a `void` return type

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.31.0:HSL=v4.25.2:2019-11-18T18:09:02+0000:2764b38ac8976c34d5fb3576fa72a902a96a87b7
 - Page requested: /hack/reference/class/HH.Shapes/removeKey/
 - Page requested at: Tue, 03 Dec 2019 10:20:34 +0000
 - Controller: APIMethodPageController

**Comment by azjezz** [comment]
shapes are not passed by references, so if the `hhi` contains a `void` return type, the `hhi` is wrong, not the documentation ( since `Shapes::removeKey` *cannot* remove an element if the shape is not passed as an `inout` argument )

**Comment by jjergus** [comment]
Good catch. It is passed in as an inout argument, I'll fix that.
