### ISSUE TITLE
[ Language update ] Update the docs for (pre|post)fix (incr|decr)ment

### ISSUE THREAD

**Issue by lexidor** [hhvm/user-documentation#786]
Please complete the information below:

# Where is the problem?

The examples shows $i++ being used as an expression.

# What is the problem?

This is not allowed, since lval as an expression has been banned.

# QQ

Is there even a difference between the prefix and postfix forms anymore.
I can find a way to use the _return value_ of a increment operator.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.40.0:HSL=v4.40.0:2020-01-17T14:02:04+0000:9f1d392f2f951dfdad225c21329bf894f6577f36
 - Page requested: /hack/expressions-and-operators/incrementing-and-decrementing
 - Page requested at: Sat, 25 Jan 2020 23:10:29 +0000
 - Controller: GuidePageController

**Comment by Wilfred** [comment]
I'm not aware of any differences between e.g. `$i++` and `++$i` any more.
