### ISSUE TITLE
Docs navigate to linux install instructions skipping mac

### ISSUE THREAD

**Issue by xixixao** [hhvm/user-documentation#787]
Please complete the information below:

# Where is the problem?

Refer to [our directions on installing a prebuilt package.]()

# What is the problem?

Links to https://docs.hhvm.com/hhvm/installation/linux

This is super confusing and makes the mac install instructions hidden

It should link instead to https://docs.hhvm.com/hhvm/installation/introduction
Which lists both Linux and Mac

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.40.0:HSL=v4.40.0:2020-01-17T14:02:04+0000:9f1d392f2f951dfdad225c21329bf894f6577f36
 - Page requested: /hhvm/getting-started/getting-started
 - Page requested at: Sun, 26 Jan 2020 07:17:12 +0000
 - Controller: GuidePageController

**Comment by Wilfred** [comment]
What page links to the linux installation page? Your first link just points to this github issue.

**Comment by jjergus** [comment]
> What page links to the linux installation page?

You can always find the page based on "Page requested" in the "Please don't change anything below this point." section at the bottom.

(this one's already fixed though)
