### ISSUE TITLE
Add Dict\group_by Example

### ISSUE THREAD

**Issue by jsjoeio** [hhvm/user-documentation#793]
Please complete the information below:

# Where is the problem?

[Dict\group_by page](https://docs.hhvm.com/hsl/reference/function/HH.Lib.Dict.group_by/)

# What is the problem?

Suggestion: add an "Examples" section and show me how to use `Dict\group_by`

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.42.0:HSL=v4.40.0:2020-01-28T18:53:22+0000:e33eca7b49fad50146e312f0f100dcd7ba8047bb
 - Page requested: /hsl/reference/function/HH.Lib.Dict.group_by/
 - Page requested at: Wed, 29 Jan 2020 20:54:51 +0000
 - Controller: APIClassPageController

**Comment by jjergus** [comment]
Feel free to suggest better examples :)

**Comment by jsjoeio** [comment]
This helps a ton. Thank you @jjergus :)
