### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by alitalari** [hhvm/user-documentation#794]
Please complete the information below:

https://docs.hhvm.com/hack/generics/type-arguments

The last line of description
In this case, ..., and Tu, and are type arguments.
Here is the typo after and  ^

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.42.0:HSL=v4.40.0:2020-01-30T15:21:12+0000:74199dc01c56e4733713bdc71ce4d0b93d5c82b3
 - Page requested: /hack/generics/type-arguments
 - Page requested at: Thu, 30 Jan 2020 16:45:58 +0000
 - Controller: GuidePageController

**Comment by Wilfred** [comment]
Crikey, that page could definitely be clearer.

**Comment by Wilfred** [comment]
Looks like the text has been copy-pasted here too: https://docs.hhvm.com/hack/generics/type-arguments
