### ISSUE TITLE
Content doesn't fit on screen

### ISSUE THREAD

**Issue by xixixao** [hhvm/user-documentation#797]
Please complete the information below:

# Where is the problem?

Every page (almost)

# What is the problem?

The right pane doesn't fit on screen:

<img width="1439" alt="Screenshot 2020-02-05 21 09 57" src="https://user-images.githubusercontent.com/1473433/73907634-f0f47d80-485b-11ea-97d7-63d0596db9c3.png">

Some CSS issue with the docs. I do not have the browser zoomed. I'm using Chrome.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.43.0:HSL=v4.40.0:2020-02-05T23:29:58+0000:f852ef8b5561843e9311cb502ae9baf788d6d841
 - Page requested: /hack/getting-started/starting-a-real-project
 - Page requested at: Thu, 06 Feb 2020 05:09:42 +0000
 - Controller: GuidePageController

**Comment by Wilfred** [comment]
Looks like it depends on the browser window width. There are some widths where the content is wider than window.
