### ISSUE TITLE
com

### ISSUE THREAD

**Issue by angguwulandari21** [hhvm/user-documentation#799]
Please complete the information below:

# Where is the problem?

- - - eg "The section describing how widgets work" - - -

# What is the problem?

- - - eg "It doesn't explain that widgets are singletons" - - -

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.43.0:HSL=v4.40.0:2020-02-05T23:29:58+0000:f852ef8b5561843e9311cb502ae9baf788d6d841
 - Page requested: /hhvm/basic-usage/command-line
 - Page requested at: Thu, 06 Feb 2020 09:53:07 +0000
 - Controller: GuidePageController

**Comment by angguwulandari21** [comment]
#
Duplicate of #

**Comment by Wilfred** [comment]
I'm not sure what needs fixing here. Feel free to reopen if you have an issue.
