### ISSUE TITLE
Async guide issues

### ISSUE THREAD

**Issue by fredemmott** [hhvm/user-documentation#8]
Intro
------

- make it clearer that executing two async functions that call blocking functions (eg non-asio curl_exec()) will not execute curl in parallel. Another picture could be handy for this. An alternative would be to use APIs with more different names for the examples - eg sleep() vs HH\Asio\usleep().

Wait handles
-----------------

 - do we just want to call this 'Awaitables' instead? `WaitHandle` exists, but isn't what this is talking about - it looks like this section is just defining 'wait handle' to be another word for awaitable?

 - 'The type of the Awaitable will be the underlying type that the function would return if it wasn't async' - this is very unclear. The type of the Awaitable will be `Awaitable<T>`, not `T`

 - The comment in the example seems confusing too:

```
  // You aren't really returning 2 in the normal sense.
  // You are returning a wait handle that will, upon conclusion of execution,
  // contain the result of 2.
  return 2;
```

I am *not* returning an awaitable, I'm returning 2. The Awaitable part applies to the whole function, not just the return statement.

**Comment by SiebelsTim** [comment]
> The comment in the example seems confusing too:

>  // You aren't really returning 2 in the normal sense.
>  // You are returning a wait handle that will, upon conclusion of execution,
>  // contain the result of 2.
>  return 2;
>I am not returning an awaitable, I'm returning 2. The Awaitable part applies to the whole function, not just the return statement.

I think this is more of a technicality. The gist is that you don't get an int from that function, even though you return one; you'll get an `Awaitable<int>`. And that's what I would understand from that comment. 
Phrasing it differently might overcomplicate things.

That being said, I'd be pleased with a different explanation as long as it is not confusing people more than this.

**Comment by fredemmott** [comment]
My worry is that it implies that the Awaitable you get back will be created after any preceding await() calls
