### ISSUE TITLE
Mention as/?as for converting enum values 

### ISSUE THREAD

**Issue by ryangreenberg** [hhvm/user-documentation#800]
Converting to/from enum values is a common action with enums; it would be useful to explain how to do this at https://docs.hhvm.com/hack/built-in-types/enumerated-types (or link to conversion docs elsewhere if preferred).

From an internal discussion:

```Hack
enum Duck: string {
  MALLARD = 'mallard';
  CANVASBACK = 'canvasback';
}

$definitely_duck as Duck; // converts to Duck, throws if not
$maybe_duck ?as Duck; // converts to ?Duck; null if is not a valid value
```

> "That would be great to include in the enum docs at https://docs.hhvm.com/hack/built-in-types/enumerated-types"

**Comment by Wilfred** [comment]
Agreed. This is mentioned in the `as` page: https://docs.hhvm.com/hack/expressions-and-operators/type-assertions but we should definitely link it from the enum page.

**Comment by andrewjtimmons** [comment]
I have a pr that can add that and a short example with the generated files as well using  
https://github.com/hhvm/user-documentation/blob/master/CONTRIBUTING.md

When I try to push my branch up I get
```
git push --set-upstream origin enum_duck_doc
remote: Permission to hhvm/user-documentation.git denied to andrewjtimmons.
fatal: unable to access 'https://github.com/hhvm/user-documentation.git/': The requested URL returned error: 403
```

I pulled down a clone of one of my personal repos and was able to push up a change with my creds, and 2x checked my github keychain on osx and it looks like the right token (I have 2fa).  

Is there something else I need to push up a branch?

**Comment by Wilfred** [comment]
#802 reverted #801.

**Comment by jjergus** [comment]
I've also noticed that `as` with enums seems to have `==`-like semantics instead of requiring strict equality (like `===`).

```hack
enum IntEnum: int {
  FOO = 1;
  BAR = 2;
}

enum StringEnum: string {
  FOO = '1';
  BAR = '2';
}

<<__EntryPoint>>
function int_enum_main(): void {
  var_dump(1 as IntEnum);
  var_dump('1' as IntEnum);
  var_dump(1 as StringEnum);
  var_dump('1' as StringEnum);
}
```

does not throw, outputs

```
int(1)
string(1) "1"
int(1)
string(1) "1"
```

even though half of those are not actually valid values of the respective enum!

If this is intentional we might want to include it in the documentation.

**Comment by jjergus** [comment]
That behavior is also inconsistent with `assert`, which seems to guarantee that the returned value is valid for the respective enum (but that means it doesn't always return the input unchanged):

```hack
<<__EntryPoint>>
function int_enum_main(): void {
  var_dump(IntEnum::assert(1));
  var_dump(IntEnum::assert('1'));
  var_dump(StringEnum::assert(1));
  var_dump(StringEnum::assert('1'));
}
```

```
int(1)
int(1)
string(1) "1"
string(1) "1"
```

**Comment by lexidor** [comment]
> I've also noticed that `as` with enums seems to have `==`-like semantics instead of requiring strict equality (like `===`).
> 
> ```hack
> enum IntEnum: int {
>   FOO = 1;
>   BAR = 2;
> }
> 
> enum StringEnum: string {
>   FOO = '1';
>   BAR = '2';
> }
> 
> <<__EntryPoint>>
> function int_enum_main(): void {
>   var_dump(1 as IntEnum);
>   var_dump('1' as IntEnum);
>   var_dump(1 as StringEnum);
>   var_dump('1' as StringEnum);
> }
> ```
> 
> does not throw, outputs
> 
> ```
> int(1)
> string(1) "1"
> int(1)
> string(1) "1"
> ```
> 
> even though half of those are not actually valid values of the respective enum!
> 
> If this is intentional we might want to include it in the documentation.

https://github.com/facebook/hhvm/issues/8651

The blog said that this would be fixed in a later release.
I would be very happy when this behavior gets abolished.

**Comment by fredemmott** [comment]
```
var_dump(1 as StringEnum); // int(1)
```

This part at least must be fixed as part of trusted types

**Comment by fredemmott** [comment]
FB T29283057
