### ISSUE TITLE
Incorrect runtime complexity for Keyset\diff()

### ISSUE THREAD

**Issue by guliashvili** [hhvm/user-documentation#809]
Please complete the information below:

# Where is the problem?

https://docs.hhvm.com/hsl/reference/function/HH.Lib.Keyset.diff/

Section describing Keyset\diff() runtime complexity

# What is the problem?

Runtime complexity is said to be O(n + m) however, I checked the implementation and it looks to be  O(n*m)
--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.44.0:HSL=v4.40.0:2020-02-19T22:07:47+0000:aaa88b7502a30207bf2e5607d0e4c128f93a54cc
 - Page requested: /hsl/reference/function/HH.Lib.Keyset.diff/
 - Page requested at: Thu, 20 Feb 2020 11:13:28 +0000
 - Controller: APIClassPageController

**Comment by lexidor** [comment]
Thanks for making us aware.
In future, documentation problems about function descriptions is being parsed from the docblocks.
So, the underlying problem actually resides in the [hsl](https://github.com/hhvm/hsl) itself.
Opening an issue there will increase the chances it is read by the right people in a timely manner.

Do you want me to forward the issue to the hsl for you?

**Comment by jjergus** [comment]
Either hsl or here is fine, it's mostly the same people reading both anyway...
