### ISSUE TITLE
Can't get hacktest to work

### ISSUE THREAD

**Issue by eoswald** [hhvm/user-documentation#815]
Please complete the information below:

# Where is the problem?

https://docs.hhvm.com/hack/getting-started/starting-a-real-project#starting-a-real-project__unit-testing

# What is the problem?

I can't seem to get the `hacktest` in the example to work. This is on an Ubuntu 16.04.6 VM:

```
$ hhvm --version
HipHop VM 4.45.1 (rel)
Compiler: 1582087061_815238447
Repo schema: 77c740d16fffe5bee017531c1f97bf45cdf567b7


$ ls -la
total 192
drwxrwxr-x 6 eoswald eoswald   4096 Feb 22 14:53 .
drwxrwxr-x 3 eoswald eoswald   4096 Feb 21 21:14 ..
drwxrwxr-x 2 eoswald eoswald   4096 Feb 22 14:42 bin
-rw-rw-r-- 1 eoswald eoswald    221 Feb 21 22:32 composer.json
-rw-rw-r-- 1 eoswald eoswald  13195 Feb 21 23:01 composer.lock
-rw-rw-r-- 1 eoswald eoswald     69 Feb 21 23:12 hhast-lint.json
-rw-rw-r-- 1 eoswald eoswald     66 Feb 21 21:16 hh_autoload.json
-rw-rw-r-- 1 eoswald eoswald      0 Feb 21 21:14 .hhconfig
drwxrwxr-x 2 eoswald eoswald   4096 Feb 22 14:54 src
drwxrwxr-x 2 eoswald eoswald   4096 Feb 22 15:03 tests
drwxrwxr-x 6 eoswald eoswald   4096 Feb 21 23:01 vendor

$ cat tests/MyTest.hack
use function Facebook\FBExpect\expect;
use type Facebook\HackTest\{DataProvider, HackTest};

final class MyTest extends HackTest {
  public function provideSquaresExamples(): vec<(vec<num>, vec<num>)> {
    return vec[
      tuple(vec[1, 2, 3], vec[1, 4, 9]),
      tuple(vec[1.1, 2.2, 3.3], vec[1.1 * 1.1, 2.2 * 2.2, 3.3 * 3.3]),
    ];
  }

  <<DataProvider('provideSquaresExamples')>>
  public function testSquares(vec<num> $in, vec<num> $expected_output): void {
    expect(square_vec($in))->toBeSame($expected_output);
  }
}

$ ./vendor/bin/hacktest tests/


Summary: 0 test(s), 0 passed, 0 failed, 0 skipped, 0 error(s).

Fatal error: Uncaught exception 'ReflectionException' with message 'Class MyTest does not exist' in /home/eoswald/hack/examples/vendor/hhvm/hacktest/src/Retriever/ClassRetriever.hack:98
Stack trace:
#0 /home/eoswald/hack/examples/vendor/hhvm/hacktest/src/Retriever/ClassRetriever.hack(98): ReflectionClass->__construct()
#1 /home/eoswald/hack/examples/vendor/hhvm/hacktest/src/Runner/HackTestRunner.hack(46): Facebook\HackTest\ClassRetriever->getTestClassName()
#2 /home/eoswald/hack/examples/vendor/hhvm/hacktest/src/HackTestCLI.hack(103): Facebook\HackTest\HackTestRunner::runAsync()
#3 /home/eoswald/hack/examples/vendor/facebook/hh-clilib/src/CLIBase.hack(181): Facebook\HackTest\HackTestCLI->mainAsync()
#4 /home/eoswald/hack/examples/vendor/hhvm/hacktest/bin/hacktest.hack(36): Facebook\CLILib\CLIBase::runAsync()
#5 /home/eoswald/hack/examples/vendor/hhvm/hacktest/bin/hacktest(19): Facebook\HackTest\hack_test_main_async()
#6 (): Facebook\HackTest\hack_test_main_async_UNSAFE()
#7 (): Closure$__SystemLib\enter_async_entry_point()
#8 (): HH\Asio\join()
#9 (): __SystemLib\enter_async_entry_point()
#10 {main}
```

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.44.0:HSL=v4.40.0:2020-02-21T15:17:44+0000:8f87fb239f654c3529c0e3ace0f9dc039b22deae
 - Page requested: /hack/classes/inheritance
 - Page requested at: Sat, 22 Feb 2020 20:06:03 +0000
 - Controller: GuidePageController

**Comment by lexidor** [comment]
I have tried to reproduce your problem, but I wasn't able to.

Could you copy these instructions in an empty directory and execute them?
This will build the application I have over here, but with the hhvm 4.44 dependencies instead of my hhvm 4.45 dependencies. (They don't differ anyhow I would think so.)

You'll need to make the file executable.
I used `chmod 777 hacktest-test.sh`, but that might be overkill, since this makes it executable, readable and writable to all users.

Please execute it like so `./hacktest-test.sh >> script.stdout.txt 2>> script.stderr.txt`
This should cause script.stdout.txt, script.stderr.txt, hacktest.stdout.txt, and hacktest.stderr.txt to appear.

You hacktest output will be in hacktest.stdout.txt and should say.
```
..

Summary: 2 test(s), 2 passed, 0 failed, 0 skipped, 0 error(s).

```
If this application does not work, please send me all of these files and your composer.lock file.

hacktest-test.sh
```SH
echo "vendor/**" > .gitignore

touch .hhconfig

cat << 'EOF' > hh_autoload.json
{
"roots": [
    "src/"
  ],
  "devRoots": [
      "tests/"
  ],
  "devFailureHandler": "Facebook\\AutoloadMap\\HHClientFallbackHandler"
}
EOF

mkdir src

mkdir tests

cat << 'EOF' > src/square_vec.hack
function square_vec(vec<num> $nums): vec<num> {
    $out = vec[];
    foreach ($nums as $num) {
        $out[] = $num * $num;
    }
    return $out;
}
EOF

cat << 'EOF' > tests/MyTest.hack
use function Facebook\FBExpect\expect;
use type Facebook\HackTest\{DataProvider, HackTest};

final class MyTest extends HackTest {
    public function provideSquaresExamples(): vec<(vec<num>, vec<num>)> {
        return vec[
            tuple(vec[1, 2, 3], vec[1, 4, 9]),
            tuple(vec[1.1, 2.2, 3.3], vec[1.1 * 1.1, 2.2 * 2.2, 3.3 * 3.3]),
        ];
    }

    <<DataProvider('provideSquaresExamples')>>
    public function testSquares(vec<num> $in, vec<num> $expected_output): void {
        expect(square_vec($in))->toBeSame($expected_output);
    }
}
EOF

composer require hhvm/hacktest facebook/fbexpect --dev

hh_client restart --no-load

hh_client

vendor/bin/hh-autoload

vendor/bin/hacktest tests >> hacktest.stdout.txt 2>> hacktest.stderr.txt

echo "FINISHED"
```

**Comment by lexidor** [comment]
@eoswald When you read this, I might already be sleeping I am afraid. I hope this helped, if not, I'll read this tomorrow at some point, but that might take some time.

Feel free to @lexidor me in your response, so I will be notified it you still need help.

**Comment by eoswald** [comment]
Thanks again @lexidor ! I forgot to run `vendor/bin/hh-autoload`. Once I ran that everything worked.

**Comment by lexidor** [comment]
Good to know that you can continue to learn about hhvm and Hack.
If you think that we could make the instructions better by stressing or adding important parts that you missed, please open an issue with your suggestion.

**Comment by lexidor** [comment]
I have made #816 to address the things you ran into.
Do you think that this will be helpful?

**Comment by eoswald** [comment]
As someone who doesn't come from a PHP background, a section explaining autoloading would be very helpful. Thanks for putting this together!
