### ISSUE TITLE
AsyncGenerator documentation claims a guide is referenced, it isn't.

### ISSUE THREAD

**Issue by fredemmott** [hhvm/user-documentation#830]
" PLEASE READ THE GUIDE REFERENCED IN THIS API DOCUMENTATION FOR MORE INFORMATION"

No guide is referenced.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.44.0:HSL=v4.40.0:2020-03-02T21:51:17+0000:46c873cd1406ff85f61a48da737237395c587cd0
 - Page requested: /hack/reference/class/HH.AsyncGenerator/
 - Page requested at: Mon, 09 Mar 2020 16:50:24 +0000
 - Controller: APIClassPageController

**Comment by fredemmott** [comment]
Looks like there's an @guide in there, but redirects need to be resolved for it to work, or it needs to be updated. We're probably not resolving legacy redirects for @guide like we do for actual URLs

**Comment by jjergus** [comment]
Looks like `@guide` doesn't work at all, I'll look into it.
