### ISSUE TITLE
Reword the section about array access via idx()

### ISSUE THREAD

**Issue by stoyan** [hhvm/user-documentation#845]
Please complete the information below:

# Where is the problem?

https://docs.hhvm.com/hack/reference/function/HH.idx/

# What is the problem?

"Instead, just access it normally like a sensible human being:"

This is fun when read at leisure, but when a person is stuck and looking for an answer (and likely frustrated), it comes as condescending. 

Maybe say:

"Instead, use regular array access by key:"

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.50.0:HSL=v4.40.0:2020-04-01T02:30:28+0000:fd6d472020e06f7aa0ad67310efa0553de4ad35d
 - Page requested: /hack/reference/function/HH.idx/
 - Page requested at: Wed, 01 Apr 2020 19:23:59 +0000
 - Controller: APIClassPageController

**Comment by Wilfred** [comment]
This will be fixed by https://github.com/facebook/hhvm/pull/8685

**Comment by lexidor** [comment]
facebook/hhvm#8685 was merged
