### ISSUE TITLE
Subscripting, []: what happens when a key is missing + null-safe operators

### ISSUE THREAD

**Issue by yukonfb** [hhvm/user-documentation#848]
Please complete the information below:

# Where is the problem?
Expressions And Operators: Subscript

# What is the problem?
- Doesn't explain what will happen if key doesn't exist
- Doesn't describe available options for handling non-existent keys (null-safe-like operations with [])
$foo = mydict['badkey']['goodkey']; // maybe "$foo = mydict['badkey']['goodkey'] ?? null;" ?

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.52.1:HSL=v4.40.0:2020-04-09T15:46:58+0000:d96130cc77b2ef2fc08fd66697c635a9d1aa5519
 - Page requested: /hack/expressions-and-operators/subscript
 - Page requested at: Fri, 10 Apr 2020 16:10:26 +0000
 - Controller: GuidePageController

**Comment by jjergus** [comment]
This should be covered by #849 so let's keep the discussion in that issue.
