### ISSUE TITLE
Building .deb from source

### ISSUE THREAD

**Issue by VamshiMuthineni** [hhvm/user-documentation#852]
Please complete the information below:

# Where is the problem?

- - - eg "The section describing how widgets work" - - -
I am building hhvm from source as I need hhvm for multi-architecture. However the build from source is taking too long. So I thought of creating a .deb file locally and install from .deb for the subsequent runs.
# What is the problem?
However I cannot find a document which explains how I can create a debian file. Can someone help me with how I can create a .deb file from the hhvm source. Thank you.
- - - eg "It doesn't explain that widgets are singletons" - - -

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.52.1:HSL=v4.40.0:2020-04-14T20:38:45+0000:91d14b590d1e646831d6a0619e941b88dffa49ea
 - Page requested: /hhvm/installation/building-from-source
 - Page requested at: Wed, 15 Apr 2020 00:50:16 +0000
 - Controller: GuidePageController

**Comment by fredemmott** [comment]
We only support using our prebuilt packages or directly building from source; that said, the scripts we use to build our debian packages (including debian/ directories) are at https://github.com/hhvm/packaging

**Comment by VamshiMuthineni** [comment]
Oh thanks for the quick response. I'll look into the scripts.

**Comment by fredemmott** [comment]
Also, we publish standard debian source packages; you might find it easier to start by:
- installing a supported distribution if you're not using one already
- mark our repositories as a source repository
- `apt-get update; apt-get source hhvm`
- work from there, following Debian's package maintainance documentation; if your target distribution is not supported, copy the source to the target distribution

The advantage of this is it only gets you the debian sources, separate from all of our build infrastructure and scripts.

On the other hand, if you're wanting to do this to support another distribution, we'd definitely consider pull requests to that repository expanding our list of supported distributions (keeping in mind https://hhvm.com/blog/2019/11/19/distribution-support.html - the primary purpose of that policy is to not need to support older compilers).

If you're doing a custom build for a supported distribution, apt-get source is probably the most convenient way
