### ISSUE TITLE
[ Docblock render ] Docblocks that contain double underscores get bolded, instead of literal double underscores

### ISSUE THREAD

**Issue by lexidor** [hhvm/user-documentation#859]
Please complete the information below:

# Where is the problem?

The docs of [FunctionCredential](https://docs.hhvm.com/hack/reference/class/FunctionCredential/) is one example I found.

# What is the problem?

The magic constant is displayed as **FUNCTION_CREDENTIAL** instead of \_\_FUNCTION\_CRENDENTIAL\_\_.

Can docblocks contain actual markdown?

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.53.0:HSL=v4.40.0:2020-04-28T02:22:33+0000:1e2682c54d15e9026ef1f59508ea72a7ef11c040
 - Page requested: /hack/reference/class/FunctionCredential/
 - Page requested at: Wed, 29 Apr 2020 12:32:15 +0000
 - Controller: APIClassPageController

**Comment by Wilfred** [comment]
Yep, I think docblocks can contain markdown.

`__FUNCTION_CRENDENTIAL__` is very new, so I'm not surprised there. Did you spot any other cases @lexidor ?

**Comment by lexidor** [comment]
I can't remember if I have spotted more.
Do we want to escape markdown sequences in docblocks?
That makes it worse for the IDE user in my opinion.

**Comment by fredemmott** [comment]
We have a lot of docblocks intentionally using markdown; they should not be escaped. Backticks should be added here.

**Comment by lexidor** [comment]
The is indeed a very good procedure.
I forgot about backtick codeblocks for a second and was considering escaping like this `\_\_FUNCTION\_CREDENTIAL\_\_`, which is just awful.

**Comment by lexidor** [comment]
This is intended behavior. In cases where Hack syntax conflicts with markdown syntax, use backticks to create codeblocks.
