### ISSUE TITLE
File extension and header guidelines only apply to open source, not internal source

### ISSUE THREAD

**Issue by chrishsu-utexas** [hhvm/user-documentation#875]
Please complete the information below:

# Where is the problem?

https://docs.hhvm.com/hack/source-code-fundamentals/program-structure

# What is the problem?

.hack vs .php file extension guidelines and shebang header only apply to open source, not internal source. Documentation could clarify this for internal readers.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.57.0:HSL=v4.41.0:2020-05-21T18:29:34+0000:422a1f74d5f744078d1a5aba910cd7ced3e6f419
 - Page requested: /hack/source-code-fundamentals/program-structure
 - Page requested at: Fri, 12 Jun 2020 23:59:08 +0000
 - Controller: GuidePageController

**Comment by AndrewDiMola** [comment]
Closing because this was clarified and added in https://github.com/hhvm/user-documentation/pull/1209/.
