### ISSUE TITLE
Make "Type System" -> "this" code example a bit less daunting

### ISSUE THREAD

**Issue by daviddoran** [hhvm/user-documentation#88]
The current example has quite a lot of code (and a massive comment about `__ConsistentConstruct`) so for me it's a bit hard to pick out the important bits being demonstrated.

I think we should focus on:

- Why `__ConsistentConstruct` is needed
- Returning `this` from a static method
- Returning `this` from an instance method (and demonstrate chaining)

http://beta.docs.hhvm.com/hack/types/type-system#this

**Comment by JoelMarcey** [comment]
@daviddoran I think the `this` section needs a bit more work overall. Not sure why I only mention `class` methods here. `instance` methods are fine with `this` too, as you say.

And maybe with that example in particular, should I just remove the `__ConsistentConstruct` and just use `final` on the class? It could be getting in the way.
