### ISSUE TITLE
Clarify whether refinement is upcasting or downcasting

### ISSUE THREAD

**Issue by daviddoran** [hhvm/user-documentation#90]
http://beta.docs.hhvm.com/hack/types/refining#refining-types

The "Refining Types" section says:

    Suppose you want to take a given type and refine (upcast) that type to another type.

My (amateur) understanding was that:

- Upcasting would be `Apple -> Fruit` or `string -> mixed`
- Downcasting would be `Fruit -> Apple` or `?string -> string`

Isn't refinement better described as downcasting?

**Comment by SiebelsTim** [comment]
I think the `upcast` is misleading, too. I wouldn't use `downcasting` though.
