### ISSUE TITLE
How to Deploy Hack/HHVM Project without Docker

### ISSUE THREAD

**Issue by jsjoeio** [hhvm/user-documentation#900]
Please complete the information below:

# Where is the problem?

Hack docs. No Deployment section. 

# What is the problem?

I would like to deploy a simple web server written in Hack but don't know how. 

I see the Docker guide [here](https://docs.hhvm.com/hhvm/installation/docker), but I don't want to go through the trouble of Docker. I'm looking for the simplest solution.

I found [this](https://github.com/facebookarchive/hack-example-site/tree/master) in the graveyard, which uses Heroku. It's 5 years old and archived so I don't know if it's still relevant or even works. 

I would love to use something like Vercel to simply run a few commands an deploy. [`vercel-php`](https://github.com/juicyfx/vercel-php) looks interesting, but I don't know if that could work with Hack/HHVM (that's out of my wheelhouse).

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.68.0:HSL=v4.41.0:2020-08-05T17:24:57+0000:9fbb0a467816209cc97aa4dc9511b9597d26d9d8
 - Page requested: /hack/
 - Page requested at: Wed, 05 Aug 2020 20:25:37 +0000
 - Controller: GuidesListController

**Comment by fredemmott** [comment]
- install following the platform-specific documentation that's appropriate - probably https://docs.hhvm.com/hhvm/installation/linux
- https://docs.hhvm.com/hhvm/basic-usage/server 

We're not currently able to recommend, document, or support specific hosting/deployment services.
