### ISSUE TITLE
Split enums, tuples etc to separate guide page

### ISSUE THREAD

**Issue by fredemmott** [hhvm/user-documentation#91]
They don't show up in the navbar as part of the 'Type System' page - this would make them more easily finable

**Comment by fredemmott** [comment]
current page: http://beta.docs.hhvm.com/hack/types/type-system#tuples

**Comment by JoelMarcey** [comment]
So we have a main `enum` page...

http://beta.docs.hhvm.com/hack/enums/introduction

I could create a main `tuples` page too, if that make sense.

Is there a way to have the sidebar expand into second level topics as an alternative?

We have a sideways triangle that points to the current topic, you figure you might be able to point that triangle down for second level topics if you click on it.

**Comment by fredemmott** [comment]
Could be worth adding, but not currently

**Comment by JoelMarcey** [comment]
Ok, so for now, let me just create a main `tuples` topic, like I did with `enums`, `shapes`, etc.
