### ISSUE TITLE
Error in explanation of trait and class method precedence

### ISSUE THREAD

**Issue by jmalroth** [hhvm/user-documentation#916]
Please complete the information below:

# Where is the problem?

The final "output" section

# What is the problem?

I believe the following sentence is wrong: "For methods, a rule of thumb is "traits provide a method implementation unless the class itself does not"."

Specifically - It should be "traits provide a method implementation ~unless~ *if* the class itself does not." or "traits provide a method implementation unless the class itself does ~not~" . The subsequent text explains that the trait method only applies if a method with a matching signature does *not* appear on the class.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.74.0:HSL=v4.41.0:2020-09-09T21:20:59+0000:1fa47f258c6b68f8ec01899aa82fd6ffa0957109
 - Page requested: /hack/classes/using-a-trait
 - Page requested at: Thu, 17 Sep 2020 04:51:50 +0000
 - Controller: GuidePageController

**Comment by jjergus** [comment]
Good catch, thanks!
