### ISSUE TITLE
It is not necessary with backslash

### ISSUE THREAD

**Issue by dotku** [hhvm/user-documentation#918]
Please complete the information below:

For code
```
function fibonacci(int $number): int {
  return \intval(\round(\pow((\sqrt(5.0) + 1) / 2, $number) / \sqrt(5.0)));
}
```

We could just remove the backslash we could simply keep it as clean as below

```
function fibonacci(int $number): int {
  return intval(round(pow((sqrt(5.0) + 1) / 2, $number) / sqrt(5.0)));
}
```

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.74.0:HSL=v4.41.0:2020-09-09T21:20:59+0000:1fa47f258c6b68f8ec01899aa82fd6ffa0957109
 - Page requested: /hhvm/basic-usage/command-line
 - Page requested at: Fri, 18 Sep 2020 19:21:53 +0000
 - Controller: GuidePageController

**Comment by Wilfred** [comment]
```
namespace HHVM\UserDocumentation\BasicUsage\Examples\CommandLine;

function fibonacci(int $number): int {
  return \intval(\round(\pow((\sqrt(5.0) + 1) / 2, $number) / \sqrt(5.0)));
}

<<__EntryPoint>>
function main(): void {
  $n = (int) (vec(\HH\global_get('argv') as Container<_>)[1] ?? 10);
  echo 'The '.
    $n.
    ' number in fibonacci is: '.
    fibonacci($n).
    \PHP_EOL;
}
```

Since the full file is in a namespace, it should be necessary.

I agree that the example is noisy and distracting. We should simplify it.

**Comment by jjergus** [comment]
Almost all real code is (or should be) in a namespace, so global functions have to be referenced with the `\`, so I think it makes sense for the documentation to follow that.

Agreed that we should use a simpler example in this guide though.
