### ISSUE TITLE
Define "reified"

### ISSUE THREAD

**Issue by talldean** [hhvm/user-documentation#922]
Please complete the information below:

# Where is the problem?

This uses the word reified without defining it, and it's still not a super common word outside of compilers/language folks.

# What is the problem?

Define it before diving in, and the page reads a lot more easily.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.74.0:HSL=v4.41.0:2020-09-24T18:02:02+0000:1fa47f258c6b68f8ec01899aa82fd6ffa0957109
 - Page requested: /hack/generics/reified-generics
 - Page requested at: Thu, 01 Oct 2020 19:40:51 +0000
 - Controller: GuidePageController

**Comment by AndrewDiMola** [comment]
Added here https://github.com/hhvm/user-documentation/commit/cff7285453b4c2ee16fc09c85e203b7b8a9f5273.
