### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by zilberstein** [hhvm/user-documentation#925]
Please complete the information below:

# Where is the problem?

The "set_error_handler" link is broken

# What is the problem?

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.77.0:HSL=v4.41.0:2020-10-01T22:14:18+0000:1fa47f258c6b68f8ec01899aa82fd6ffa0957109
 - Page requested: /hack/expressions-and-operators/error-control
 - Page requested at: Tue, 06 Oct 2020 20:28:44 +0000
 - Controller: GuidePageController

**Comment by AndrewDiMola** [comment]
Fixed in https://github.com/hhvm/user-documentation/commit/1e89e16e3afff4e4911eb888d24002382ca1cdee
