### ISSUE TITLE
Make `bin/update-versions` handle the massive number of HHVM tags there are nowadays

### ISSUE THREAD

**Issue by fredemmott** [hhvm/user-documentation#928]
Right now, it'll fetch 10 pages. Fetching more hits github rate limits.

Pushing the nightly tags doesn't help :p

This should probably stop using the github API, and instead call Ghostbusters^W`git ls-remote --tags https://github.com/facebook/hhvm.git --quiet HHVM-\*`

**Comment by fredemmott** [comment]
It errors out; You can manually specify `--hhvm-tag=` to work around this.

**Comment by jjergus** [comment]
I changed it to 20 pages during my last version update :) But agreed we should fix it properly.

**Comment by fredemmott** [comment]
When I tried that, I hit a github API rate limit; I don't think we can run the script twice at the moment :)
