### ISSUE TITLE
Style on "inconsistencies" is difficult to visually parse

### ISSUE THREAD

**Issue by jwatzman** [hhvm/user-documentation#93]
Was just skimming http://beta.docs.hhvm.com/hhvm/inconsistencies/introduction and noticed how hard it was to visually parse the hierarchy of sections and subsections. Not sure what the problem is -- maybe the prevalence of code (which is styled differently) in the headers? In any event, I found it a ton harder to read than the markdown original in the HHVM repo's docs dir.

Not sure what the right solution is, just thought it worth pointing out.

**Comment by JoelMarcey** [comment]
Could be that h2 and h3 headers are just too similar in font, height and style. Let me remove the code styles in the headers and see if that helps.

**Comment by JoelMarcey** [comment]
would it be better to have different guides (pages) for the inconsistencies. One for each major topic

`arrays`
`foreach`
:
:
