### ISSUE TITLE
Misspell the  word "annotation" 

### ISSUE THREAD

**Issue by larryleizhou** [hhvm/user-documentation#938]
Please complete the information below:

# Where is the problem?

"typed anotation " 

# What is the problem?

annotation is misspelled.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.79.0:HSL=v4.41.0:2020-10-23T20:15:50+0000:1fa47f258c6b68f8ec01899aa82fd6ffa0957109
 - Page requested: /hack/asynchronous-operations/blocks
 - Page requested at: Sat, 24 Oct 2020 04:13:30 +0000
 - Controller: GuidePageController

**Comment by Wilfred** [comment]
I can't see any mentions of "anotation" on that page, but I've fixed the "type anotation" on the anonymous functions page. Thanks!
