### ISSUE TITLE
Ordered lists are styled without any number or bullet

### ISSUE THREAD

**Issue by daviddoran** [hhvm/user-documentation#95]
- http://beta.docs.hhvm.com/hack/async/guidelines#considering-data-dependencies-is-important
- http://127.0.0.1:8080/hack/async/guidelines#considering-data-dependencies-is-important
- [public/main.css#L46-L48](https://github.com/hhvm/user-documentation/blob/23aa17af1cf4ab6472f9856270eef35a7708ba21/public/main.css#L46-L48)

<img width="1092" alt="async guidelines 2015-11-18 12-27-40" src="https://cloud.githubusercontent.com/assets/313983/11241118/d5cd4788-8def-11e5-8504-282d25a7e547.png">

**Comment by fredemmott** [comment]
cc @matthewjohnston4
