### ISSUE TITLE
Minor issue in document of Namespaces

### ISSUE THREAD

**Issue by haoysRPI** [hhvm/user-documentation#953]
Please complete the information below:

# Where is the problem?

In section of "Source Code Fundamentals: Namespaces",  the third paragraph says "See script inclusion for an example involving two class types, each defined in its own namespace, used by an application in a third namespace."

# What is the problem?

In section of script inclusion, there is no such an example. 

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.84.0:HSL=v4.41.0:2020-11-18T21:55:19+0000:1fa47f258c6b68f8ec01899aa82fd6ffa0957109
 - Page requested: /hack/source-code-fundamentals/namespaces
 - Page requested at: Sat, 21 Nov 2020 18:58:02 +0000
 - Controller: GuidePageController

**Comment by AndrewDiMola** [comment]
Removed reference to example that was removed in https://github.com/hhvm/user-documentation/commit/bef041feb349785d7be8bddf35e9035124cf558b.
