### ISSUE TITLE
Clarify the interactions between awaitables, __Memoize, and throwables

### ISSUE THREAD

**Issue by xEtherealx** [hhvm/user-documentation#959]
Please complete the information below:

# Where is the problem?

https://docs.hhvm.com/hack/attributes/predefined-attributes#__memoize

# What is the problem?

The statement "If an exception is thrown, this is not memoized." is not true. It should read something like

"If an exception is thrown, it is only memoized for async methods."
--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.84.0:HSL=v4.41.0:2020-12-01T03:40:24+0000:1fa47f258c6b68f8ec01899aa82fd6ffa0957109
 - Page requested: /hack/attributes/predefined-attributes
 - Page requested at: Thu, 03 Dec 2020 20:17:27 +0000
 - Controller: GuidePageController

**Comment by fredemmott** [comment]
This isn't correct - the Awaitable itself is memoized - but some clarification here would be good. #853 is a stale work in progress on this.

For example, this is equivalent, and does not use memoize:

```Hack
async function foo(): Awaitable<void> {
  await \HH\Asio\later();
  print("Throwing!\n");
  throw new Exception();
}

<<__EntryPoint>>
async function main(): Awaitable<void> {
  print("Calling foo()\n");
  $x = foo();
  print ("Called foo()\n");
  try {
    await $x;
  } catch (Exception $_) {
    print("Caught once\n");
  }
  try {
    await $x;
  } catch (Exception $_) {
    print("Caught twice\n");
  }
}
```

```
Calling foo()
Called foo()
Throwing!
Caught once
Caught twice
```

**Comment by fredemmott** [comment]
... or, without exceptions:

```hack
class TestClass {
  public function __construct() {
    print("__Construct\n");
  }
}
async function foo(): Awaitable<TestClass> {
  await \HH\Asio\later();
  return new TestClass();
}

<<__EntryPoint>>
async function main(): Awaitable<void> {
  print("Calling foo()\n");
  $x = foo();
  var_dump(await $x);
  var_dump(await $x);
}
```

```
Calling foo()
__Construct
object(TestClass) (0) {
}
object(TestClass) (0) {
}
```
