### ISSUE TITLE
non-generated files included in `build/`

### ISSUE THREAD

**Issue by fredemmott** [hhvm/user-documentation#981]
For example:

- `build/extracted-examples/guides/hack/21-XHP/10-interfaces/md.md_render.inc.hack`
- `build/extracted-examples/guides/hack/03-expressions-and-operators/99-yield/Testfile.txt`
- `build/extracted-examples/guides/hack/06-classes/16-constructors/unpromotion.inc.hack`

While deleting `build/extracted-examples/` shouldn't be a regular part of workflow, deleting everything in `build/` should be safe when followed by `bin/build.php`

In this case, I did this while trying to figure out why the change in #980 v1 does not create the necessary .skipif files

**Comment by jjergus** [comment]
I'll move these (I already moved some .inc files to src/utils/examples but apparently missed these).

> deleting everything in build/ should be safe when followed by bin/build.php

It should be safe but still probably not a good idea in general, as it's

- super slow
- non-deterministic because of various async and rand examples

**Comment by fredemmott** [comment]
I'm *hoping* that some .example.out files will change and that's it - if we're close to that it would be nice to actually test that too :)

**Comment by jjergus** [comment]
That sounds about right, unless there's an HHVM update that breaks some examples (which should be detected as a test failure), .example.out should be the only changes.

It should be easy to update the build script to detect (and delete?) extra files, I'll do that. The rest is covered by ExamplesTest I think.
