### ISSUE TITLE
RFC: Facebook employee dev environment: don't change 'origin'

### ISSUE THREAD

**Issue by fredemmott** [hhvm/user-documentation#987]
Most documentation for git suggests `git pull --rebase origin master` or similar. It would be nice if that would continue working. Currently, `origin` is changed to be the users' fork

Some ways to avoid this:
- create a new remote, e.g. `myusername`, and make it the default remote
- use `git remote set-url --push origin` instead of just `git remote set-url origin`; this will both make sure that `git push origin` doesn't accidentally create branches in the main repo, but also keep fetching working as expected.

I see the first as more 'standard'/less surprising, more consistent with general git documentation, but the second as less likely to have practical issues for people who don't use git regularly

**Comment by jjergus** [comment]
> Most documentation for git

Hmm I've been mostly following github specific documentation, which seems to generally assume that `origin` is your personal fork (e.g. https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork describes adding the original repository as `upstream`).

**Comment by jjergus** [comment]
I wonder if most git documentation predates the "everyone has a public fork" model that github popularized?

**Comment by fredemmott** [comment]
Eh, adding a separate `upstream` is fine too, as long as we document it :)

**Comment by jjergus** [comment]
https://github.com/hhvm/packaging/commit/3e53f625e99f57ca7f68f2ffe1e63b447daf006f

FB-internal: D26416232
