### ISSUE TITLE
Koala

### ISSUE THREAD

**Issue by jakub585** [hhvm/user-documentation#991]
Please complete the information below:

# Where is the problem?

- - - eg "The section describing how widgets work" - - -

# What is the problem?

- - - eg "It doesn't explain that widgets are singletons" - - -

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.94.0:HSL=v4.93.0:2021-01-26T21:58:57+0000:1fa47f258c6b68f8ec01899aa82fd6ffa0957109
 - Page requested: /hhvm/installation/linux
 - Page requested at: Fri, 29 Jan 2021 12:17:09 +0000
 - Controller: GuidePageController

**Comment by fredemmott** [comment]
Closing; if there is a real request here, pleasecomplete the template.
